### ISSUE TITLE
Add export to HTML and DocBook

### ISSUE THREAD

**Issue by GauntletPL** [asciidoctor/asciidoctor-vscode#102]
It would be neat to have a Command Palette option to export created Asciidoc document to HTML and DocBook formats supported by AsciiDoctor.

**Comment by gontadu** [comment]
I second this. Could we get feature parity with the atom version yet?

**Comment by MatteoCampinoti94** [comment]
It's definitely possible. We'll add it to the next update if possible.

**Comment by damgot** [comment]
+1. Export to HTML would be so useful for me :)

**Comment by GauntletPL** [comment]
> 
> 
> +1. Export to HTML would be so useful for me :)

You can try AsciidocFX as a workaround for now. Works for me ;)

**Comment by damgot** [comment]
> 
> 
> > +1. Export to HTML would be so useful for me :)
> 
> You can try AsciidocFX as a workaround for now. Works for me ;)

Yep, but I don't really like AsciidocFX because I have 3 screens (one 4K and 2 1080p), and asciidocFX is very badly rendered on 1080p screen. I have to override the DPI scaling behavior in the application properties. But the font used in the AsciidocFX editor become very ugly and not easyly readble.

**Comment by danyill** [comment]
Thanks for this issue.

Save as HTML is now supported as of 2.7.12. I would like to look further into supporting "Save to Docbook" as that is (only) slightly more difficult to implement.

Generally there is as a desire for additional backends including reveal.js (see #213) which seems like something it would be good to do in a fairly general way.
