### ISSUE TITLE
Bug: Fix link display with commas

### ISSUE THREAD

**Issue by RichardJECooke** [asciidoctor/asciidoctor-vscode#108]
Using syntax from the guide, but it doesn't seem to work: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links

![untitled](https://user-images.githubusercontent.com/5468805/45506792-994e0180-b790-11e8-8b30-547b5de2f220.png)

**Comment by Mogztter** [comment]
It's necessary to escape characters such as underscores (`_`) in URLs. Please read https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/ to learn more about how to handle complex URLs in AsciiDoc.

Please note that you don't need to repeat the URL in the square brackets. Comma is a reserved characters in square brackets used to separate attributes.

You can write the link as follows:

```
link:++http://hz.imslp.info/files/imglnks/usimg/4/4a/IMSLP00010-Beethoven,_L.v._-_Piano_Sonata_10.pdf++[]
```

You can also escape the `_` using `\`:

```
link:http://hz.imslp.info/files/imglnks/usimg/4/4a/IMSLP00010-Beethoven,\_L.v._-_Piano_Sonata_10.pdf[]
```


Alternatively, you can use an attribute.
