### ISSUE TITLE
Enhancement: Don't move the preview when saving the source

### ISSUE THREAD

**Issue by RichardJECooke** [asciidoctor/asciidoctor-vscode#109]
Whenever I save the preview window jumps back to the start. It's the only UX problem I have with the plugin, and it's really tedious.

It would be great if when saving the plugin looked at the longest line of text in the source at the top of the current window, checked if it occurred multiple times, and jumped to the same text location in the new preview window at the same occurrence number.

**Comment by joaompinto** [comment]
I am providing a preview version for the new release at
https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99 .

It fixes this big.

Any feedback is welcome.

**Comment by joaompinto** [comment]
Closed with the release of v2.0.0
