### ISSUE TITLE
Links doesn't work properly

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor-vscode#116]
Example:

```
https://foo.bar/[this is foo site]
```

And here is how it will look inside VS Code:

![bug](https://user-images.githubusercontent.com/18004961/46442449-57522300-c772-11e8-8620-1d04416fa460.PNG)

As you see, the syntax highlighting isn't correct. Aslo, if you click this link, it will open incorrect address:

```
https://foo.bar/[this
```

**Comment by MatteoCampinoti94** [comment]
It's not caused by the extension, the error is in VSCode's uri recognition.
You can test it by putting the same link into a new blank file (`CTRL+N`).

VSCode seems to recognize as link any uri identifier (`file:`, `http:`, etc...) followed by any non-space characters. Something like this I guess: `(https?|file)://\S+`

**Comment by john-cj** [comment]
@MatteoCampinoti94 Well, thank you. In this case I will post it in VS Code repository itself.

**Comment by MatteoCampinoti94** [comment]
:+1:

**Comment by chaseadamsio** [comment]
I was looking at the Sublime AsciiDoctor package (which is what I believe the current regex is "based off of") and the capture groups look different. 

Submlime Regex: https://github.com/asciidoctor/sublimetext-asciidoc/blob/master/Syntaxes/Asciidoctor.tmLanguage#L1390-L1400

When I see links the highlighting captures everything _to_ the apostrophe, including `[`, is it possible that the regex is greedily capturing incorrectly?

example in an asciidoc file:

```adoc
- https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide]
```

![image](https://user-images.githubusercontent.com/1024544/79674162-4d95e200-8195-11ea-91e3-e226fc3efba7.png)
