### ISSUE TITLE
Extension not working on VSCode 1.28.0

### ISSUE THREAD

**Issue by SanderSmee** [asciidoctor/asciidoctor-vscode#117]
- Extension Name: asciidoctor-vscode
- Extension Version: 0.15.1
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 734,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:asciidoc"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by joaompinto** [comment]
I am providing a preview version for the new release at

https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99 .


Any feedback is welcome.

**Comment by SanderSmee** [comment]
Using version 1.0.99 on VSCode 1.29.1 doesn't give any errors. 
Thanks for the fix.
