### ISSUE TITLE
Invitation to join the Asciidoctor organization

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-vscode#119]
Thank you for creating this plugin to support the Asciidoctor ecosystem. I consistently hear praise from users about how it helps them write in AsciiDoc.

I'd like to extend an invitation to this project to join the Asciidoctor organization on GitHub. You should in no way feel obligated to accept. However, by accepting, we may be able to better collaborate, in particular by aligning functionality with the plugins Atom and IntelliJ. Since the Atom plugin is based on the same technology, there may even be an opportunity to share code.

This is also a general invitation to collaborate with the Asciidoctor project. VSCode is a very important tool for writers and we want to make sure we do everything we can do to support this plugin.

cc: @mogztter @ldez

**Comment by joaompinto** [comment]
@mojavelinux, I am ok with the change,  can you please create an asciidoctor-vscode repository within the organization and provide me commit privileges ?

Due to the required major change to the WebView API (https://github.com/joaompinto/asciidoctor-vscode/issues/123), the new repository will be populated from scratch.

As far as possible the new code will be based on the VSCode core markdown plugin, this should grant the same level of features that are currently available for Markdown.

**Comment by diguage** [comment]
@joaompinto Thank you very much!

@mojavelinux Congratulation！

**Comment by mojavelinux** [comment]
I'm so happy that you accepted, @joaompinto! Welcome! I'll get the repo set up asap.

I'll create the repository as requested and make you the administrator. You'll still be the owner of the project, so nothing about that changes. Just the location. You're free to run the project in the way that works best for you and your users. If you want to populate it from scratch, go for it.

> As far as possible the new code will be based on the VSCode core markdown plugin, this should grant the same level of features that are currently available for Markdown.

Very excellent.

**Comment by mojavelinux** [comment]
Actually, before I do that, would you like to transfer the repository to preserve the issues and pull requests? I've given you permission to transfer, so you should be able to proceed with it.

**Comment by mojavelinux** [comment]
Once the repository is transferred, you can still force push a fresh code base, if that's what you prefer.

**Comment by joaompinto** [comment]
I was not able to transfer, got the error: "You don’t have the permission to create repositories on asciidoctor "

**Comment by mojavelinux** [comment]
Aha. That might be because you first need to join Asciidoctor. I've sent an invite. You can visit https://github.com/asciidoctor to accept. Once you accept, then the transfer should work. Then just reply here.

**Comment by joaompinto** [comment]
@mojavelinux Done. Thank you very much for the invitation.

**Comment by mojavelinux** [comment]
We're glad to have you as part of the maintainer community!

I created a team called vscode-extension-maintainers, added you to it, and gave the team admin permission to the repo. If there's anything else you need, just @ me.

When you get a chance, please update the logo for the extension to be the official logo. You can find it here: https://github.com/asciidoctor/brand
