### ISSUE TITLE
Issue with comment toggling

### ISSUE THREAD

**Issue by hsablonniere** [asciidoctor/asciidoctor-vscode#121]
Hey ;-)

I'm trying to toggle lines or blocks with keyboard shortcuts but it's not working.

* Is this feature supported?
* Do I need to configure something?
* Can I help if needed?

Cheers,
Hubert

**Comment by MatteoCampinoti94** [comment]
I'm so sorry for getting back to you so late.

Yes the extension does support line comment toggling via `CTRL+/` (I believe it's `CMD+/` on Mac).

For multiline comments use `CTRL+SHIFT+A` (`CMD+SHIFT+A` on Mac), remember that you need both `////` to be the only thing in their respective lines. Id est:
```asciidoc
////
This lines are considered comments
Line 2
...
Line n
////

//// This is not a comment ////

////
This is also not a comment ////
```

It might be that some other extension is overriding the shortcut if it is not working for you.

Once again, sorry for the delay :(

**Comment by hsablonniere** [comment]
I discovered that a few weeks ago. I should have close the issue with a comment, sorry.

**Comment by MatteoCampinoti94** [comment]
Don't worry, we should have answered you earlier ^^
