### ISSUE TITLE
Preview fails with command 'adoc.previewToSide' not found

### ISSUE THREAD

**Issue by derheap** [asciidoctor/asciidoctor-vscode#122]
In Visual Code 1.28.2 on OSX 10.13.5 after installing the Extension, I select the Preview to to side command. 
But the Preview fails with

`command 'adoc.previewToSide' not found`

**Comment by joaompinto** [comment]
I am providing a preview version for the new release at

https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99 .


Any feedback is welcome.
