### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [asciidoctor/asciidoctor-vscode#123]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by joaompinto** [comment]
@mjbvz thanks for letting me no, I had such change planned but I will now set it as priority.

**Comment by joaompinto** [comment]
I am providing a preview version for the new release at https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99. Any feedback is welcome.

**Comment by joaompinto** [comment]
Closed with the release of v2.0.0
