### ISSUE TITLE
Preview doesn't show includes

### ISSUE THREAD

**Issue by mvuijlst** [asciidoctor/asciidoctor-vscode#125]
I have the following code:

`include::admin.adoc[]`

Until recently this rendered perfectly; now I get

`Unresolved directive in <stdin> - include::admin.adoc[]`

VS Code 1.28.2, Mac.

**Comment by joaompinto** [comment]
The previous update (1.0.0) was broken. Please update to v1.0.1, reopen this issue if you still have a problem.
Thanks
