### ISSUE TITLE
Preview issue after update to 1.29

### ISSUE THREAD

**Issue by G3ph4z** [asciidoctor/asciidoctor-vscode#126]
OS: Debian 9.6
vSCode: 1.29.0

I just updated my vscode from 1.28 to 1.29 and now, its broken.

When I try to open the preview I get this error message:
`command 'markdown.extension.togglePreview' not found`

**Comment by joaompinto** [comment]
Could you please confirm that you are using the latest extension version which is 1.0.1 ?

That error seems to be related to a broken 1.0.0 update.

Thanks for reporting.

**Comment by joaompinto** [comment]
Sorry, can you upgrade now to 1.0.2 ? Please make sure you have closed all code instances after updating the plugin. I am sure the "markdown.extension.togglePreview" was not present in 1.0.1, so a previous version of the extension is running somehow...

**Comment by G3ph4z** [comment]
Ofc. I am on 1.0.2 right now, but it still doesn't work. I closed everything and reinstalled the plugin.

Version:
![image](https://user-images.githubusercontent.com/26697727/48473623-20534080-e7f9-11e8-82db-f1cc5d85b5d8.png)

Error message:
![image](https://user-images.githubusercontent.com/26697727/48473607-17fb0580-e7f9-11e8-860c-ae7d3f3dd9c6.png)

**Comment by joaompinto** [comment]
Could you please provide the ouput from:
`grep -r markdown.extension.toggle ~/.vscode/extensions`

**Comment by G3ph4z** [comment]
```
  grep -r markdown.extension.toggle ~/.vscode/extensions
/home/denes/.vscode/extensions/yzhang.markdown-all-in-one-1.7.0/package.json:                           "command": "markdown.extension.togglePreview",
/home/denes/.vscode/extensions/yzhang.markdown-all-in-one-1.7.0/package.json:                           "command": "markdown.extension.togglePreviewToSide",
/home/denes/.vscode/extensions/yzhang.markdown-all-in-one-1.7.0/out/src/preview.js:    context.subscriptions.push(vscode_1.commands.registerCommand('markdown.extension.togglePreview', () => {
/home/denes/.vscode/extensions/yzhang.markdown-all-in-one-1.7.0/out/src/preview.js:    }), vscode_1.commands.registerCommand('markdown.extension.togglePreviewToSide', () => {
```

**Comment by BogdanI-FintechOS** [comment]
~ on Nov 9th VSCode (1.28.2) notified that v1.0.0 is available and I installed it. This resulted in a broken preview. Switching between the preview pane and the editor would reset the preview to the top. Moving the caret through the editor would do nothing for the preview pane (it just stayed at the top).

I went through an obscure method to manually download and revert to 0.15.2.

The big problem is how easy it was for my workflow to brake (without preview .adoc editing is much more difficult) and how difficult it was to revert to a good state. Also, there is no sign on github.com/asciidoctor/asciidoctor-vscode that v1.0.* exists or is worked on. v0.15.2 is also not on github. v1.0.0 just popped up out of nowhere on VSCode marketplace.

I'm fully aware I get this for free but please consider how destructive such instability is. Nobody needs new features if the price is a breakdown in workflow for multiple doc writers. Please go through a slower or gated release procedure to avoid breaking something that cannot be fixed: confidence.

Note: I disabled updates for all extensions and so didn't try v1.0.1 or v1.0.2.

**Comment by joaompinto** [comment]
@BogdanI-FintechOS , the release of v1.0.0 was an accidental action from my part, I have published a development branch to the marketplace, v1.0.2 is just a version bump from v0.15.2, adding  association with ".asc" files.

I understand your frustration, I will try to improve the release process by adding a more structured flow with automated testing before release.

**Comment by joaompinto** [comment]
@G3ph4z , that error seems to be caused by the extenstion "yzhang.markdown-all-in-one", please uninstall it, reload vscode, and try again.

**Comment by G3ph4z** [comment]
@joaompinto Haha, you have right. Thank you!
