### ISSUE TITLE
Please publish the lastest version to VS Code marketplace.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-vscode#127]
I see that the marketplace still has the v1.0.2. Can we get an update?

**Comment by joaompinto** [comment]
I am providing a preview version for the new release at

https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99 .


Any feedback is welcome.

**Comment by ravipinto** [comment]
@joaompinto, I have downloaded and applied the preview. What changes do I look out for?

**Comment by joaompinto** [comment]
Closed with the release of v2.0.0
