### ISSUE TITLE
Image preview not working

### ISSUE THREAD

**Issue by ruku320** [asciidoctor/asciidoctor-vscode#128]
I'm using the v1.0.99 pre-release and image preview doesn't seem to be working.  The preview only shows the name of image file without the extension.

**Comment by joaompinto** [comment]
Can you please provide the adoc that you used ? Also please check if you get some kind of security warning on the end of the preview page, the new preview system blocks some items by default.

**Comment by ruku320** [comment]
Here's the adoc and the image:
[test.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/2592315/test.zip)

This is what I see in vscode:
![vscode](https://user-images.githubusercontent.com/17328958/48666340-a12a6a80-ea8d-11e8-8398-a2b1b565afe8.png)

**Comment by joaompinto** [comment]
This is fixed on preview2:

You can get it from:
https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.100
