### ISSUE TITLE
GoTo symbols and outline do not work in vscode ^1.29.1

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-vscode#133]
I have noticed that outline and goto symbols (`ctrl+shift+o`, `ctrl+p @`) seem to not work anymore after updating VSCode to version 1.29.

Have tested downgrading to VSCode 1.27 and they work fine there.

Have also taken a look in the logs to see if there was any error, but could only found one related to foldingProvider.js.

**Comment by MatteoCampinoti94** [comment]
Seen the response to PR #111, I guess the issue should be closed since it's in the roadmap?

**Comment by joaompinto** [comment]
@MatteoCampinoti94 is ok to leave it open to keep track on it. Adapting the markdown code will probably require a significant effort in such a way that it will need to be tracked on different issues.

**Comment by MatteoCampinoti94** [comment]
@joaompinto :+1:

**Comment by danyill** [comment]
I'll close this -- the Outline View/Symbols seems to be working satisfactorily since about 2.7.7. 

Please feel free to reopen if I've misunderstood.
