### ISSUE TITLE
v2.0.1 preview out of sync with editor (was ok with v0.15.12)

### ISSUE THREAD

**Issue by BogdanI-FintechOS** [asciidoctor/asciidoctor-vscode#137]
This config worked relatively OK: vscode v1.29.1 + asciidoctor-vscode v0.15.2 + Philips 223V5LSB/00 21.5" 1920x1080 in full screen

Upgraded to v2.0.1 and ran into multiple issues with preview. Ultimately had to revert to v0.15.2.

1. Preview syncs very badly with active editor, often keeping the in-editing paragraph outside the area visible in preview, making the preview useless. I have to scroll the preview slightly down to view what I've edited and as soon as I start editing again the preview immediately jumps to its useless position.

example image 1, point 1: TOC overlaps main preview area unless I move preview to about 80% of the screen, to the point where I don't have any more space for even a single editor

example image 1, point 2-3: In-editing paragraph is not visible in preview

example image 1:
![example image 1](https://user-images.githubusercontent.com/35227468/49381510-c6210d80-f71c-11e8-9d57-a5f7a08f8e11.png)

example image 2, point 4-5: With 2 editors (my normal configuration), the problem is similar.

example image 2:
![example image 2](https://user-images.githubusercontent.com/35227468/49381557-e2bd4580-f71c-11e8-875b-b34a56ffa9a3.png)

2. Syntax highlight with highlightjs didn't work unless I set Markdown preview security to disable. This I could live with.

v0.15.2 is far better in keeping the in-editing paragraph visible in preview at all times.

example image 3:
![example image 3](https://user-images.githubusercontent.com/35227468/49381850-8dcdff00-f71d-11e8-8150-c1874dc5345f.png)

If anyone else wants to revert, download the previous version from: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/joaompinto/vsextensions/asciidoctor-vscode/0.15.2/vspackage

**Comment by danyill** [comment]
Thanks for filing this issue.

The overlap of the TOC on the contents has been fixed in the latest version of the extension.

I think the visibility of in-editing paragraphs is improved for Example 1 and also I hope Example 2 (it's difficult to reproduce if you can't provide the text of your Asciidoc example).
Example 3 I could imagine is difficult as the block for the table gets "given" a line number in processing, but the individual table rows do not. I may look into this.

Could you test with the latest version and let us know if you are still concerned please.

**Comment by danyill** [comment]
We can do better with table cells if https://github.com/asciidoctor/asciidoctor/issues/1338 is implemented, in fact it may occur automatically because each cell is a block and would naturally get a line number provided to it if the converter supported this.

**Comment by BogdanI-FintechOS** [comment]
@danyill I tried it on my adoc with vscode v1.42.1 + asciidoctor-vscode v2.7.13. Things are much better now, the preview is usable and seems to keep well in sync with the editor.

There is a new (smaller) problem but I won't create a new issue for it. I now have a much larger monitor (34" 3440x1440) and the preview uses a font that is much larger than the font in the editor so it can only physically fit about 50% of what I can see in the editor. The result is I can only see in preview the top half of what I'm editing in the editor. I can work around this issue but if it's possible, it could be a good ideea to dynamically adjust the size of the font used by the preview to fit in about the same amount of info as in the editor. I realize this might be very difficult to compute since the amount of info shown in preview also depends on the width used for both the editor and the preview.

**Comment by BogdanI-FintechOS** [comment]
I now can provide you with my adoc since it has become public in the mean time: [Installation Guide.adoc.txt](https://github.com/asciidoctor/asciidoctor-vscode/files/4286977/Installation.Guide.adoc.txt)
