### ISSUE TITLE
[discussion] Preview background

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-vscode#139]
I was wondering about the possibility of rendering the asciidoc preview with the same style as the markdown one. i.e. using the background and font color of the editor.

I have played around with `media/asciidoctor.css` and removing the `background` and `color` fields from `body` gives this result:
![screenshot from 2018-12-04 13-14-34](https://user-images.githubusercontent.com/5142004/49441390-9cbcbc00-f7c6-11e8-9c76-ea7bc39b20b4.png)

It does of course require a lot more work to ensure all the colors and backgrounds are actually readable, but looking at the built-in `markdown.css`, at least some of them _should_ be inherited directly from the editor (I think, am not a front-end developer so css, less, etc.. are still somewhat mysterious to me, though I grasp the basic concepts).

Would this be something desirable?
I'm not 100% sure if the asciidoc documentation has a "mendatory" style or if there are elements that cannot be rendered any other way.
I use asciidoc mostly for writing fiction and documentation, and having the option to see the preview in the same style as the editor would be helpful, especially with dark themes. With the current style the preview is quite blinding at night.

**Comment by joaompinto** [comment]
I agree on removing the explicit colours for background, by default eventually it makes sense to change to the a markdown css copy. Asciidoc does not impose any specific format, we just need to make sure the CSS provides a good result. We also need to be careful on it's potential impact on the PDF printing option.

**Comment by MatteoCampinoti94** [comment]
Hmmm, could we point the pdf rendered to a second .css? We would simply need to make a copy of the current one and call it asciidoctor-pdf.css or something like that.

**Comment by joaompinto** [comment]
We can, on text-parser.ts AsciiDocParser will need a new paramenter (private readonly printable: bool), and then on exportpdf call it with True, and from renderengine False. And on the convert to code, we need to set the css filename depending on the "printable" value .

**Comment by MatteoCampinoti94** [comment]
I'll try to do a quick test then :+1:

**Comment by MatteoCampinoti94** [comment]
Did it :3
In the end it was easier to use an argument, called it `preview`. When the parser is called from `previewContentProvider.ts` then it's passed as `true` and `ascidoctor-preview.css` is used. When called from `exportAsPDF.ts` then `false` is passed instead.
It was much easier than I thought.

Also removed background and color from body in `ascidoctor-preview.css`, just to start.

Made a pull request #140
