### ISSUE TITLE
Preview renders incorrectly with toc:left

### ISSUE THREAD

**Issue by mvuijlst** [asciidoctor/asciidoctor-vscode#141]
The table of contents is incorrectly rendered over the text when toc is set to left when your window is not wide enough. 

When asciidoctor renders to html, the toc gets a width of 15 or 20em, and the body a corresponding padding-left of 15 or 20em. 

This does no longer seem to happen in asciidoctor-vscode. 

Correct:

![correct](https://user-images.githubusercontent.com/4365702/49502752-12339580-f876-11e8-8fca-1084f985846c.png)

Incorrect:

![incorrect1](https://user-images.githubusercontent.com/4365702/49502754-12339580-f876-11e8-84d2-76352a38578e.png)

![incorrect2](https://user-images.githubusercontent.com/4365702/49502756-12339580-f876-11e8-9928-ca1247dd98d6.png)

**Comment by mvuijlst** [comment]
I took advantage of VS Code's _Install another version_ to pinpoint when the problem arose.

This is v.1.0.2:

![image](https://user-images.githubusercontent.com/4365702/49903264-ea8c9080-fe66-11e8-85a9-a9a822ba49e9.png)

This is exactly the same thing in v.2.0.0:

![image](https://user-images.githubusercontent.com/4365702/49903242-d6e12a00-fe66-11e8-9068-de5dfd488d77.png)

**Comment by mvuijlst** [comment]
It's particularly annoying in the side by side preview. 

![image](https://user-images.githubusercontent.com/4365702/50375668-b13fe780-0601-11e9-9603-b86657709f2a.png)

**Comment by brkerez** [comment]
Any progress with this ? It's quite a blocker for effective Asciidoc writing in VS Code. 

It's broken also with `:toc: right` - in that case TOC is displayed on the left side and it's rendered over the text.

![image](https://user-images.githubusercontent.com/313735/67271611-1d59d900-f4bb-11e9-9865-ed89fc3a07c2.png)

**Comment by ebousse** [comment]
Same problem here, and if anyone has a workaround I'm interested :)

**Comment by danyill** [comment]
What would you like the preview to show?

**Comment by ebousse** [comment]
With `:toc: left` I have currently the same faulty rendering as @brkerez above ([link to his screenshot](https://user-images.githubusercontent.com/313735/67271611-1d59d900-f4bb-11e9-9865-ed89fc3a07c2.png)), where the TOC is shown above the text, which hides a big part of the document.

I would like to have the same correct rendering as when I generate html and open it in a browser, which means the toc is shown next to the text, and not above. This is the behavior that existed in 1.0.2, apparently, as pinpointed by @mvuijlst ([link to his screenshot](https://user-images.githubusercontent.com/4365702/49903264-ea8c9080-fe66-11e8-85a9-a9a822ba49e9.png)).

**Comment by danyill** [comment]
Thanks @ebousse -- the way we process the Asciidoctor output in the preview is a bit hacky which I think has caused this. This whole extension was rebuilt for v2 due to significant upstream changes in VS Code.

@brkerez if this is a blocker for you, just unset the `toc` attribute when writing.

I've done a PR which fixes this issue (for both `left` and `right` but the fix is not as robust as I'd like it to be). If anyone is able to test this and comment I'd be grateful.

**Comment by ebousse** [comment]
Thanks for the answer and looking forward to test the next release then! :)

**Comment by brkerez** [comment]
> Thanks @ebousse -- the way we process the Asciidoctor output in the preview is a bit hacky which I think has caused this. This whole extension was rebuilt for v2 due to significant upstream changes in VS Code.
> 
> @brkerez if this is a blocker for you, just unset the `toc` attribute when writing.
> 
> I've done a PR which fixes this issue (for both `left` and `right` but the fix is not as robust as I'd like it to be). If anyone is able to test this and comment I'd be grateful.

It works for me now ;) Thanks, much appreciated! Disabling toc is what I was doing since I started editing asciidoc in vs code but that was very annoying workaround as I often forgot to enable it when I was finished :)   !
