### ISSUE TITLE
Broken links on diagrams in preview (asciidoc.use_asciidoctor_js: false)

### ISSUE THREAD

**Issue by mrumpf** [asciidoctor/asciidoctor-vscode#142]
Rendering the images locally works, but displaying does not.
I use the settings from #132 and I can see that the images are created in my "images" sub-folder

````
"asciidoc.use_asciidoctor_js": false,
"asciidoc.asciidoctor_command": "asciidoctor -r asciidoctor-diagram -o-",
````

````
[plantuml, diagram-classes2, png] 
----
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
----
````

I get a file
./src/.asciidoctor/diagram/diagram-classes2.png.cache
and the actual png
./images/diagram-classes2.png

Unfortunately in preview mode the diagram does not get rendered.

In the logs of the developer console I see the following message:
````
[Embedded Page] Not allowed to load local resource: file:///<project-root-folder>/images/diagram-classes2.png
````
BTW, the same happens for graphviz files!

Environment
* MacOS Mojave 10.14.1
* VSCode 1.29.1
* AsciiDoc Extension 2.1.0

**Comment by luminize** [comment]
I have the same problem.
I run asciidoctor locally too (Debian Stretch)
Visual Studio code code_1.27.2-1536736588_amd64.deb wit accompanying plugin works, but when I switch to 1.28 and above the preview window renders the text output without showing the diagrams.

**Comment by luminize** [comment]
Thanks @joaompinto The diagrams get rendered again
