### ISSUE TITLE
problem in pdf

### ISSUE THREAD

**Issue by saberery** [asciidoctor/asciidoctor-vscode#143]
I have tried many times for exporting the pdf of the asciidoc but it does not show the image, no Plantuml or the imported image since the version 2.0.0. Though the preview does not show any problem, is there any body who knows how to fix it?

**Comment by MatteoCampinoti94** [comment]
Could you share the block that previews incorrectly?

As a temporary solution you can set `asciidoc.use_asciidoctorpdf` to `true`. This makes the extension use the ruby implementation asciidoctor-pdf to render the pdf.

**Comment by mischn1980** [comment]
I have a similar problem. The preview shows the formatting and the tables cleanly. The PDF export creates the PDF without formatting (no table lines, etc).

**Comment by MatteoCampinoti94** [comment]
Sorry for getting back to you so late.

The PDF converters are not part of the extension, so we cannot really troubleshoot problems that depend only on them. I've looked at our code, but couldn't find anything that would cause those problems.

**Comment by mischn1980** [comment]
Thanks for your repley.
