### ISSUE TITLE
Support relative paths on includes

### ISSUE THREAD

**Issue by andresbm05** [asciidoctor/asciidoctor-vscode#144]
If you use relative paths within an include tag, the include is not rendered and shows an error saying:
Unresolved directive in <stdin> - include::./relative/path/to/file[]

**Comment by MatteoCampinoti94** [comment]
That's not a bug. The correct syntax is `include::path/to/file[<attributes list>]`

For more info see https://asciidoctor.org/docs/user-manual/#include-directive

**Comment by andresbm05** [comment]
With [path] I meant that it prints the path you put, anyway I already changed it.
The real bug is that using a relative path does not work anymore at the preview, it says Unresolved directive.
As info, in v1 that was working perfectly

**Comment by MatteoCampinoti94** [comment]
That's weird. I've tried `include` with both `ascidoctor_js` and `ascidoctor` and they both preview without problems.

Could you share the `include` statement that doesn't work?

**Comment by andresbm05** [comment]
All statements with relative paths were failing, for example one of them was `include::./include/variables.adoc[]`. However I changed to asciidoctor_js and back to pearl one and the error disapeared.
Thanks for the help
