### ISSUE TITLE
diagrams in preview in side window do not update

### ISSUE THREAD

**Issue by luminize** [asciidoctor/asciidoctor-vscode#146]
Previewing in a new tab works, changing the asciidoc source changes the preview (CTRL + SHIFT + V), however when opening the preview on the side (CTRL+K, V) the preview does not update when changing the asciidoc source.

I'm using the system (Debian) asciidoctor, with asciidoctor-diagram
```
    "asciidoc.use_asciidoctor_js": false,
    "asciidoc.asciidoctor_command": "asciidoctor -r asciidoctor-diagram -o-",
    "[asciidoc]": {
        "editor.wordWrap": "off",
        "editor.quickSuggestions": false
    }
```

**Comment by luminize** [comment]
Apologies, I need to be more specific. Updating the text works as expected, this is about the asciidoctor-diagram diagrams not updating.

**Comment by pomdtr** [comment]
Alternatively, if you work with plantuml, you can use the asciidoctor.js preview, and see the change as you type.

You need to define the attribute : `:plantuml-server-url: http://www.plantuml.com/plantuml`

Next use this syntax to draw your diagram :
```
[plantuml]
----
@startuml
Bob --> Alice
@enduml
----

**Comment by MatteoCampinoti94** [comment]
@luminize, as @pomdtr said, you can use the `plantuml-server-url` attribute and set `asciidoc.use_asciidoctor_js` to `true` and the diagrams will redraw automatically.

Your solution to put `-r asciidoctor-diagram` in the command option is correct, but with the way it works you need to save it for the diagrams to be redrawn (just tapping `CTRL+S` is enough).

I'm not 100% sure why that is the case though, the asciidoctor preview does update when text is inputted, it's just the diagrams that aren't redrawn without saving the content.

**Comment by MatteoCampinoti94** [comment]
And sorry for the delay :'(
Hope it wasn't too problematic.
