### ISSUE TITLE
Make preview style easily configurable

### ISSUE THREAD

**Issue by mvuijlst** [asciidoctor/asciidoctor-vscode#148]
While the issues mentioned in #139 are valid (it can be jarring to see a preview on a white background while editing in an otherwise dark environment, you're not necessarily interested in what the PDF version will look like, ...), there can be valid reasons to actually want to see the preview the way it used to be rendered. 

I am producing a file that will eventually end up as a document in black on white, I'd like to see it a little closer to what it will look like. What I see now is really not usable. 

![image](https://user-images.githubusercontent.com/4365702/49858560-88e00e00-fdf5-11e8-9b21-b42047934566.png)

I suggest making an option out of #139: either "use standard css for preview yes/no" or "follow VS code theme for preview yes/no".

I looked into the  `asciidoc.styles` configuration option, but as my project has many folders of asciidoc files and will be used in many enviroments (also off-line), it's just not a viable option.

**Comment by MatteoCampinoti94** [comment]
Solved with #149.

A new option has been added asciidoc.preview.useEditorStyle of type bool:
* `true`
the modified .css is used which partially inherits the editor style.
* `false`
original .css is used instead.

Furthermore setting `asciidoc.use_asciidoctor_js` to `false` forces the extension to use the system-installed `asciidoctor` command which uses its own stylesheet (the default one).
