### ISSUE TITLE
Add MatteoCampinoti94 to the asciidoctor organization

### ISSUE THREAD

**Issue by joaompinto** [asciidoctor/asciidoctor-vscode#150]
@mojavelinux could you please add @MatteoCampinoti94 to the asciidoctor organization ? 
He has been actively contributing so I would like to add him to the vscode-extension-maintainers team to provide him access rights to the master branch.

Thanks

**Comment by MatteoCampinoti94** [comment]
Wow! Thanks @joaompinto! :D

**Comment by mojavelinux** [comment]
Certainly!

**Comment by mojavelinux** [comment]
Welcome @MatteoCampinoti94! I'll send you an invite.

**Comment by MatteoCampinoti94** [comment]
Thank you both! :D
