### ISSUE TITLE
Publish version 2.2.0 & 2.3.0

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-vscode#151]
**New version [v2.2.0](/asciidoctor/asciidoctor-vscode/releases/tag/v2.2.0)**

New features:
* Add option to use editor or default style in preview
* Snippets

Fixes:
* Fix documents with apostrophe in path not rendering with manual command

**Comment by MatteoCampinoti94** [comment]
**New version [v2.3.0](/asciidoctor/asciidoctor-vscode/releases/tag/v2.3.0)**

New features:
* Add option to use asciidoctor-pdf instead of wkhtmltopdf

Fixes:
* Fix PDFs with single quotes in path not opening from the notification after running exportAsPDF

**Comment by joaompinto** [comment]
Published 2.3.0, the vscode marketplace does not support multiple versions so we always need to do a single release :)

**Comment by MatteoCampinoti94** [comment]
Oh okay, I thought it even allowed to install a specific version

**Comment by alhalama** [comment]
VS Code does allow [installing past versions](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) if there are issues with the current release.  For both versions to be available in that list it would have been necessary to release 2.2.0 and then later release 2.3.0.

**Comment by MatteoCampinoti94** [comment]
It might be useful if something is broken and we don't realize it, users could roll back to a previous release while waiting for a fix.

**Comment by joaompinto** [comment]
If a release is broken, we must fix it :P

**Comment by alhalama** [comment]
They would also still have the option of using the older previous version so releasing two at one time doesn't add much value.

**Comment by MatteoCampinoti94** [comment]
Pity the repo is not on gitlab, it has CI built in.
We could make a repo there with automatic pull and testing (it doesn't even need to be public, private repos are free on gitlab), but some functions are a bit hard to test.
