### ISSUE TITLE
Pipe operator escaping in table is not rendered correctly

### ISSUE THREAD

**Issue by helmbold** [asciidoctor/asciidoctor-vscode#152]
The following code block with escaped pipe operators inside a table is not rendered correctly:

```asciidoc
[cols="2,8a,1"]
|===
|A |B |C  

|a
|File: SomeFile.java
----
final boolean result = ((filterValue == null) \|\| 
    (filterValue.getName().length() == 0) \|\| 
    ((device.getSite() != null) && 
    (device.getSite().getName() != null) && 
    device.getSite().getName().toLowerCase().contains(filterValue.getName().toLowerCase())));
----
|115

|x
|y
|z
|===
```
The rendered result in VS Code looks like this:

![asciidoctor-vs-code](https://user-images.githubusercontent.com/5079980/50231077-43e84880-03ae-11e9-80a7-dbfdaf53170e.png)

And this is how it should look like (rendered with AsciiDoctory, Ruby implementation):

![asciidoctor-ruby](https://user-images.githubusercontent.com/5079980/50231084-46e33900-03ae-11e9-8150-ba1c01580de1.png)

Affected plugin version: 2.3.0 with VS Code 1.30.0

**Comment by MatteoCampinoti94** [comment]
As a temporary solution you can try using asciidoctor (Ruby) for the preview by setting the `asciidoc.use_ascidoctor_js` option to `false`.

At the moment the preview works by piping the content of the editor to the preview render, so escaped characters do not always work.

**Comment by helmbold** [comment]
Thanks for the hint! Using the Ruby version works, even it is not as fast and convenient as asciidoctor.js

**Comment by MatteoCampinoti94** [comment]
You're welcome @helmbold ^.^

If you have the same problem with the PDF export you can set the `asciidoc.use_ascidoctorpdf` option to `true`. The PDF will then be rendered by asciidoctor-pdf.

`asciidcotor.js` isn't handled in this repo, we only use the node. I'll see what we can do on our end but it might take a while to solve this bug.

PS: the asciidoctor.js preview doesn't work exactly like that, text piping is actually what the extension does with the Ruby version, my bad.

**Comment by danyill** [comment]
@helmbold this appears to be working fine in 2.7.12. We've moved at least one Asciidoctor.js version since then.

Preview output:

![image](https://user-images.githubusercontent.com/674783/74482269-1139d180-4f19-11ea-9b0c-206abfba548b.png)

I'll close this, feel free to re-open if you have outstanding concerns.
