### ISSUE TITLE
In-editor syntax-highlighting

### ISSUE THREAD

**Issue by pomdtr** [asciidoctor/asciidoctor-vscode#153]
It would be nice to have code-blocks highlighting based on the source language (similarly to the built-in markdown syntax-highlighter)

![screenshot at 2018-12-22 19-25-39](https://user-images.githubusercontent.com/36007425/50377543-6b921780-061f-11e9-94b4-885070a405d6.png)

**Comment by MatteoCampinoti94** [comment]
As of commit [59f11f5](/asciidoctor/asciidoctor-vscode/commit/59f11f5) fenced code blocks are now highlighted in the editor.

At the moment this only works with blocks fenced by backticks:
```
    ```go
    fmt.Println("Hello world!")
    ```
```

Furthermore, only the full name of the language is supported atm (i.e. ruby not rb, python not py, etc...).
