### ISSUE TITLE
Table of Contents floating

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#156]
ToC seems to be floating in version and scrolling with the VS 1.30.2 As I scroll down the preview the ToC scrolls with it.

I am using `:toc: left`

![image](https://user-images.githubusercontent.com/674783/51278342-32db3780-1a3f-11e9-9b5c-bf708bd6a56b.png)

This seems similar but quite different to https://github.com/asciidoctor/asciidoctor-vscode/issues/141

**Comment by MatteoCampinoti94** [comment]
Could you try previewing the same document using the system-installed asciidoctor? (set `asciidoc.use_asciidoctor_js` to `false` in your settings)

I'll try to reproduce it on my end too.

**Comment by MatteoCampinoti94** [comment]
The problem seems to be tied to `asciidoctor_js`. It's the AsciiDoc to HTML engine that the extension uses but it is not developed in this repository. I'll see if I can transfer the issue to [/asciidoctor/asciidoctor.js](/asciidoctor/asciidoctor.js).

**Comment by MatteoCampinoti94** [comment]
Sorry to disturb you @joaompinto, but I don't seem to have the necessary permissions to transfer the issue to [/asciidoctor/asciidoctor.js](/asciidoctor/asciidoctor.js) myself.

**Comment by MatteoCampinoti94** [comment]
Ah nevermind, seems the problem is down to the styling overhaul we applied.

@danyill could you please try previewing your document setting `asciidoc.preview.useEditorStyle` to `false`?

**Comment by MatteoCampinoti94** [comment]
The transparency fix has a temporary fix now. Until we find a way to use the editor's background for the toc it will use the default style.

The side toc shadowing the main content has not been fixed.

**Comment by danyill** [comment]
👍 you are super fast! thanks 🎁

**Comment by MatteoCampinoti94** [comment]
You're welcome @danyill! :smile:

Hopefully we'll manage to fix the shadowing and transparency for good soon :)
