### ISSUE TITLE
asciidoctor basedir sticky after first opened preview

### ISSUE THREAD

**Issue by mjtrjk** [asciidoctor/asciidoctor-vscode#161]
When opening a preview window, an instance of `AsciiDocParser` is created with the current file path. This consequently sets the basedir for `asciidoctor` app invocation.
When changing the document, the parser instance is not recreated thus keeping the basedir consequently causing all relative path references (like `include::*` or diagrams) to fail to resolve.

After removing the `if` condition in https://github.com/asciidoctor/asciidoctor-vscode/blob/267c5de7ae0556d2eb5c9e9e8e94b536eff45bd0/src/markdownEngine.ts#L28 , paths and diagrams update again.

**Comment by mjtrjk** [comment]
#146 maybe related

**Comment by Mogztter** [comment]
Probably fixed in recent versions. If not, please reopen.
