### ISSUE TITLE
Add template replication shortcut

### ISSUE THREAD

**Issue by nakamuloud** [asciidoctor/asciidoctor-vscode#163]
When creating new document, I have to copy .css and .yaml theme files into target dir.
I suggest new shortcut that copy template files from Template dir.

**Comment by MatteoCampinoti94** [comment]
Which template files? Asciidoctor-pdf or -epub3? We could do it but then again the styles are easily downloadable from the respective repositories, and we would have to keep the copies in our extension up to date.

I'll look into having the extension download them from the respective repos, but can't promise anything.

**Comment by nakamuloud** [comment]
thanks, I am looking forward to that. XD
