### ISSUE TITLE
'stem' and 'latexmath' are not rendered properly

### ISSUE THREAD

**Issue by no-simpler** [asciidoctor/asciidoctor-vscode#165]
macOS 10.14.2
VSCode 1.31.1
AsciiDoc extension 2.3.3

`stem:[x]` is rendered to textual `\$x\$`.

`latex:[y]` is rendered to textual `\(y\)`.

LaTeX math blocks (`[latexmath]` and  `++++`) are rendered incorrectly as well, but with `\[ … \]` delimiters.

- [x] `:stem:` attribute is set in the header.
- [x] VSCode’s 'Preview security setting' is set to 'Disable'.
- [x] AsciiDoctor.js is selected in settings, as is default.
- [x] Chrome’s 'AsciiDoctor.js Preview' extension renders the file correctly.
- [x] On my Windows PC, VSCode with this extension and same settings renders the file correctly.

It seems like something is blocking Mathjax libraries from downloading. But it’s apparently not VSCode’s preview security settings. What else could be at play?

**Comment by MatteoCampinoti94** [comment]
Hmmm, the same error occurs on Linux as well, and with both js and ruby previewers.

The problem does not appear when converting the files via command line though.

I think the issue might be with how the preview works. The extensions gets the text from the current document and then feeds it via stdin to the previewer, either js or ruby. It might be that the backslashes are escaped incorrectly.

I will run some tests, might have to ask you to repeat them on your machine @no-simpler, I do not have MacOS at home.

**Comment by MatteoCampinoti94** [comment]
Dang close button with no confirmation.

**Comment by MatteoCampinoti94** [comment]
Found the error:
```
[Embedded Page] Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.6.0/MathJax.js?config=TeX-MML-AM_HTMLorMML' because it violates the following Content Security Policy directive: "script-src 'nonce-1550504880972972'".
```

Problem is I honestly have no idea what `script-src 'nonce-1550504880972972'` means X3

**Comment by MatteoCampinoti94** [comment]
Found a workaround!

In the preview you need to click the text at the bottom saying that some content is disabled, and disabled preview security from there.

Seems that there is some mixing with the markdown preview security.

**Comment by no-simpler** [comment]
Can confirm, workaround works on macOS.

**Comment by MatteoCampinoti94** [comment]
I've pushed a small update that fixes part of the problem. AsciiDoc preview security is now its own setting which you can select via the command palette: `AsiiDoc: Change Preview Security Setting`.

The button inside the preview still leads to the markdown security unfortunately, still trying to find which part of the extensions code handles that.

To reset preview security settings you can head do `~/.config/Code/User` (or the MacOS equivalent if it's different) and remove all `*Storage` folders. With that done simply invoke the preview security selector via the aforementioned command.

**Comment by MatteoCampinoti94** [comment]
Hopefully I'll be able to fix the button, then we'll push a new version to the marketplace.

In the meantime @no-simpler you can build and install the extension manually if you need.

**Comment by no-simpler** [comment]
> Hopefully I'll be able to fix the button, then we'll push a new version to the marketplace.
> 
> In the meantime @no-simpler you can build and install the extension manually if you need.

I’ll make do with the workaround for now. Thank you for the extra-quick response.

**Comment by MatteoCampinoti94** [comment]
You're welcome :blush:

**Comment by matthewbegun** [comment]
Any idea how to get this working on Windows?

I am unable to locate the `*Storage` equivalent.

**Comment by matthewbegun** [comment]
NVM - found it. For reference they are at ` %appdata%/code/user `

**Comment by Nadano** [comment]
I'm still unable to render equations even with the workaround, any tips?

**Comment by danyill** [comment]
@no-simpler, @matthewbegun, @Nadano I think this is working fine now.

Although you have probably tried it, if it doesn't work immediately go to the option "Change Preview Security Settings" and select a less secure option (e.g. "Disable"). There should also be a hyperlink at the bottom of the preview window.

![image](https://user-images.githubusercontent.com/674783/74485048-bacf9180-4f1e-11ea-96e5-75baacfdbaf4.png)

After changing the security setting it may be a good idea to close and re-open the preview window (although if you change the content this won't be necessary).

![image](https://user-images.githubusercontent.com/674783/74485324-5fea6a00-4f1f-11ea-80f3-78d0ed09dc1a.png)

Can you confirm if this is a problem in the latest version of this extension? FWIW it's working for me on Linux and I'm pretty sure (not currently near a Windows machine) it's been working fine on Windows also.

**Comment by matthewbegun** [comment]
This is working now on VSCode 1.42 on Windows and WSL. 

Thanks!

**Comment by danyill** [comment]
Thanks for responding -- I'll close this for now.

Feel free to open another issue if you notice problems with this feature in the future.

**Comment by matklad** [comment]
Disabling security does not work for me sadly. Nothing happens, and I see the following in dev tools:

<details>

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'document' of undefined
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'document' of undefined	at /home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:57:36	at new Promise (<anonymous>)	at AsciidocParser.<anonymous> (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:55:20)	at Generator.next (<anonymous>)	at /home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:7:71	at new Promise (<anonymous>)	at __awaiter (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:3:12)	at AsciidocParser.convert_using_javascript (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:54:16)	at AsciidocParser.<anonymous> (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:241:29)	at Generator.next (<anonymous>)	at /home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:7:71	at new Promise (<anonymous>)	at __awaiter (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:3:12)	at AsciidocParser.parseText (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:238:16)	at AsciidocEngine.<anonymous> (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/asciidocEngine.js:52:36)	at Generator.next (<anonymous>)	at fulfilled (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/asciidocEngine.js:7:58)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at /home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:57
	at new Promise (<anonymous>)
	at AsciidocParser.<anonymous> (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:55)
	at Generator.next (<anonymous>)
	at /home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:7
	at new Promise (<anonymous>)
	at __awaiter (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:3)
	at AsciidocParser.convert_using_javascript (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:54)
	at AsciidocParser.<anonymous> (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:241)
	at Generator.next (<anonymous>)
	at /home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:7
	at new Promise (<anonymous>)
	at __awaiter (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:3)
	at AsciidocParser.parseText (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/text-parser.js:238)
	at AsciidocEngine.<anonymous> (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/asciidocEngine.js:52)
	at Generator.next (<anonymous>)
	at fulfilled (/home/matklad/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.15/out/src/asciidocEngine.js:7)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

</details>

Is there any reason for why this needs to be a custom button which (?) stores the state into global state? Would just using standard VS Code `settings.json` work better here?

**Comment by rasmusmk** [comment]
I do not know if something has changed but it does not on my windows pc

**Comment by Mogztter** [comment]
@matklad you are using an outdated version (2.7.15), could you please install the latest version 2.8.10 and try again?

**Comment by Mogztter** [comment]
(@matklad sorry I thought it was a new comment, never mind, you should have figured it out by now 😉)
