### ISSUE TITLE
Mojibake unstead of cyrillic

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor-vscode#175]
Hello.

vscode 1.32.3 on Windows 8
asciidoc v2.3.3

I **don't** use `asciidoctor.js`. I use Ruby version of Asciidoctor. But when I tried `asciidoctor.js`, all worked fine.

![image](https://user-images.githubusercontent.com/33900895/54949545-63b07f00-4f50-11e9-8655-701b507824a6.png)

I tried Chrome extensions. It works without any problems.

I tried in console `asciidoctor test.adoc` &mdash; all works fine too.

```
asciidoctor -v
Asciidoctor 2.0.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:IBM866 ex:IBM866)
```

-- Andrey.

**Comment by MatteoCampinoti94** [comment]
That probably happens because the font used by the preview does not have those symbols.

Could you post that text in Cyrillic here so that I can test it?

**Comment by sindzicat** [comment]
No problems!)

```
= Вывод уравнения упругой линии балки для шпиндельного узла
:nofooter:
:lq: pass:[&laquo;]
:rq: pass:[&raquo;]
:stem: latexmath


Hello
Привет
```

**Comment by sindzicat** [comment]
@MatteoCampinoti94, what font is used? I can check if it contains cyrillic symbols too.

**Comment by MatteoCampinoti94** [comment]
Works fine for me. I'm using the default preview font family on a Linux machine
![Screenshot from 2019-03-26 11-11-01](https://user-images.githubusercontent.com/5142004/54989020-f20c1b80-4fb7-11e9-9f43-1b296d124311.png)

This is the setting that controls the font used in the preview:
`"asciidoc.preview.fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', 'HelveticaNeue-Light', 'Ubuntu', 'Droid Sans', sans-serif",`
(It's identical to the default `editor.fontFamily` setting)

As with the `editor.fontFamily` setting, VSCode will use the first font it can find, regardless of how many symbols it can provide. Try removing fonts from the left hand side, at least one of them should support Cyrillic characters.
If nothing works, try installing a font manually, or selecting one that is already installed and that you know supports Cyrillic symbols.

**Comment by sindzicat** [comment]
Hm... This problem is only on my home computer. I will look at this moment this evening.

**Comment by MatteoCampinoti94** [comment]
Weird, but then again we are talking about Windows. If it were behaving like it should I'd be worried x3

Hopefully in the future VSCode will allow for OS-dependent default settings, it'd solve a lot of these little problems.

**Comment by sindzicat** [comment]
No, this isn't font. I tried Arial and 'Times New Roman' &mdash; just now work.

I downloaded zip archive of VS Code and used [these instructions](https://code.visualstudio.com/docs/editor/portable) to make it portable. Then I saw that new VS Code is really clean. I installed asciidoctor extension again, turn of `use asciidoctor.js` and got the same error:

![image](https://user-images.githubusercontent.com/33900895/55024627-4c38cb00-5010-11e9-994c-e7ea4709342f.png)

As for fonts, in clean version of VS Code I changed fonts to:

```
'Times New Roman', Arial, -apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', 'HelveticaNeue-Light', 'Ubuntu', 'Droid Sans', sans-serif
```
But this didn't helped me.

**Comment by sindzicat** [comment]
`{asciidoctor-version}` gives me 2.0.1.

**Comment by sindzicat** [comment]
When I use `use asciidoctor.js`, `{asciidoctor-version}` gives me 1.5.6.2.

**Comment by sindzicat** [comment]
Seems I found, what cause these problems. I just uninstall all Ruby versions of Asciidoctor, then installed Asciidoctor ver. 1.5.8. Now I have the following:

![image](https://user-images.githubusercontent.com/33900895/55025402-ecdbba80-5011-11e9-8b87-27309745bafa.png)

**Comment by sindzicat** [comment]
I just have been removed Asciidoctor 1.5.8 and installed Asciidoctor 2.0.1. I got my problem again:

![image](https://user-images.githubusercontent.com/33900895/55025617-55c33280-5012-11e9-80e1-bc354a569458.png)

This is definitelly problem of new version of Asciidoctor.

@mojavelinux, please, help! :sos:

**Comment by mojavelinux** [comment]
Asciidoctor is doing the right thing. If the document is a UTF-8 string, it uses it as is. If it is not, it encodes it as UTF-8. So it's likely the case that the file (or string) the extension is passing to Asciidoctor is not UTF-8. Asciidoctor no longer forces the encoding to UTF-8 (which is more correct).

**Comment by mojavelinux** [comment]
@sindzicat First, you can verify that VSCode is using the `asciidoctor` command and not Asciidoctor.js?

Having confirmed that, here's how the asciidoctor command is invoked:

```
adoc_cmd_args.push.apply(adoc_cmd_args, ['-q', '-o-', '-', '-B', '"' + documentPath + '"'])
var asciidoctor = spawn(adoc_cmd, adoc_cmd_args, options);
```

I can see what's probably happening. In this scenario, the extension is piping a UTF-8 string to the command, but Ruby is configured to use the IO encoding IBM866. That's why you get mojibake.

One solution to this problem is to pass the RUBY_OPTS environment variable to the spawn command so that the IO encoding Ruby uses is UTF-8. That will almost certainly fix the problem.

```
RUBY_OPTS: '-E UTF-8:UTF-8'
```

**Comment by mojavelinux** [comment]
The reason this happens in Asciidoctor 2.0 is because Asciidoctor now respects the encoding of the input string and reencodes it to UTF-8, which is the correct behavior. However, that means that when piping a string to Asciidoctor, Ruby's IO encoding must be UTF-8. That part is new.

**Comment by sindzicat** [comment]
> First, you can verify that VSCode is using the asciidoctor command and not Asciidoctor.js?

![image](https://user-images.githubusercontent.com/33900895/55060975-b8a0e200-5083-11e9-9be4-702bf7508d57.png)

> `RUBY_OPTS: '-E UTF-8:UTF-8'`

![image](https://user-images.githubusercontent.com/33900895/55061131-0a496c80-5084-11e9-9fea-87baa086559a.png)

> That will almost certainly fix the problem.

Sorry, this didn't fixed my problem((

**Comment by sindzicat** [comment]
Stop!

> That will almost certainly fix the problem.

Fixed!!! :+1: 

It seems for me I forgot to relauch VS Code after reinstalling Ruby and Asciidoctor.

Many thanks!!!)))

**Comment by mojavelinux** [comment]
Yeah!!

This is definitely something we need to document. I also think it will help if we can add the option directly to the asciidoctor command to deal with this.

Thanks for taking the time to debug with me!

**Comment by mojavelinux** [comment]
Though, I would say before we close this issue, I think the spawn command should pass the RUBYOPT environment variable. I'm testing it.

**Comment by mojavelinux** [comment]
I'll submit a PR.

**Comment by mojavelinux** [comment]
PR submitted and merged.

**Comment by sindzicat** [comment]
Cool! So fast)))

**Comment by mojavelinux** [comment]
We mean business ;)

**Comment by MatteoCampinoti94** [comment]
Thank you for solving the issue @mojavelinux!

Will merge the commit immediately.

**Comment by mojavelinux** [comment]
Glad to help out!
