### ISSUE TITLE
Publish version 2.5.1-1

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-vscode#185]
New version [2.5.1](https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.5.1)

Fixes:
* Fix contrained literal (\`) or closing single typographic quote (\`') bug when used inside typographic quotes (e.g. "\`busy \`'till tomorrow\`" would create a recursive match)

Changes:
* Change remaining Markdown-named variables/modules to AsciiDoc
* Improve automated building/install script
* Add syntax highlight for closing single typographic quote (\`')

**Comment by MatteoCampinoti94** [comment]
Do not publish yet, found a bug that is causing ALL syntax highlighting to fail.

**Comment by MatteoCampinoti94** [comment]
If it is what I think it is it should be easy and I'll tag a hotfix.

**Comment by MatteoCampinoti94** [comment]
Fixed it, version is now [2.5.1-1](https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.5.1-1)

Fixes:
* Fix an error from [2.5.1](https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.5.1-1) that caused all syntax highlighting to fail

**Comment by joaompinto** [comment]
This release will take some time. I am in Italy without laptop until wednesday

**Comment by MatteoCampinoti94** [comment]
No worries, I'm actually going to Italy too next week ^^

**Comment by joaompinto** [comment]
Published as 2.5.2, vscode does not handle -release in the version naming scheme. Thanks

**Comment by MatteoCampinoti94** [comment]
Got it :+1:
