### ISSUE TITLE
plantuml preview broken

### ISSUE THREAD

**Issue by forest-yang** [asciidoctor/asciidoctor-vscode#188]
I want to write plantuml diagram in asciidoc. when preview in vscode, it did not rendered correctly.

Environment:
OS: macOS 10.14.4
VSCode: 1.33.1
AsciiDoc extension: 2.5.2

my asciidoc snippet:

```
:plantuml-server-url: http://www.plantuml.com/plantuml
= My Design

[plantuml]
....
autonumber

title Initial
participant Alice
participant Tom

Alice -> Tom: hello
Tom -> Alice: hello response
....

```

**Comment by MatteoCampinoti94** [comment]
The address is incorrect, you need to use `https://www.plantuml.com/plantuml`. Not sure why it needs the secure option, but apparently it breaks the diagram in the preview.

**Comment by forest-yang** [comment]
Yes, work after change to https. thank you.
