### ISSUE TITLE
Publish version 2.7.1 (or 2.6.1)

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-vscode#189]
New version [2.6.0](https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.6.0)

Changes:
* Add `preview.attributes` option to set preview attributes in the user/workspace settings

**Comment by MatteoCampinoti94** [comment]
Completed #155

**Comment by MatteoCampinoti94** [comment]
I've also rewritten the readme from scratch. There is an Options section now with a list of the options the extension supports and expanded the How to Use to include preview style and export as PDF function. Also added a small Contributing section, just to be thorough.

For the first rewrite I used AsciiDoc only to realize VSCode marketplace needs a markdown file for the description x3

**Comment by MatteoCampinoti94** [comment]
New version [2.7.0]

Changes:
* Add `preview.style` option to set preview stylesheet in settings

**Comment by MatteoCampinoti94** [comment]
We could also release it as 2.6.0, removing the 2.7.0 tag and reassigning the 2.6.0 one. Didn't think I'd have had enough time to implement the `preview.style` option until this morning, so yesterday I tagged the 2.6.0 thinking it'd be a while before the next one.

**Comment by MatteoCampinoti94** [comment]
Also, the damn _How to Build and Install from Source (Linux and Mac)_ doesn't want to work in the VSCode extension details x3
It works fine here on GitHub (and even inside the VSCode editor and preview), but for some reason that one link doesn't work inside the extension view.

**Comment by MatteoCampinoti94** [comment]
New version [2.7.1](https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.7.1)

Fixes:
* Fix `preview.attributes` description

Also changed the _Build from Source_ section in the README and fixed the link.

**Comment by joaompinto** [comment]
Published joaompinto.asciidoctor-vscode@2.7.1, takes some minutes to appear in the vscode updates.
Thanks for all the hard work.

**Comment by MatteoCampinoti94** [comment]
:+1:
