### ISSUE TITLE
Rename extension vendor from joaompinto. to asciidoctor.

### ISSUE THREAD

**Issue by joaompinto** [asciidoctor/asciidoctor-vscode#193]
This might be a complex change but would better align the vendor id with the teamwork behind the extension.

Things to consider:

- [ ]

**Comment by MatteoCampinoti94** [comment]
That'd be great! :D

**Comment by MatteoCampinoti94** [comment]
Maybe we could set up an automated system

**Comment by MatteoCampinoti94** [comment]
To publish the extension you need to use `vsce` right? Can it be used passing all necessary info via arguments?

We might be able to set up a CI to do it for us, triggered by any commit tagged as `vX.Y.Z`. We'd need to be careful with it, but it'd make it easier.

**Comment by joaompinto** [comment]
Yes, we should be able to use vsce from a CI, the more complex part right now is to figure how to setup a shared vendor on MS :P

**Comment by MatteoCampinoti94** [comment]
*nod*

Can't we setup an organization on Azure The vendor is only identified with the name and access token, if the whole team has access to it then we can have a de facto shared vendor.

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops

**Comment by joaompinto** [comment]
Are you able to check https://dev.azure.com/asciidoctor/ ?

**Comment by MatteoCampinoti94** [comment]
Yep, joined :)

**Comment by MatteoCampinoti94** [comment]
Can't find an option to create an access token for the organization :(
But maybe that's because of my permission level?

**Comment by joaompinto** [comment]
Access Tokens are always personal, there is no option to create "organization" level tokens, so we need to create some personal token (within mine or your user) to use it from the CI. You have "stakeholder" privileges, which I hope is kind of admin.

I still do not understand how is the organization linked to the vendor id name and the extension publishing privileges.

**Comment by MatteoCampinoti94** [comment]
\*nod\* Created one, there was an organization setting but not 100% sure what it does (I've never used Azure before).

Stakeholder seems to be more like developer from what I can see, doesn't let me create projects or change some settings.

**Comment by MatteoCampinoti94** [comment]
These are the permission levels: https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azure-devops

**Comment by Mogztter** [comment]
@joaompinto this is done right? can we close this issue?

**Comment by joaompinto** [comment]
Yup, closing it now
