### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by jstafman** [asciidoctor/asciidoctor-vscode#194]
In the options table, the description for the first two rows has "Asciidcotor" instead of "Asciidoctor." The contribution instructions say not to edit the readme file, so I'm opening an issue instead.

**Comment by MatteoCampinoti94** [comment]
You can edit it yourself for these kind of things ^^

**Comment by MatteoCampinoti94** [comment]
The contributing section is still a wip, put that part about the readme as a precaution. Still need to update it with more detailed instructions.

**Comment by jstafman** [comment]
I would volunteer to update that section of the readme, except fixing this typo is literally going to be my first contribution ever, so I feel that someone with more experience should be drafting instructions about contributing.

**Comment by MatteoCampinoti94** [comment]
Dont worry, we'll update the contributing section ourselves :)

**Comment by MatteoCampinoti94** [comment]
If you spot anything else that needs fixing anywhere in the code though, feel free to do it, help is more than welcome ^.^

**Comment by MatteoCampinoti94** [comment]
Merged your changes, thanks for the corrections!
