### ISSUE TITLE
Getting "Pygments: uninitialized constant Pygments" 

### ISSUE THREAD

**Issue by WoojungHuh** [asciidoctor/asciidoctor-vscode#200]
Getting "Pygments: uninitialized constant Pygments" when trying to preview of adoc

## Description

With "Pygments: uninitialized constant Pygments" message, no preview screen.

## System Information
Windows VS Code 1.33.1 with AsciiDoc 2.7.3

## To Reproduce
Steps to reproduce the issue:

Preview of adoc with ":source-highlighter: pygments"

**Comment by MatteoCampinoti94** [comment]
It's because you need to have the [pygments.rb](https://rubygems.org/gems/pygments.rb) gem installed on your system. If you don't asciidoctor.js will throw an error and the preview will fail.

**Comment by MatteoCampinoti94** [comment]
Ok, nevermind my previous comment. The error is still there. It seems the first call to the preview works without problems, but when it needs to update it it doesn't work anymore and throws the error

**Comment by MatteoCampinoti94** [comment]
I need to investigate it a bit, still not sure it's caused by our extension.

**Comment by WoojungHuh** [comment]
Thx for looking into.

**Comment by MatteoCampinoti94** [comment]
No need :)

**Comment by MatteoCampinoti94** [comment]
I've looked into the asciidoctor.js issues and found this one [asciidoctor.js#95](https://github.com/asciidoctor/asciidoctor.js/issues/95) which seems to be caused by some problem with the asciidoctor processor itself.

Seems we can't do anything on our end to fix it :(

**Comment by MatteoCampinoti94** [comment]
What our extension does is take the AsciiDoc text and throw it at asciidoctor.js, nothing more. We don't even touch the conversion settings except to add the attribute for the editor style css.

**Comment by MatteoCampinoti94** [comment]
Sorry that we couldn't solve the problem :(

**Comment by WoojungHuh** [comment]
No problem. Appreciate your fast actions and feedback. 👍
