### ISSUE TITLE
Scroll sync seems broken (was working in earlier versions)

### ISSUE THREAD

**Issue by rocketraman** [asciidoctor/asciidoctor-vscode#201]
## Description

Using AsciiDoc plugin v2.7.3 with VS Code 1.34.0. Sometime recently, scroll syncing seems to be broken. I have verified the extension settings "Scroll Editor with Preview" and "Scroll Preview With Editor" are both checked.

## System Information

Fedora 29, VS Code 1.34.0

## To Reproduce

Steps to reproduce the issue:

1. Open an AsciiDoc file, and view the preview.
2. Click on some text in the source -- the preview does not scroll.
3. Click on some text in the preview -- the editor does not scroll.

## Additional Context

This used to work fine, but I don't know the version numbers when it worked.

**Comment by rocketraman** [comment]
I see this is a duplicate of https://github.com/asciidoctor/asciidoctor-vscode/issues/182, closing. By the way, as mentioned in that issue, version 2.3.3 solves the problem on my machine as well.

**Comment by MatteoCampinoti94** [comment]
Thanks for the report :)

Yeah we are aware that version 2.3.3 works correctly, I'm still investigating but I dont have a lot of free time atm so it might take a while. Sorry :(
