### ISSUE TITLE
Add config option to set the wkhtmltopdf binary path

### ISSUE THREAD

**Issue by DennisL68** [asciidoctor/asciidoctor-vscode#202]
## Can't install wkhtmltodoc manually if no access to internet
When AsciiDoc is installed using a vsix file in a protected environment, the download of wkhtmltopdf will fail with the error:
Error: Error instaling wkhtmltopdf, connect ETIMEDOUT (sic)
[IP]:443

Source: AsciiDoc (Extension)

## System Information
VSCode 1.33.0
OS: Windows_NT x64 6.1.7601
AsciiDoc 2.7.3

## To Reproduce

1. Disconnect connection to internet
2. Export any file as PDF

## Screenshots & Files

N/A

## Additional Context

Instructions about how to manually download and install wkhtmltopdf should be provided if internet connection isn't available.

**Comment by DennisL68** [comment]
I found out where to put the binary by hand.
But how do I configure VS Code to know about it?

**Comment by joaompinto** [comment]
VSCode looks for the file in a specific place, if is not working it means the file is in the wrong place :) 
In Linux the binary must be present at:

> 
$HOME/.vscode/extensions/joaompinto.asciidoctor-vscode-version/out/src/commands/wkhtmltopdf-linux-x64

**Comment by DennisL68** [comment]
Yes, I had a look at a computer that was online and had successfully downloaded and installed the binary.
But just putting the binary in place doesn't stop AsciiDoc from trying to download it anyhow.

There must be a setting or flag as well that is working it's dark magic.

**Comment by joaompinto** [comment]
Adding an option to manually set the binary path will address this better.

**Comment by MatteoCampinoti94** [comment]
We could add `asciidoc.wkhtmltopdf_path` to the configurations. Defaults to empty and when the Export to PDF command is launched it uses that path if not empty.

**Comment by MatteoCampinoti94** [comment]
Thanks for taking care of it @joaompinto :+1:

Am quite busy lately, not much time for side projects:(

**Comment by DennisL68** [comment]
Will the binaries of wkhtmltopdf, placed i default command dir, be migrated when asciidoc is updated?

**Comment by joaompinto** [comment]
You should place the binary in a regular static folder, the path set on the configuration will be preserved during extension upgrades.

**Comment by DennisL68** [comment]
Yes.
But if I don't set the path, binaries in default $HOME/.vscode/extensions/joaompinto.asciidoctor-vscode-version/out/src/commands is now correctly detected if already present when using 2.7.6.
