### ISSUE TITLE
Snippets not Working 

### ISSUE THREAD

**Issue by beckje01** [asciidoctor/asciidoctor-vscode#204]
## Description

Snippets  and all inellisense features not working while a doc is in asciidoctor mode.

## System Information

Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.1.1-2-MANJARO

## To Reproduce

Steps to reproduce the issue:

1. Open an Adoc Filer
2. type any snippet, global user or ones provided by the extension
3. Nothing will prompt. 

## Additional Context

Tested with major versions 2.3 through 2.7.4

Only error in the debugging console is the TypeError reported in #190

**Comment by MatteoCampinoti94** [comment]
They work perfectly on my machine. Are you sure you haven't changed the `editor.quickSuggestions` setting?

**Comment by beckje01** [comment]
I'll check they work in any setting but asciidoc for the language.

**Comment by beckje01** [comment]
The suggestions are set to the following for everything the best I can tell
```
	"editor.quickSuggestions": {
		"other": true,
		"comments": false,
		"strings": false
	}
```

**Comment by MatteoCampinoti94** [comment]
Those are the default settings yes. I have the same ones on my machine and the snippets work without problems.

Try adding this setting to your global settings.json and open a new folder:
```json
"[asciidoc]": {
    "editor.quickSuggestions": true
}
```

**Comment by beckje01** [comment]
That does fix it but I didn't have anything bout asciidoc in the file. But thanks this is great. If there is anything I should do to help with this further. Not sure if its worth doing more digging to see why its like that or if a note in the docs would be enough?

**Comment by MatteoCampinoti94** [comment]
Most likely it was just a settings conflict, no need to keep the issue open for that.

If you want though you can experiment with the `quickSuggestions` setting globally, locally and for the language to see if there is a specific combination that breaks snippets on your system :)

**Comment by radar** [comment]
Just a small followup to this one. I encountered this issue today too within VS Code. The above suggestion for:

```
"[asciidoc]": {
    "editor.quickSuggestions": true
}
```

Into `settings.json` fixed my issue. Thank you very much @MatteoCampinoti94!
