### ISSUE TITLE
Feature Request - Paste Image

### ISSUE THREAD

**Issue by stobias123** [asciidoctor/asciidoctor-vscode#208]
I love this plugin. It's fantastic. Would love to be able to paste images.

## Is your feature request related to a problem? Please describe

I hate that I have to switch contexts and place images appropriately in finder when I'm writing docs. Being able to paste and create appropriate adoc links would be fantastic

## Describe the solution you'd like

Paste creates a link, and uploads the image to `images/`

Seems its possible like this.
https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image

## Describe alternatives you've considered

https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image

I believe this is also possible in the atom asciidoc extensions.

**Comment by danyill** [comment]
@stobias123 You can do this now (actually for a while), using the Paste Image command so I'll close this issue.

![image](https://user-images.githubusercontent.com/674783/74484888-5c0a1800-4f1e-11ea-8e00-372a34ffa5b3.png)

Feel free to re-open if this doesn't address your concern.
