### ISSUE TITLE
Doesn't work with asciidoctorj

### ISSUE THREAD

**Issue by AlexTalker** [asciidoctor/asciidoctor-vscode#211]
## Description

As I do not want to install Ruby on my system and manage `AsciiDoctor` via `gem`,
I decided to utilize `chocolatey` package `asciidoctorj.exe` instead.
Also, I installed this add-on to ease writing in VSCode.
Unfortunately, `PlantUML` code were represented as plain text in preview while being rendered by `asciidoctorj.exe`. So I decided to specify it for usage by the add-on.

Unfortunately, I get this:
```
Exception in thread "main" Exception in thread "main" 

command: C:\ProgramData\chocolatey\bin\asciidoctorj.exe -a stylesdir=C:\Users\User\.vscode\extensions\joaompinto.asciidoctor-vscode-2.7.6\media@ -a stylesheet=asciidoctor-editor.css@ -q -o- - -B "c:\Users\User\Documents\asciidoctor"

If the asciidoctor binary is not in your PATH, you can set the full path.
Go to `File -> Preferences -> User settings` and adjust the asciidoc.asciidoctor_command
```

## System Information

```
Version: 1.36.0 (system setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```

## To Reproduce

Steps to reproduce the issue:

1. `choco install asciidoctorj`
2. Install this add-on in VS-Code
3. Override configuration for usage of `asciidoctorj`:
```
    "asciidoc.asciidoctor_command": "C:\\ProgramData\\chocolatey\\bin\\asciidoctorj.exe",
    "asciidoc.use_asciidoctor_js": false
```

## Screenshots & Files

![image](https://user-images.githubusercontent.com/3531127/60720602-f12e4280-9f33-11e9-963f-0b32d1fb7390.png)

![image](https://user-images.githubusercontent.com/3531127/60720664-20dd4a80-9f34-11e9-8cab-f42b8349f398.png)

## Additional Context

The problem seems to be `-o-` part of the generated command. I can't get why you need an extra `-`.

**Comment by nicerloop** [comment]
Explanation: -o- indicates to output to STDOUT, following - indicates input comming from STDIN. Neither is supported by asciidoctorj. Temporary files need to be used.

**Comment by anb0s** [comment]
Using with asciidoctorj distribution (windows and linux) shows:
`Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -o-`

**Comment by nicerloop** [comment]
> Explanation: -o- indicates to output to STDOUT, following - indicates input comming from STDIN. Neither is supported by asciidoctorj. Temporary files need to be used.

Correction: output to STDOUT is supported, but the command line parser used requires the option '-o' to be separated from the option value '-'.

The '-o-' parameter need to be split in two parts '-o' '-' to be compatible with current asciidoctorj implementation.

The STDIN input is currently not supported by the current parser, but as the parser is updated in asciidoctorj, the STDIN input could be reactivated https://github.com/asciidoctor/asciidoctorj/pull/864

**Comment by nicerloop** [comment]
asciidoctorj master now includes the necessary fixes to be used by asciidoctor-vscode in place of asciidoctor (see https://github.com/asciidoctor/asciidoctorj/pull/875), as long as asciidoctor-vscode has a cleaned-up use of '-o' option (see https://github.com/asciidoctor/asciidoctor-vscode/pull/232)

**Comment by anb0s** [comment]
@nicerloop i've just updated to v2.7.7 of this plugin with your PR #232 included and the AsciidoctorJ 2.1.0 reports now this:

`Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: - at com.beust.jcommander.JCommander.parseValues(JCommander.java:738) at com.beust.jcommander.JCommander.parse(JCommander.java:281) at com.beust.jcommander.JCommander.parse(JCommander.java:264) at com.beust.jcommander.JCommander.(JCommander.java:209) at org.asciidoctor.jruby.cli.AsciidoctorInvoker.invoke(AsciidoctorInvoker.java:31) at org.asciidoctor.jruby.cli.AsciidoctorInvoker.main(AsciidoctorInvoker.java:229)`

So we need new asciidoctorj release to use this cleaned-up use of '-o' in combination? Thanks!

**Comment by nicerloop** [comment]
Yes you need a recent version of asciidoctorj, https://github.com/asciidoctor/asciidoctorj/pull/875 was merged on 2019-11-19. You can clone and build it yourself if you want.

**Comment by anb0s** [comment]
I've just tried the released [asciidoctorj v2.2.0](http://dl.bintray.com/asciidoctor/maven/org/asciidoctor/asciidoctorj/2.2.0/) and see only this messages in preview:

```
WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/D:/Progs/asciidoctorj-2.2.0/lib/jruby-complete-9.2.9.0.jar) to method sun.nio.ch.NativeThread.signal(long) WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release WARNING: An illegal reflective access operation has occurred 

WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/D:/Progs/asciidoctorj-2.2.0/lib/jruby-complete-9.2.9.0.jar) to method sun.nio.ch.NativeThread.signal(long) WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release

command: d:\Progs\asciidoctorj-2.2.0\bin\asciidoctorj.bat -q -o - - -B "c:\Users\USER\dev\BHC"

If the asciidoctor binary is not in your PATH, you can set the full path.
Go to `File -> Preferences -> User settings` and adjust the asciidoc.asciidoctor_command

```
Do you know what can be missing?

**Comment by nicerloop** [comment]
> I've just tried the released [asciidoctorj v2.2.0](http://dl.bintray.com/asciidoctor/maven/org/asciidoctor/asciidoctorj/2.2.0/) and see only this messages in preview:
> 
> ```
> WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/D:/Progs/asciidoctorj-2.2.0/lib/jruby-complete-9.2.9.0.jar) to method sun.nio.ch.NativeThread.signal(long) WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release WARNING: An illegal reflective access operation has occurred 
> 
> WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/D:/Progs/asciidoctorj-2.2.0/lib/jruby-complete-9.2.9.0.jar) to method sun.nio.ch.NativeThread.signal(long) WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release
> 
> command: d:\Progs\asciidoctorj-2.2.0\bin\asciidoctorj.bat -q -o - - -B "c:\Users\USER\dev\BHC"
> 
> If the asciidoctor binary is not in your PATH, you can set the full path.
> Go to `File -> Preferences -> User settings` and adjust the asciidoc.asciidoctor_command
> ```
> 
> Do you know what can be missing?

Those warnings are triggered by JRuby on Java 9+. Try using Java 8 to run asciidoctorj.

**Comment by anb0s** [comment]
Thanks, now with JAVA_HOME set to JRE8 it works!

The messages are "just" warnings, i did not expected that it fails then in the vscode plugin...

**Comment by danyill** [comment]
I think we can close this as the issue appears to be resolved in the current version of the extension.

Feel free to re-open if your concerns have not been fully addressed.
