### ISSUE TITLE
Replace the existing plantuml support by kroki

### ISSUE THREAD

**Issue by pomdtr** [asciidoctor/asciidoctor-vscode#215]
kroki (a wrappper for many text to diagram languages, including plantuml) is already available as a plugin for asciidoctor.js :

https://kroki.io/
https://github.com/Mogztter/asciidoctor-kroki

It would be nice to be able to use it from the vscode preview.

**Comment by joaompinto** [comment]
Since the asciidoctor plugin uses the web service, we should provide as optional, disabled by default.
