### ISSUE TITLE
Does inline icons (like admonitions) work with asciidoctor-vscode?

### ISSUE THREAD

**Issue by tindlebaum** [asciidoctor/asciidoctor-vscode#217]
Admonitions and other inline icons (`icon: file`, for instance) are not rendered in the preview. Should I've installed an additional plug-in? Change any settings in VS Code/asciidoctor-vscode plug-in?

Thank you for your feedback.

**Comment by joaompinto** [comment]
You must add  the :icons: font attribute to your documents:
```adoc
= Document Title
:icons: font
```
You have more details about the icons configuration options at https://asciidoctor.org/docs/user-manual/#icons .

**Comment by tindlebaum** [comment]
Dear João, thank you for your feedback an link. It seems the `:icons: font` attribute must come right in the beginning of the file to work.

**Comment by joaompinto** [comment]
@tindlebaum you are welcome, there are several attributes that only take effect when defined in the document header:  https://asciidoctor.org/docs/user-manual/#setting-built-in-attributes .
