### ISSUE TITLE
Release vsix file in /releases/

### ISSUE THREAD

**Issue by nickboldt** [asciidoctor/asciidoctor-vscode#221]
As reported in https://github.com/eclipse/che/issues/14573 we're not supposed to link directly to marketplace.visualstudio.com anymore for vscode extensions used outside VS Code itself.

Yet the only URL I've found so far for joaompinto.asciidoctor-vscode-2.7.6.vsix is at https://marketplace.visualstudio.com/_apis/public/gallery/publishers/joaompinto/vsextensions/asciidoctor-vscode/2.7.6/vspackage 

## Describe the solution you'd like

Would it be possible to publish a copy of `joaompinto.asciidoctor-vscode-2.7.6.vsix` (and all future releases) into https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.7.6 ?

## Alternate option ...

Rebuild from tag: 

https://github.com/asciidoctor/asciidoctor-vscode/#manual

**Comment by ibuziuk** [comment]
@MatteoCampinoti94 @joaompinto maybe you can give a hand with this? would be great to have vsix for the latest + upcoming release

**Comment by joaompinto** [comment]
Added https://github.com/asciidoctor/asciidoctor-vscode/releases/download/v2.7.7/asciidoctor-vscode-2.7.7.vsix, I will need the issue open because we really need to be done automatically as part of the release process.

**Comment by nickboldt** [comment]
Thanks! Downstream project and product is happy for this change. :)

**Comment by Mogztter** [comment]
@joaompinto could you please describe what steps you've done to generate/upload vsix file?

**Comment by joaompinto** [comment]
@Mogztter , this is actually already done on the release workflow:
https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.8.9

Thanks for looking into the issues
