### ISSUE TITLE
editor crashes on bad formatting of quotes

### ISSUE THREAD

**Issue by ppiegaze** [asciidoctor/asciidoctor-vscode#225]
## Description

When AsciiDoc plugin is enabled, opening a file with a poorly formatted quoted string of the form described below causes a crash.
```
`'<23 or more chars>`'
```
### VSCode
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

### AsciiDoc Plugin
Version: 2.7.6

## To Reproduce

1. Create a file containing a string of the form 
```
`'<23 or more chars>`'
```
for example:
```
`'12345678901234567890123`'
```

2. Open the file in VSCode with AsciiDoc Plugin enabled. 

## More Info

If you start with a string of the same form (with the same mismatched quotes) but with fewer characters between the quotes it will not crash, but as you add additional characters you will see the reparse slow down each time. Once you get to 23 characters it seems to either crash or slow down so much that the "window not responding" modal pops up.

**Comment by danyill** [comment]
I can't reproduce this. Can you please confirm this is still an issue with the latest version of this extension?

**Comment by ppiegaze** [comment]
It looks like this is no longer an issue. I'll close it. Thanks
