### ISSUE TITLE
PlantUML  diagram with includes is not rendered

### ISSUE THREAD

**Issue by anb0s** [asciidoctor/asciidoctor-vscode#233]
## Is your feature request related to a problem? Please describe
If i'm using PlantUML diagrams with includes the includes are not loaded before sending to PlantUML server. Therefore server cannot generate the diagram, because include cannot be resolved.

```
[plantuml, Name, png]
....
!include puml/StyleClass.puml
box "Sync"
  participant Convertor
  participant Session
end box
....
```
![image](https://user-images.githubusercontent.com/95811/68482947-e3b6fb00-023a-11ea-8b19-588fd9abdf60.png)

## Describe the solution you'd like
The includes have to be resolved and included to temporary file that is sended then to server instead of original content.

## Describe alternatives you've considered
Use local planuml.jar if possible?

**Comment by DBuret** [comment]
the include syntax you are using is a plantuml syntax. that means that the ascidoctor engine will not understand it. So it sends it as-is to plantuml server.

if you want asciidoctor to process the include, you must use asciidoctor syntax:

`include::puml/StyleClass.puml`

Or you can ask the plantuml to use its syntax to fetch the file by itself, serving it throug http(s):
`include: https://raw.githubusercontent.com/user/repo/branch/path/file`
noet this will work only on publix repo (plantuml server will not be able to log into a private repo to read your file)

**Comment by anb0s** [comment]
@DBuret  Thanks! Yes i know all this. BUT: If the included PlantUML file also uses other includes e.g. for style etc. it will not work and i do not want to change the PlantUML files for AsciiDoc usage only.

In the `asciidoc` file:
`include::puml/Sync.puml`

In the `Sync.puml` file:
```
!include puml/StyleClass.puml
box "Sync"
  participant Convertor
  participant Session
end box
```

It would be good if some kind of "include processor" for PlantUML can be implemented, e.g. see the other plugin "https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml" that implements this (https://github.com/qjebbs/vscode-plantuml/issues/260). May be it can be used directly or done same way before sending the file to PlantUML server etc.

**I do not know if this should be done in the editor / plugin or in the "asciidoc-diagram" module of AsciiDoctor...**

_P.S.: The usage of the local plantuml server instead of plantuml.jar is preferable, because it is very fast and the only missing feature is the include support as it's good to have separated PlantUML files for styles, other digrams etc._

**Comment by danyill** [comment]
I think is an upstream issue and given that it's been filed upstream, can we close it here? 

It doesn't seem to have gained much traction yet however I don't think this extension can take on the role of implementing language features.

**Comment by anb0s** [comment]
Yes, it can be closed as we need new asciidoctor-plantuml.js with patched plantuml-encoder, but there is no answer from maintainer after long time :(

I think forked version of asciidoctor-plantuml.js + plantuml-encoder will not be accepted as dependency by this plugin?

We have lot of users working with plantuml server (as it's much faster then plantuml.jar) and preview is not working if AsciiDoc is used...

**Comment by gdw2** [comment]
Given the unresponsiveness of the maintainer, I think we should at least consider adopting the fork in the meantime.

**Comment by anb0s** [comment]
@gdw2 yes, i've created own version, but there are two problems:
- i've created a fork and created new [version](https://github.com/markushedvall/plantuml-encoder/issues/13) but it has an integration [issue](https://github.com/eshepelyuk/asciidoctor-plantuml.js/issues/53#issuecomment-580191713)
- in the meantime the maintainer reviewed the [PR](https://github.com/markushedvall/plantuml-encoder/pull/11) from the original fix and had minor comments, but the PR was closed by the original author and was not finished

I've no experience with JS and it would be good if somebody can help to rework the original patch. Please comment in the other projects two projects...

**Comment by anb0s** [comment]
As asciidoctor-plantuml is [no longer maintained](https://github.com/eshepelyuk/asciidoctor-plantuml.js) we are switching to [asciidoctor-kroki ](https://github.com/Mogztter/asciidoctor-kroki) and add [include support](https://github.com/Mogztter/asciidoctor-kroki/issues/49).
