### ISSUE TITLE
Chart (e.g. Vega, vegalite) support in preview

### ISSUE THREAD

**Issue by stenzengel** [asciidoctor/asciidoctor-vscode#242]
I would like to see the preview of a chart (e.g. a line chart with a date axis) in my asciidoc file. 

Asciidoctor Diagram (https://github.com/asciidoctor/asciidoctor-diagram) seems to support this for example via vega (https://vega.github.io/vega/) or vega-lite (https://vega.github.io/vega-lite).

I was not able to see a vega or vega-lite preview with asciidoctor-vscode. Is this feature already supported or do I have to wait for https://github.com/asciidoctor/asciidoctor-vscode/issues/215?

Further background information: I try to migrate from using Asciidoc FX which has a custom extension for charts (https://asciidocfx.com/#truejavafx-charts-extension) to VS Code with asciidoctor-vscode extension. But currently I'm blocked.

Any help greatly appreciated.

**Comment by pomdtr** [comment]
You should be able to preview it by switching to the ruby implementation.

Settings:
  "asciidoc.use_asciidoctor_js": false,
  "asciidoc.asciidoctor_command": "asciidoctor -r asciidoctor-diagram",

**Comment by stenzengel** [comment]
Thank you very much! 

Switching to ruby worked at least for plantuml. I'll test it with vega-lite this weekend. But that should work, too.

Nevertheless, kroki support should be helpful, since nothing has to be installed.

**Comment by waldyrious** [comment]
> Alternatively, kroki support should be easy to implement. I'll try to open a pull request when i'll have some time.

For future reference, that was done in #244.
