### ISSUE TITLE
ruby issue

### ISSUE THREAD

**Issue by dmbyte** [asciidoctor/asciidoctor-vscode#245]
VScode on MacOS Catalina
error:

/bin/sh: /usr/local/bin/asciidoctor-pdf: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

command: /usr/local/bin/asciidoctor-pdf -q - -B "/Users/byte/Documents/RA/ses-tuning-guide/ses-tuning-guide/adoc" -o "/Users/byte/Downloads/ses-tuning-guide.pdf"
If the asciidoctor-pdf binary is not in your PATH, you can set the full path.Go to `File -> Preferences -> User settings` and adjust the asciidoc.asciidoctorpdf_command

Ruby is version 2.6 now:
ls /System/Library/Frameworks/Ruby.framework/Versions/    
2.6	Current

How do we resolve this?

**Comment by danyill** [comment]
I suspect this is an environment issue with your machine. All this extension does is call either the command line specified in the user settings:

![image](https://user-images.githubusercontent.com/674783/72919169-db874a00-3dab-11ea-8ac1-b4cf8f254461.png)

Or if not specified, it simpy calls `asciidoctor-pdf`.

Possibly if you've installed Ruby 2.6 after previously installing the `asciidoctor-pdf` gem. RubyGems has hard-coded the installation path from the previous installation.

You could try removing and reinstalling the gem:

```bash
gem uninstall asciidoctor-pdf
gem install --pre asciidoctor-pdf
```

or

```bash
gem update --pre asciidoctor-pdf
```
Generally something like [rvm](http://rvm.io/rvm/install) should be used for managing Ruby these days which makes many of these kinds of problems go away...

**Comment by danyill** [comment]
Closing as this is most likely an environment problem and the OP has not responded. 

Feel free to reopen if I have misunderstood.
