### ISSUE TITLE
Preview is not working anymore with 2.7.9

### ISSUE THREAD

**Issue by TheTwoSven** [asciidoctor/asciidoctor-vscode#262]
With 2.7.8 everything woks fine. After update to 2.7.9 the Preview stays blank or "An error occurred while restoring view:asciidoc.preview".

I tried to uninstall and reinstall version 2.7.9 but without success. After "Install Another Version..." -> 2.7.8 the preview is loading again.

OS: Windows 10

**Visual Studio Code Version**
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by TheTwoSven** [comment]
duplicate to #261?

**Comment by joaompinto** [comment]
I have added your system config to  #261 , will follow-up there.
