### ISSUE TITLE
HTML generation does not work, due to wrong path

### ISSUE THREAD

**Issue by Linuspogo** [asciidoctor/asciidoctor-vscode#269]
## Description

When trying to use the HTML generation, a wrong path is given (the hard drive is added twice at the beginning), therefore the generation fails.

## System Information

Extension version 2.7.12
Asciidoctor version 1.5.6.1

## To Reproduce

1. Open .adoc file
2. Try to export as HTML

## Screenshots & Files

![image](https://user-images.githubusercontent.com/10514098/74510734-aa122200-4f04-11ea-978f-d555696351f6.png)

## Note

Might this also be due to a wrong configuration..?

**Comment by joaompinto** [comment]
I can reproduce the issue on Windows.

**Comment by joaompinto** [comment]
P.S.: Thanks for reporting it :)

**Comment by joaompinto** [comment]
Added some debugging to understand the issue:
```
        console.log("docPath.root", docPath.root)
        console.log("docPath.dir", docPath.dir)
        console.log("docPath.name", docPath.name)
```
```
docPath.root /
saveHTML.js:30
docPath.dir /home/joaompinto/Projects/asciidoctor-vscode/test/samples
saveHTML.js:31
docPath.name full
```
it seems that .dir already includes the root.

**Comment by danyill** [comment]
Thanks for the tidy up and Windows fixes @joaompinto
