### ISSUE TITLE
Easy configuration of diagram servers

### ISSUE THREAD

**Issue by Kinokin** [asciidoctor/asciidoctor-vscode#272]
Current settings screen doesn't provide easy way to configure url for plantuml and kroki servers

Suggestion:
For every diagram server have three settings
- enable
- use public server
- custom server url

**Comment by anb0s** [comment]
Similar question: How kroki can be used?

I've just found the setting ""asciidoc.use_kroki": true", but if i disable the "plantuml-server-url" then diagrams are not rendered.

**Comment by anb0s** [comment]
see #277

**Comment by danyill** [comment]
@anb0s you can set the diagram servers using the attribute which is provided for each.

For asciidoctor-kroki, in the document header set the appropriate attribute, something like this:

```asciidoc
:kroki-server-url: https://kroki.io
```

For asciidoctor-plantuml to set a specific server, use something like the following in the document header:

```asciidoc
:plantuml-server-url: http://www.plantuml.com/plantuml
```

For more configuration options, see the [extension readme](https://github.com/eshepelyuk/asciidoctor-plantuml.js#configuration).

I think we should document these more clearly in this extension's Readme but also that these configuration options are sufficiently simple that it does not warrant an additional configuration option. Additionally user's might want to vary options between documents which is why setting these options as per-document attributes seems to me to be the right idea.

So @Kinokin I'm a little resistant to adding an additional configuration option for this but I'm happy to update the Readme. I don't want to provide configuration options which avoid the need to learn the "normal use" of Asciidoctor extensions or their configuration because I think this goes against the intent of Asciidoc (we're avoiding the heavy GUI world, so creating a new GUI within vscode for this extension doesn't seem like the right idea to me).

@anb0s if you can't get asciidoctor-kroki to work, please provide a minimal document with the problem and we can take a look at it. Perhaps a good test document would be the one shown in the [Readme](https://github.com/Mogztter/asciidoctor-kroki/blob/master/README.md#usage). This should produce something like:

![image](https://user-images.githubusercontent.com/674783/76741356-4c5b4900-67d4-11ea-833b-152a4e133fc1.png)

**Comment by Kinokin** [comment]
Adding the attributes is not an option to me. The server setup is a local setting of a user and shouldn't be part of the document.

What may work is an user defined attribute file defining the local setup.

**Comment by anb0s** [comment]
@danyill thank you i will try this attribute in the document, but i think (like @Kinokin ) this should be configured in VSCode as setting like it's done for PlantUML server and then passed to asciidoctor.js as attribute parameter `-a kroki-server-url=http::/localhost:8000`...

**Comment by anb0s** [comment]
I've played with document attrubute `:kroki-server-url: http://localhost:8000` and it works with own server now! 

E.g. for reading the PlantUML version:
```
Version
[plantuml, "{plantUMLDir}diagram-version", svg]
....
@startuml
checkversion
@enduml
....
```
![image](https://user-images.githubusercontent.com/95811/76794692-d9e46c00-67c7-11ea-851d-b2140d886af6.png)

Today it also works with uncommented line `//:kroki-server-url: http://localhost:8000` or using `:kroki-server-url: https://kroki.io`.

It returns now newer version of PlantUML --> it looks like kroki.io was updated :) :

![image](https://user-images.githubusercontent.com/95811/76794794-1b751700-67c8-11ea-930d-b15903d570b9.png)

( I'm sure it did not worked two days before ;) )

@Kinokin it does not matter if the VSCode setting `"asciidoc.use_asciidoctor_js": ` is `true` or `false`. Is it intended?

@danyill I can play now with kroki, but need a possiblity to define the kroki server in VSCode settings like for PlantUML server:
```
    "asciidoc.preview.attributes": {
        "plantuml-server-url": "http://localhost:8080"
        "kroki-server-url": "http://localhost:8000"
    },
```
or new possiblity to add / append attributes to asciidoc.js command line.

**Comment by anb0s** [comment]
@Kinokin / @danyill we need a possiblity to define the kroki server in VSCode settings like done for PlantUML server:

    "asciidoc.preview.attributes": {
        "plantuml-server-url": "http://localhost:8080"
        "kroki-server-url": "http://localhost:8000"
    },

or new option to add attributes to asciidoc.js command line.

I'm new to vs-code plugin development and want to ask if you plan do add this? Thanks!

**Comment by anb0s** [comment]
I've now played with different setups and it looks like all the attributes defined in `asciidoc.preview.attributes` in `settings.json` are already passed to asciidoctor.js! The `kroki-server-url` is working as expected :
```
"asciidoc.preview.attributes": {
    "plantuml-server-url": "http://localhost:8080"
    "kroki-server-url": "http://localhost:8000"
}
```
no need to define it in all documents!

**For me it's enough if it is documented and no need for UI...**

P.S.: new investigation: if `kroki-server-url` is not provided (no attribute passed and not defined in document) it uses `https://kroki.io` as fallback and without i-net access it's not woking, should be documented too...

**Comment by mirogta** [comment]
Is there any way to disable the fallback to `https://kroki.io`?

We may have some potentially sensitive diagrams with Intellectual Property content that we'd rather not share with a 3rd party (kroki.io).

Also how can I tell if the fallback is happening? I can't find any logs or anything, which would tell me if my own kroki server works (it does in a browser/curl) when I try to use it from within VSCode Preview or if it falls back to `kroki.io`. Thanks

**Comment by anb0s** [comment]
@mirogta I think this should be addressed in [asciidoctor-kroki](https://github.com/Mogztter/asciidoctor-kroki) so create an issue [there](https://github.com/Mogztter/asciidoctor-kroki/issues).

**Comment by mirogta** [comment]
> @mirogta I think this should be addressed in [asciidoctor-kroki](https://github.com/Mogztter/asciidoctor-kroki) so create an issue [there](https://github.com/Mogztter/asciidoctor-kroki/issues).

Good point - raised as https://github.com/Mogztter/asciidoctor-kroki/issues/70

**Comment by danyill** [comment]
@mirogta @Kinokin 

You can also set `kroki-server-url` in the preview attributes of the extension. In this case it is set via the API and [cannot be overriden](https://asciidoctor.org/docs/user-manual/#setting-attributes-on-a-document) without changing the User Settings (which presumably can be centrally managed in a corporate environment or if there are concerns about sensitive information).

![image](https://user-images.githubusercontent.com/674783/81638131-46988180-946c-11ea-9cbf-e0d596ecad5f.png)

This has to be set as JSON so in my `settings.json` I have an entry like:

```json
"asciidoc.preview.attributes": {
      "kroki-server-url": "stayAwayFromKrokiIO"
    },
```

If this isn't sufficient then the standard corporate answer would be the firewall...

**Comment by mirogta** [comment]
@danyill thanks, that's useful.

We've added kroki.io into our firewall's whitelist, so that people can read about it and try the examples. But that means we can't use firewall to prevent leaking information.

I think it's unfortunate that the documentation and examples are on the same domain (https://kroki.io) as the API server. There is the https://docs.kroki.io/kroki/ documentation but it doesn't have the examples.

Perhaps the examples could be moved to the documentation - raised as https://github.com/yuzutech/kroki/issues/222

**Comment by sturtison** [comment]
Thanks all - Kroki makes it so much easier to access the diagrams.

While configuring it as covered above works, it makes it too easy for some people to not worry about the security, and hard enough for some to turn a blind eye to the security risk. Blocking kroki.io is not an option.

How can it be made easier to set these attributes - from the extension settings for example?

**Comment by lidaling** [comment]
My investigation is :

` :kroki-server-url:http://localhost:8000` mark in adoc file header works ,but 

```
    "asciidoc.preview.attributes": {
        "kroki-server-url": "http://localhost:8000",
    },
    "asciidoc.use_kroki": true,
```
does not work.
Any idea for this?please

**Comment by Mogztter** [comment]
It does work on my end. Did you refresh the preview?

**Comment by lidaling** [comment]
> Which version are you using? Could you please try with the latest beta version 3.x?

versioned 3.0.1 is one pre-release .
It does not work.setting.json as bellow:
```
   "asciidoc.extensions.enableKroki": true,
    "asciidoc.preview.asciidoctorAttributes": {
        "kroki-server-url": "http://localhost:8000",
    },
```
And more ,it seems header mark `:kroki-server-url: http://localhost:8000` does not work too!

**Comment by lidaling** [comment]
> Which version are you using? Could you please try with the latest beta version 3.x?

I start the kroki server with command                                                                                                                                                                                                                        `java  -jar kroki-server-v0.17.2.jar `
`

**Comment by Mogztter** [comment]
@lidaling Did you "Change Preview Security Settings" to enable loading content from http? Could you please share a screenshot as follows:

#### Version 2.9.6

![image](https://user-images.githubusercontent.com/333276/188268199-ace75135-1b70-472e-8359-81c9b5e9c501.png)

#### Version 3.0.1

![image](https://user-images.githubusercontent.com/333276/188268244-4e915c70-5d18-45ca-a57e-470db912a0ea.png)


Also, please join the community chat https://asciidoctor.zulipchat.com/ to continue this discussion as we don't use the issue tracker as a support forum.

**Comment by lidaling** [comment]
> @lidaling Did you "Change Preview Security Settings" to enable loading content from http? Could you please share a screenshot as follows:
> 
> #### Version 2.9.6
> ![image](https://user-images.githubusercontent.com/333276/188268199-ace75135-1b70-472e-8359-81c9b5e9c501.png)
> 
> #### Version 3.0.1
> ![image](https://user-images.githubusercontent.com/333276/188268244-4e915c70-5d18-45ca-a57e-470db912a0ea.png)
> 
> Also, please join the community chat https://asciidoctor.zulipchat.com/ to continue this discussion as we don't use the issue tracker as a support forum.

It was the key reason . I forgot to enable http content again after switch to 3.x version.
It works now .

**Comment by Mogztter** [comment]
Let's continue the discussion #480

**Comment by Bedzior** [comment]
In case someone's still wondering how to enable this for Asciidoc: the action is now called `AsciiDoc: Manage Preview Security Settings` and is only visible when the command palette is activated whilst in the preview.
