### ISSUE TITLE
digrams are not rendered if "asciidoc.use_kroki": true is activated

### ISSUE THREAD

**Issue by anb0s** [asciidoctor/asciidoctor-vscode#277]
## Description

Instead of asciidoctor-diagram with PlantUML server i want to try out kroki server.

I've spended some hours to find out how it can be configured and found only this documented setting : `"asciidoc.use_kroki": true`

After enabling this, still the diagrams are rendered with PlantUML server (running @ localhost).
I think because the setting is still there, the asciidoctor-diagram is used in asciidoctor.js:
```
"asciidoc.preview.attributes": {
        "plantuml-server-url": "http://localhost:8000"
    },
```

I this setting is removed diagrams are not rendered.

I've setup kroki server via docker and can see the kroki page at http://localhost:8000.

**How can i use this server for rendering?**

## System Information

Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

## Plugins
AsciiDoc 2.7.13

**Comment by danyill** [comment]
I've replied in #272, you should be able to use the parameter for the server URL to connect to the docker container.

**Comment by anb0s** [comment]
Close this one as kroki works, but not sure how `"asciidoc.use_kroki": true` affects the behaviour, continue discussion in #272
