### ISSUE TITLE
Descriptions on "Feature Contributions" tab are placeholders

### ISSUE THREAD

**Issue by zanedp** [asciidoctor/asciidoctor-vscode#278]
## Description

When looking at the `Feature Contributions` for AsciiDoc 2.7.13, all of the `Descriptions` are placeholders.

I would expect actual explanatory text, instead.

## System Information

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.16299

## To Reproduce

Steps to reproduce the issue:

1. Go to the Extensions browser (Ctrl+Shift+X).
2. Type "asciidoc", and click the one by João Pinto.
3. Click "Feature Contributions"
4. Notice placeholder text in the "Description" column rather than actual descriptions.

## Screenshots

![image](https://user-images.githubusercontent.com/295055/77012565-8ea39800-6944-11ea-8020-3539a5885201.png)

**Comment by danyill** [comment]
Yip, that's true. Thanks for reporting.

Actually the description is a reference which is taken from elsewhere. I'll see what we can do about that.
