### ISSUE TITLE
How to display math formulas in preview?

### ISSUE THREAD

**Issue by prudhomm** [asciidoctor/asciidoctor-vscode#279]
## Description

cmd+shift+v yields preview of an asciidoc file however the math are not displayed, they are still in latex

## System Information

```
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0
```
I am using extension 2.7.3

## To Reproduce

preview a adoc file

**Comment by danyill** [comment]
@prudhomm assuming you have set `stem` in your document header, you likely need to change the `Asciidoc: Change Preview Security Settings` to allow the remote content to load. I usually set it to `Disable` because I trust the Asciidoctor processor which then allows the javascript from the Mathjax CDN to load and display formulas.

**Comment by prudhomm** [comment]
Super thanks. Will check asap

**Comment by prudhomm** [comment]
it works fine thanks!

<img width="1108" alt="Screenshot 2020-03-21 08 18 54" src="https://user-images.githubusercontent.com/151693/77221736-bebd8780-6b4c-11ea-9751-2181df928b5e.png">

**Comment by blueray453** [comment]
I am trying to print square root of N.

I have selected `Asciidoc: Change Preview Security Settings > Allow Insecure Contents`

My Document Looks Like

```
= Test Math
:stem:

stem:[sqrt(N)]
```

The preview looks like ` \$sqrt(N)\$`.

What am I doing wrong?

**Comment by rasmusmk** [comment]
Why is disable needed?
Does go to external ip for formating?

**Comment by Mogztter** [comment]
We are loading MathJax from https://cdnjs.com/libraries/mathjax and CDN are not trusted
The [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) we are using are probably too strict but in the meantime, you will need to disable CSP to use MathJax.

If you have additional questions, please use the community chat at https://asciidoctor.zulipchat.com/

**Comment by SjoerdV** [comment]
I think this issue should be re-opened as disabling all security measures to get the preview to work seems like a rather excessive compromise. So can we get *secure* `latexmath` and `:stem:` processing back on the agenda?

**Comment by ggrossetie** [comment]
@SjoerdV That's no longer true, MathJax is now embed in the VS code extension. You should not need to disable security with 3.x

**Comment by SjoerdV** [comment]
@ggrossetie that is weird, is there a setting I should switch on, perhaps? using v3.1.3

![2023-08-13-001](https://github.com/asciidoctor/asciidoctor-vscode/assets/13275320/a7c3727f-b68a-4948-bca8-9be267ee5f81)

**Comment by ggrossetie** [comment]
Did you enable STEM using the `:stem:` attribute?

**Comment by SjoerdV** [comment]
> Did you enable STEM using the `:stem:` attribute?

Yes I did, this setting is in a 'included' file.

**Comment by rasmusmk** [comment]
Hi

For me it also do not work.



Den søn. 13. aug. 2023 kl. 23.40 skrev SjoerdV ***@***.***>:

**Comment by ggrossetie** [comment]
I've opened https://github.com/asciidoctor/asciidoctor-vscode/issues/779 to address this issue.

**Comment by SjoerdV** [comment]
@ggrossetie just for my understanding: does this issue stem from loading a resource from the internet? If this is the case, wouldn't it be both safer (preventing CSP relaxation or script-src-elem spoofing) AND more resilient (offline use is still a thing for me) if these dependencies (lie MathJax) were 
* bundled with the extension OR
* downloaded on demand (ie. some peeps will never use math syntax) OR 
* maybe the best option: have a separate companion extension with a tested and supported version for asciidoctor-vscode (ie. asciidoctor.asciidoctor-vscode-mathjax)?

**Comment by ggrossetie** [comment]
>  just for my understanding: does this issue stem from loading a resource from the internet

No, MathJax is bundled with the extension. VS code is loading resources inside an extension using `https://file+.vscode-resource.vscode-cdn.net/` protocol.

**Comment by siddjain** [comment]
It does not work for me.

```
Version: 1.91.0 (Universal)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 22.6.0
```

```
:doctype: article
:stem: latexmath

[latexmath]
++++
\begin{equation}
ds^s = (c dt)^2 - (dx)^2 - (dy)^2 - (dz)^2 = (c dt')^2 - (dx')^2 - (dy')^2 - (dz')^2 
\end{equation}
++++
```

renders as:

<img width="697" alt="image" src="https://github.com/user-attachments/assets/fb44364a-4196-4b29-9992-19b79d17b20d">

I have disabled security settings:

<img width="621" alt="image" src="https://github.com/user-attachments/assets/9d4a66b6-1741-4320-8b3a-e90b420b8c19">

Is there some plugin I need to install? I have installed v3.3.1 of this extension

**Comment by siddjain** [comment]
I fixed it. I my case I had this header in my file:

```
---
layout: mathjax-post
title:  "xxx"
date:   2024-07-11 00:00:00 -0800
categories: xxx
description: xxx
---
```

removing the header fixed the problem.
