### ISSUE TITLE
Conditional env for vscode in asciidoc: how to detect we are in vscode preview

### ISSUE THREAD

**Issue by prudhomm** [asciidoctor/asciidoctor-vscode#280]
I am writing pages in asciidoc for an Antora website.

I wish to visualise the images in preview. The images are not in the same directory as the adoc file

## Is your feature request related to a problem? Please describe

How do I detect that I am in vscode (preview) to display images ?
```
:imageprefix: 
ifdef::env-github,env-browser[:imageprefix: ../../assets/images/]
```

work fine at top of doc in github.

## Describe the solution you'd like
would it be possible to have something like
```
:imageprefix: 
ifdef::env-github,env-browser,env-vscode[:imageprefix: ../../assets/images/]
```

or maybe there exists already an `env-` that catches that we are in vscode preview?
I would have expected `env-browser` to work.

**Comment by prudhomm** [comment]
here is an example of an adoc file in an antora framework:
I can see the images in github
https://github.com/feelpp/toolbox/tree/master/examples/modules/cfd/pages/laminar_isothermal_backward_facing_step
as well as in the browser thanks to the asciidoctor.js browser extension
https://raw.githubusercontent.com/feelpp/toolbox/master/examples/modules/cfd/pages/laminar_isothermal_backward_facing_step/README.adoc

**Comment by danyill** [comment]
Thanks for logging this issue @prudhomm, I think we could set an attribute in vscode to detect this -- something like `env-vscode` or similar. Happy to take a PR, although I hope to deal with some of these easier issues quite soon.

**Comment by prudhomm** [comment]
@joaompinto @danyill  thanks a lot! any ETR for this feature?

**Comment by joaompinto** [comment]
@prudhomm 2.7.15 was published now, containing this improvement.

Thanks

**Comment by prudhomm** [comment]
Thanks a lot

**Comment by prudhomm** [comment]
@danyill @joaompinto it works very well.
for the record, here is what +I did:

top of the document, `/` at the end
```
ifdef::env-github,env-browser,env-vscode[:imagesprefix: ../../images/]
```

where I add an image, no `/` at the end
```
image::{imagesprefix}myimage.png[]
```
