### ISSUE TITLE
Feature Request: Show Warnings / Logger / Problems / Diagnostics

### ISSUE THREAD

**Issue by larshp** [asciidoctor/asciidoctor-vscode#287]
When building a document on command line, it sometime shows:

`asciidoctor: WARNING: foobar.adoc: line 41: section title out of sequence: expected level 2, got level 3`

for malformed documents like

```asciidoc
= Foo
=== Bar
````

I guess these warnings can be retrieved via
https://asciidoctor-docs.netlify.com/asciidoctor.js/processor/logging-api/

And shown in vscode as Problems / Diagnostics
https://code.visualstudio.com/api/references/vscode-api#Diagnostic

**Comment by danyill** [comment]
Great idea, we should definitely do this. Happy to take a PR if you are able to help.
