### ISSUE TITLE
Content followed by a Header with no new line prints content in the header in preview mode

### ISSUE THREAD

**Issue by vairamsvsjdo** [asciidoctor/asciidoctor-vscode#293]
Content followed by a Header with no new line prints content in the header in preview mode

## Description

Content followed by a Header with no new line prints content in the header in preview mode

## System Information

Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041## To Reproduce

Steps to reproduce the issue:

1. Enable the extension
2.2.  [Added markdown in file](https://github.com/JayDevOps/testmd/blob/master/testgit.asc)
```markdown
=== Recording Changes to the Repository
Normal Content
```
3. Ctrl+Shift+V To Preview in markdown, it does not respect heading.
4. [Whereas github is able to display content correctly]
(https://github.com/JayDevOps/testmd/blob/master/testgit.asc)

## Screenshots & Files

See links provided

**Comment by danyill** [comment]
Hi @vairamsvsjdo thanks for reporting.

Unfortunately, I can't see a problem with this -- here's a screenshot:

![image](https://user-images.githubusercontent.com/674783/81639372-dab81800-946f-11ea-9286-131bf00e8687.png)

The heading also appears in the outline view correctly and appears to match the appearance of the file you've linked to in Github.

Can you confirm if this is still a problem for you? One thought is that possibly you have other extensions which provide a preview with the same shortcut keys?

**Comment by Mogztter** [comment]
@vairamsvsjdo Closing, feel free to reopen with additional information
