### ISSUE TITLE
Update asciidoctor-kroki

### ISSUE THREAD

**Issue by cgoguyer** [asciidoctor/asciidoctor-vscode#301]
## Description

Some diagrams have been added in asciidoctor-kroki: packetdiag, rackdiag, vega, vegalite and wavedrom
So could you update dependencies to the latest release of asciidoctor-kroki => 0.8.2.

## System Information
Currently asciidoctor-kroki 0.6.0 is implemented.

**Comment by danyill** [comment]
Thanks for this -- I'm quite keen on this myself. I've noticed a small issue with the  `kroki-fetch-diagram` parameter and will try to get this integrated upstream but I don't think that's a reason not to integrate the latest version (but it will behave strangely if `imagesoutdir`, `outdir`, `to_dir` or `base_dir` are not set).

**Comment by anb0s** [comment]
@danyill i've also faced issues with `:kroki-fetch-diagram: true`. I do not see the images in the configured `imagedir `folder like it's done by `asciidoc-diagram`.

**Comment by danyill** [comment]
Yup, you're right, see
https://github.com/Mogztter/asciidoctor-kroki/issues/62
