### ISSUE TITLE
Support ":source-language:" header attribute for code highlighting

### ISSUE THREAD

**Issue by pgeorgi** [asciidoctor/asciidoctor-vscode#303]
By stating :source-language: in the document header, it's not necessary to repeat the language for every code block (although a code block can override it). The extension doesn't seem to parse it and so code blocks remain unhandled by vscode.

**Comment by danyill** [comment]
Thanks for filing this issue @pgeorgi 

If you run the command "Change Asciidoc Preview Settings" and set to "Disable" I believe the `highlightjs` source-highlighter will function correctly. Otherwise retrieving the `highlightjs` code highlighter remotely will be disallowed.

Here's an example document which is working for me:

```asciidoc
= just a test
:source-highlighter: highlightjs
:source-language: java
:doctype: book

[source]
----
public void setAttributes(Attributes attributes) {
    this.options.put(ATTRIBUTES, attributes.map());
}
----

You can override the global source language by specifying a source language on the block.

[source,ruby]
require 'sinatra'


[source]
----
// I really do Java so I'm not sure what to write here
public void setAttributes(Attributes attributes) {
    this.options.put(ATTRIBUTES, attributes.map());
}
----

Blah blah blah
blah blah blah
```

Does this work for you?

**Comment by danyill** [comment]
Here's what I see when I run this with Preview settings set to Disable:

![image](https://user-images.githubusercontent.com/674783/81490664-166ca980-92d9-11ea-9b51-e3de146ad8e0.png)

**Comment by pgeorgi** [comment]
Disabling the security settings and changing to highlightjs (over pygments that I use for rendering) works with the java language formatter. Not with "ada" (nothing happens with that), but that's issue #19 

I suppose the situation could be streamlined (e.g. vendoring in highlightjs and overriding the source-highlighter to work in the preview), but not sure that's part of this issue.

Thank you!

**Comment by danyill** [comment]
Hey @pgeorgi thanks for the response.

Pygments is not compatible with asciidoctor.js. Ruby shells out to it and it requires Python (2! [apparently](https://asciidoctor.org/docs/user-manual/#pygments)). If you use the Asciidoctor command line you can get that to work if it is installed locally.

**Comment by pgeorgi** [comment]
I guess the other thing I was thinking of was to have code snippets in the source view highlighted by vscode. Not sure how much is involved to make that work, but apparently other document formats support that, see https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example which allows passing code blocks to syntax highlighters in the markdown highlighter.

**Comment by pgeorgi** [comment]
Ah, and even that works (tried with typescript), just not for ada.
