### ISSUE TITLE
Remove asciidoctor-plantuml

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#308]
asciidoctor-plantuml is [no longer maintained](https://github.com/eshepelyuk/asciidoctor-plantuml.js
).

Fortunately thanks to a recent contribution we already have the recommended alternative which is using [asciidoctor-kroki](https://github.com/Mogztter/asciidoctor-kroki).

It will simplify this extension and provide a better experience to use only asciidoctor-kroki in my view. Asciidoctor-kroki also provides a free public instance.

@joaompinto Any thoughts? Any objections to me submitting a PR for this?

**Comment by joaompinto** [comment]
Looks good to me.
