### ISSUE TITLE
Admonitions, callouts and syntax highlighting not rendered in preview

### ISSUE THREAD

**Issue by knzudgt** [asciidoctor/asciidoctor-vscode#315]
## Description

I just installed the extension and tried to write few lines.
The extension does not render admonitions, callouts and syntax highlighting in code blocks.

## System Information

VSCode Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic

OS: Ubuntu 18.04 LTS

AsciiDoc version: 2.7.15

## To Reproduce

Steps to reproduce the issue:
Write the following lines in the editor. The preview dos not render admonitions, callouts and syntax highlighting. See attached screenshot. 

```
= Heading Level 1
This is a short presentation on AsciiDoc's core capabilities.

Preview as you type, including formatting like *this* or _this_

It automatically preview as you type

WARNING: You need to install AsciiDoc

[source,ruby]
----
require 'asciidoctor'  # <1>
puts Asciidoctor.convert_file 'mysample.adoc'  # <2>
----
```

## Screenshots & Files

![Screenshot from 2020-05-13 15-47-49](https://user-images.githubusercontent.com/15718033/81822052-ec162880-9532-11ea-83bd-49796c46ae16.png)

**Comment by knzudgt** [comment]
I was able to render admonitions adding `:icons: font` at the beginning of the document.
Still code syntax highlighting does not work:

![Screenshot from 2020-05-14 11-26-51](https://user-images.githubusercontent.com/15718033/81917803-f2a9ac00-95d5-11ea-8b10-5423d95c4d67.png)

**Comment by danyill** [comment]
You can't use pygments with the default asciidoctor.js renderer but you can use highlightjs (you'll need to set preview security to disable). See the [user manual](https://asciidoctor.org/docs/user-manual/#available-source-highlighters). I don't think prettyify is available anymore (the project is archived and not mention in the asciidoctor.js source).

Pygments is a Python 2 library. If you are using Ruby asciidoctor and have this installed on your system it will work.

But this extension will only work with JavaScript compatible syntax highlighters and the only bundled one with Asciidoctor.js is highlightjs.
