### ISSUE TITLE
save to automation toolchain

### ISSUE THREAD

**Issue by edl7878** [asciidoctor/asciidoctor-vscode#318]
This extension is great.

As build-in asciidoc.saveDocbook command use kroki to render diagram, it is the best way to generate diagrams of a adoc file.

adoc -> DocBook -> odt/docx is needed in my work.

1. adoc -> DocBook : asciidoc.saveDocbook (vscode command)
2.  DocBook -> odt/docx: pandoc --from docbook --to docx <source>.xml -o <destination>.docx (command line command)

Is it possible to automate these two steps into one step?  For example, as a vs-code task?

Thanks.

**Comment by danyill** [comment]
Thanks @edl7878 for your kind words and thanks for reporting.

Sure, you can use tasks to achieve this. At least on my machine something like this works:

*tasks.json*
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Save to Docbook",
            "command": "${command:asciidoc.saveDocbook}",
        },
        {
            "label": "Convert Docbook to Word with Pandoc",
            "type": "shell",
            "command": "pandoc",
            "args": [
                "-s",
                "--from",
                "docbook",
                {
                    "value": "${fileDirname}/${fileBasenameNoExtension}.xml",
                    "quoting": "escape"
                },
                "--to=docx",
                "-o",
                {
                    "value": "${fileDirname}/${fileBasenameNoExtension}.docx",
                    "quoting": "escape"
                }]
        },
        {
            "label": "Asciidoc to Word",
            "dependsOrder": "sequence",
            "dependsOn": [
                "Save to Docbook",
                "Convert Docbook to Word with Pandoc"
            ]
        }
    ]
}
```

However perhaps you're saying it's difficult to get the diagrams from asciidoctor-kroki?
You can set the `kroki-fetch-diagram` attribute in the header to achieve this but at the moment there's a small bug which will be fixed in the next release and then we'll integrate it into the extension, see https://github.com/Mogztter/asciidoctor-kroki/issues/62

**Comment by edl7878** [comment]
@danyill Thanks for your instant reply.

Based on your code, I realized the toolchain on Windows 10.

```
{
    "version": "2.0.0",
    "tasks": [
        // adoc -asciidoc.saveDocbook-> Docbook: ${command:asciidoc.saveDocbook}
        {
            "label": "adoc -> Docbook (asciidoc.saveDocbook)",
            "command": "${command:asciidoc.saveDocbook}"
        },
        // Docbook -pandoc-> docx : pandoc -s --from docbook [source] --to=docx -o [destination]
        {
            "label": "Docbook -> docx (pandoc)",
            "type": "shell",
            "command": "pandoc",
            "args": [
                "-s",
                "--from",
                "docbook",
                {
                    "value": "${fileDirname}/${fileBasenameNoExtension}.xml",
                    "quoting": "strong"
                },
                "--to=docx",
                "-o",
                {
                    "value": "${fileDirname}/${fileBasenameNoExtension}.docx",
                    "quoting": "strong"
                }
            ]
        },
        // adoc-> Docbook -> docx
        {
            "label": "adoc-> Docbook -> docx",
            "dependsOrder": "sequence",
            "dependsOn": [
                "adoc -> Docbook (asciidoc.saveDocbook)",
                "Docbook -> docx (pandoc)"
            ],
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
I tested kroki with docker, vscode  settings.json:

```
"asciidoc.preview.attributes": {
"kroki-server-url": "http://localhost:8000"
},
"asciidoc.use_kroki": true,
```

So far, so good. Except for mermaid diagram which I often used is not workable:

To provide kroki server an url, a diagram will be returned.
As my test, korki server can return mermaid diagram correctly, but can't be showed by this extension in preview or any out put format.

I think using kroki is a better way for the extension to get diagrams, since it is a "one config all diagrams" solution.
