### ISSUE TITLE
Font size / preview style too large and setting doesn't work

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#320]
The preview font size option doesn't appear to do anything:

![image](https://user-images.githubusercontent.com/674783/82796632-f12b8e00-9ec9-11ea-9c42-d9135acc53f8.png)

Compared to the Markdown extension this extension has a rather large set of fonts:

*Markdown*

![image](https://user-images.githubusercontent.com/674783/82796677-086a7b80-9eca-11ea-9c16-11d49547f37b.png)

*Asciidoc*

![image](https://user-images.githubusercontent.com/674783/82796690-10c2b680-9eca-11ea-98aa-2cb4b3411376.png)

On the Asciidoctor gitter channel there were some comments about this not being great.
I think we could provide a control to scale down the size of all CSS in the preview.

**Comment by rosasco-wk** [comment]
Any word on this one ?

**Comment by Mogztter** [comment]
Related to https://github.com/asciidoctor/asciidoctor-vscode/issues/365
