### ISSUE TITLE
Problem creating .pdf with v2.7.16

### ISSUE THREAD

**Issue by uwaibel** [asciidoctor/asciidoctor-vscode#331]
## Description

Have a problem to create a pdf file with the plugin for visual studio code. 

sample asciidoc file
```
= Simple Testfile

:icons: font
:hardbreaks:

== my first heading
here comes some simple text

=== Heading 2

* bullet1 
.. numbered
* bullet 2
.. numbered

WARNING: seems to be a strange document
```

After a few seconds I get the message

`Successfully converted to Simple.pdf
`
but also the error

```
Invalid argument @ dir_s_mkdir - c:/c:
  Use --trace for backtrace

command: asciidoctor-pdf.bat -q -B "c:\Develop\Sample" -o "c:\c:\Develop\Sample\Simple.pdf" -
If the asciidoctor-pdf binary is not in your PATH, you can set the full path.Go to `File -> Preferences -> User settings` and adjust the asciidoc.asciidoctorpdf_command

```
I have no idea where the duplicate drive c:\c:\ come from in the path.

## System Information
AsciiDoc Plugin v2.7.16

- Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:CP850 ex:CP850)

**Visual Studio Code**
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

## To Reproduce

Steps to reproduce the issue:

1. Go to Command Palette
2. Click on AsciiDoc:Export document as PDF
3. 

## Screenshots & Files

If applicable, add screenshots to help explain your problem. If the problem occurs only in a specific file, attach the file to the issue (do not copy the contents here).

**Comment by uwaibel** [comment]
It works on a other workstation with VSCode v1.42.1 and AsciiDoc Plugin v2.7.16
The major difference is the Ruby version. Here I am using v2.5.3p105 and the asciidoctor-pdf v1.5.0.rc.1
On both workstations  the cli for asciidoctor-pdf does work.

**Comment by uwaibel** [comment]
After upgrading the VSCode to 

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

the problem exist now on the other workstation also

**Comment by uwaibel** [comment]
after several trials, I can definitely say it is caused by the latest version of the plugin. Downgrading to v2.7.15 solve the problem

**Comment by GauntletPL** [comment]
I'm facing the same issue.

It seems to be caused by this line of ExportAsPDF.ts:

`pdfPath = path.join(docPath.root, docPath.dir, docPath.name+".pdf")`

`docPath.root` evaluates to `c:\`, which is already contained in `docPath.dir` (`c:\develop\sample`). Executing `path.join()` on top of that causes the `c:\` bit to be doubled.

The problem was not apparent before, because 'Save' dialogue was effectively overwriting incorrect content of `pdfPath` variable.

**Comment by joaompinto** [comment]
Thanks for reporting, I will try to provide a release with the fix still today.

**Comment by joaompinto** [comment]
2.7.17 includes the fix, please let me know if you still find the issue with the newer version.
