### ISSUE TITLE
Is "AsciiDoc: Export Document as Pdf"  broken?

### ISSUE THREAD

**Issue by edl7878** [asciidoctor/asciidoctor-vscode#332]
*Export Document as Pdf* not work with v2.7.17

## Error message:

Error converting to PDF, Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[================>                                           ] 27%
Warning: Failed to load file:///C:/Users/abc/AppData/Local/Temp/1-5-2020-23-05-51-PM.png (ignore)
Warning: Failed to load file:///C:/Users/abc/AppData/Local/Temp/sunset.jpg (ignore)
Warning: Failed to load file:///C:/Users/abc/AppData/Local/Temp/icons/play.png (ignore)
Warning: Failed to load file:///C:/Users/abc/AppData/Local/Temp/icons/pause.png (ignore)
[===================>                                        ] 33%
[=====================>                                      ] 36%
[=========================>                                  ] 43%
[==============================>                             ] 51%
[=================================>                          ] 56%
[====================================>                       ] 61%
[========================================>                   ] 67%
[===========================================>                ] 72%
[=============================================>              ] 76%
[================================================>           ] 80%
[==================================================>         ] 84%
[===================================================>        ] 86%
[====================================================>       ] 87%
[============================================================] 100%
QPainter::begin(): Returned false
Error: Unable to write to destination                              
Exit with code 1, due to unknown error.

**Comment by edl7878** [comment]
I tested 2..7.15, 2.7.16, 2.7.17.

Only 2.7.15 is workable.

**Comment by joaompinto** [comment]
I am not able to reproduce the problem so I am gong to revert to the behavior of showing the "Save As" dialog that we ad on 2.7.15.

**Comment by AFulgens** [comment]
I can reproduce with 2.7.17.

**Comment by GauntletPL** [comment]
Is it possible that the build did not happen correctly?
Even the summary screen of the extension in the VSCode looks strange (missing 'Details' and 'Changelog' tabs):

![image](https://user-images.githubusercontent.com/42208078/85705342-6a90e900-b6e1-11ea-9c29-af4b495b9456.png)

This is how it normally looks like:

![image](https://user-images.githubusercontent.com/42208078/85705605-a9bf3a00-b6e1-11ea-8ce6-0cd102ff0741.png)

Also - in the extensions folder on my disc - 2.7.17 was installed not as an upgrade, but as a separate folder. It did not do it this way before.

![image](https://user-images.githubusercontent.com/42208078/85706552-9c567f80-b6e2-11ea-9577-25b2ddd71f4e.png)

**Comment by joaompinto** [comment]
I did some major changes to exclude unnecessary files from the extension, it seems I excluded some core file about the package information. Will check it now.

**Comment by uwaibel** [comment]
facing the same issue as with v2.7.16. Seems the fix did not work, see #331

**Comment by joaompinto** [comment]
Can you please test with 2.7.18 and let me know the result ?

Thanks

**Comment by uwaibel** [comment]
Hi Joao Pinto, 

the .pdf export is now working fine. However the “save as” behavior is slightly different than in v2.7.15.

When the dialog opens, the file name in the previous version was predefined with the name of the .adoc file, now it is shown empty.

E.g. simple.adoc should be shown as simple.pdf and saved as the same

 

Best regards

Uli Waibel

 

Von: João Pinto <notifications@github.com> 
Gesendet: Freitag, 26. Juni 2020 21:57
An: asciidoctor/asciidoctor-vscode <asciidoctor-vscode@noreply.github.com>
Cc: Uli Waibel <uwaibel@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [asciidoctor/asciidoctor-vscode] Is "AsciiDoc: Export Document as Pdf" broken? (#332)

 

Can you please test with 2.7.18 and let me know the result ?

Thanks

**Comment by edl7878** [comment]
2.7.18 is workable.

the file name in the previous version was predefined with the name of the .adoc file, **now it is the same behavior** in my test.

Thanks.

**Comment by joaompinto** [comment]
@uwaibel I am not able to reproduce your problem, I am getting "simple.pdf" as the default for "simple.adoc" are you using Windows or Linux?

**Comment by uwaibel** [comment]
Hi
using Windows 10 pro 
Regards 
Uli 

Von meinem iPhone gesendet
