### ISSUE TITLE
Something weird when scrolling?

### ISSUE THREAD

**Issue by DaLynxx** [asciidoctor/asciidoctor-vscode#348]
## Description

1st thing)
If i have a preview running next to an .adoc file and scrolls, having focus on the .adoc file, When scrolling from below and up... the preview will stop at the first level heading while the .adoc will scroll to the top showing the title. (starting with a '='

The top of the document renders and I can reach it by switching focus to the preview and continue the scroll upwards.

2nd thing)
When I switch focus to the preview and scroll to the top (I.e. i see the title, the scroll in the .adoc file does not reach (i.e. show) the top-most row.

## System Information

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Asciidoc 2.8.1

## To Reproduce

Steps to reproduce the issue:

1. Go to https://asciidoctor.org/docs/asciidoc-article/ and copy that asciidoc example (to get something to demo on)
2. Setup with having an .adoc next to an asciidoctor preview (i.e. split window)
3. Click on the adoc file and scroll to the bottom. (the preview tags along).
4. Scroll back up to the top of the .adoc file so you see the 1st row (the 1st row starts with "= AsciiDoc Article Title"
5. The preview does not show the title of the document. Instead it shows 1 row above the first "first level heading" (see screenshot)
6 swap focus to the preview and scroll to the top.
7. You can then see the rendered title but... now you can't see the 1st row of the .adoc file. (screenshot 2)

## Screenshots & Files

Screenshot 1.

![image](https://user-images.githubusercontent.com/1823630/87079723-c5205e00-c226-11ea-972e-6c1226c23dab.png)

Screenshot 2.

![image](https://user-images.githubusercontent.com/1823630/87079783-da958800-c226-11ea-82c5-4f988ec95635.png)

**Comment by richardmcsong** [comment]
I'm seeing this too -- seems to happen whenever there are any header tags like `:test: value` or `:icons: font`

**Comment by jamesongithub** [comment]
seems to happen if the first line is a title for me **and** when the preview cant fit the entire document without scrolling

![image](https://user-images.githubusercontent.com/4452738/108277006-88f29b80-712d-11eb-981a-4baf5b26d9f9.png)

```
= myTitle

1

2

3
```

**Comment by Mogztter** [comment]
I can also reproduce this issue.
