### ISSUE TITLE
Exported PDF files are named "Untitled"

### ISSUE THREAD

**Issue by DanielSWolf** [asciidoctor/asciidoctor-vscode#349]
## Description

When I run "AsciiDoc: Export document as PDF", a save dialog appears. In the past, the default directory of this dialog was the directory containing the AsciiDoc file and the default file name was the name of the AsciiDoc file but with the extension _.pdf_.

Now, the default directory is the root of my hard disk and the default file name is "Untitled". This means that each time I export a PDF, I have to navigate to a sensible directory and manually type in the file name.

## System Information

**VS Code:**
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (3 wks ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Extension:** v2.8.1

## To Reproduce

Steps to reproduce the issue:

1. Open an _.adoc_ file.
2. Hit F1, run "AsciiDoc: Export document as PDF"
4. A save dialog appears.
3. Observe that neither the directory nor the file name in the dialog have sensible default values.

**Comment by joaompinto** [comment]
I have failed to identify the problem while testing because it's specific to the "Use_asciidoctorpdf" which I was not using , I will look at it.

Thanks for reporting

**Comment by Mogztter** [comment]
@DanielSWolf could you please confirm that this is now fixed?

**Comment by DanielSWolf** [comment]
@Mogztter Sorry for the late reply. I can confirm that the dialog now behaves as expected. Thank you!
