### ISSUE TITLE
Convert images to base64 when printing to HTML

### ISSUE THREAD

**Issue by FunnyYish** [asciidoctor/asciidoctor-vscode#356]
like the `markdown.extension.print.imgToBase64` option in [markdown-all-in-one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#supported-settings)

**Comment by tigion** [comment]
Like the [:data-uri:](https://asciidoctor.org/docs/user-manual/#managing-images) document attribute?

**Comment by Mogztter** [comment]
@tigion is right you should use the `:data-uri:` attribute. You can add it in your AsciiDoc document:

```
= Document Title
:data-uri:

// ...

image:sunset.jpg[]
```

The sunset image will be converted to base64 and embedded in the HTML file.

https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/#embed-images-with-the-data-uri-attribute
