### ISSUE TITLE
Preview does not open after "Activating extensions" and then marked as "Unresponsive" "performance issue"

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor-vscode#357]
vscode 1.47.3, asciidoctor-vscode 2.8.3 installed on Ubuntu 20.04 with `snap`, Asciidoctor 2.0.10, adoc hello world:

```
= hello

world
```

notifications shows:

```
The extension 'AsciiDoc' took a very long time to complete its last operation and it has prevented other extensions from running.
```

**Comment by Mogztter** [comment]
Yikes!
@cirosantilli could you please try again with the latest version on your system?

**Comment by cirosantilli** [comment]
I tried again on Ubuntu 20.10 vscode 1.56.1 asciidoctor.asciidoctor-vscode@2.8.9 and now it worked.

**Comment by cirosantilli** [comment]
I tried again on Ubuntu 20.10 vscode 1.56.1 asciidoctor.asciidoctor-vscode@2.8.9 and now it worked.

**Comment by Mogztter** [comment]
Thanks for the follow-up and I'm glad it's fixed 😅
