### ISSUE TITLE
Preview: Font Size and Line Height not working

### ISSUE THREAD

**Issue by HunterFrisby** [asciidoctor/asciidoctor-vscode#365]
This is an example issue. Use just the headings and fill out all necessary information. Screenshots & Files and Additional Context are optional.

## Description

The Preview: Font Size and Preview: Line Height are not working.

## System Information

Visual Studio Code - Insiders
- Version: 1.50.0-insider (user setup)
- Commit: 9e505675670d65138405321a60b0df4ddec28799
- Date: 2020-09-16T06:49:37.816Z
- Electron: 9.3.0
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.18363

## To Reproduce

Modifying the asciidoc.preview.fontSize and/or asciidoc.preview.lineHeight does not affect the preview in any way. I have tried this with both asciidoc.preview.useEditorStyle enabled/disabled and asciidoc.use_asciidoctor_js enabled/disabled.

**Comment by bdutta** [comment]
Indeed have same issue on Ubuntu Linux 20.04 with latest updates. I am using VSCode 1.52.1 (Electron: 9.3.5, Chrome: 83.0.4103.122, Node.js: 12.14.1, V8: 8.3.110.13-electron.0).

**Comment by agrexgh** [comment]
Same here.
I use it on Ubuntu 20.04 on WSL2.

## information about asciidoc extension

Name: AsciiDoc
Id: asciidoctor.asciidoctor-vscode
Description: Provides rich language support for AsciiDoc.
Version: 2.8.10
Publisher: asciidoctor
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode

## information about vs code

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by Mogztter** [comment]
I can reproduce this issue
