### ISSUE TITLE
Can't render laexmath or asciimath in vs code

### ISSUE THREAD

**Issue by mariotoffia** [asciidoctor/asciidoctor-vscode#368]
Hi and thanks for this **great** vs code plugin!

I have a problem with rendering latexmath or asciimath in vs code preview. I certainly can be my fault but it seems pretty straight forward to do simple expressions.

Cheers,
 Mario

## Description

I'm having the following in a `overview.adoc` document.

```
stem:[sqrt(4) = 2] 
asciimath:[sqrt(4) = 2]
```

It outputs
```
\$sqrt(4) = 2\$ \$sqrt(4) = 2\$
```

## System Information

Windows 10, WSL2, asciidoctor.asciidoctor-vscode v2.8.3.

Vs Code About:
```
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

## To Reproduce

Create a document with content above and choose preview asciidoc.

## Screenshots & Files

The problem
![image](https://user-images.githubusercontent.com/1716527/95861100-44ab5500-0d61-11eb-8948-19710a94d77b.png)

The security settings
![image](https://user-images.githubusercontent.com/1716527/95861182-6278ba00-0d61-11eb-874d-853a5c9cc547.png)

**Comment by Leon0402** [comment]
Does this work if you compile it to html? (i.e. have you set the stem macro and verified that it's working with plan asciidoctor)

Have you reloaded the document after you changed the security settings? I had to do that.

**Comment by mariotoffia** [comment]
@Leon0402  thanks for the help! It was SBS from my side - I did not set `:stem: latexmath` in the header!

Many Thanks!
 Mario :)
