### ISSUE TITLE
Callouts in Codeblocks missing

### ISSUE THREAD

**Issue by theOneJMK** [asciidoctor/asciidoctor-vscode#369]
## Description

If a source block is used in asciidoc the documentation shows call outs like this: 
![image](https://user-images.githubusercontent.com/56893193/96168631-5176a700-0f21-11eb-965f-2d6d84374f6d.png)
see: https://asciidoctor.org/docs/asciidoc-writers-guide/

But actually the callouts are presented as comments in the VsCode preview:
![image](https://user-images.githubusercontent.com/56893193/96168750-84b93600-0f21-11eb-868f-4f9a6a3adb2a.png)

There might be a relation to #342 
## System Information

I'm Using Version 2.8.3 in VSCode 1.48.2 on Mac OS 10.15.6

**Comment by tigion** [comment]
The `:icons: font` document attribute is needed.

**Comment by theOneJMK** [comment]
This solution works. Thank you!
