### ISSUE TITLE
Typo "ascidoctor.css" with only one 'i' in the setting descriptions

### ISSUE THREAD

**Issue by tigion** [asciidoctor/asciidoctor-vscode#371]
## Description

I think there is a typo "ascidoctor.css" with only one 'i' in the settings view for the Asciidoc extension.

- to find under: "Asciidoc > Preview: Use Editor Style"
- text: "Use editor style instead of default ascidoctor.css"
- (project file:  [asciidoctor-vscode/package.nls.json](https://github.com/asciidoctor/asciidoctor-vscode/blob/09b59da54ff6d0fbeccc9653a1de74be62006768/package.nls.json))

## System Information

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
```
Extension Version: 2.8.4
```

## Screenshots & Files

<img width="352" alt="Bildschirmfoto 2020-10-20 um 12 07 34" src="https://user-images.githubusercontent.com/31811/96573936-1680c480-12cf-11eb-9daf-7f60eb8f61ad.png">

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-vscode/commit/ad417d859ef1636a9f4714529ae57afa47f7e6d6 (and released in version 2.8.8).

Thanks @tigion !
