### ISSUE TITLE
Preview image does not display with relative UNC-path

### ISSUE THREAD

**Issue by simtec66** [asciidoctor/asciidoctor-vscode#383]
Images do not show up in the preview if the image-path is relative and the image is stored on a Windows-share:

Assuming the image ```example.png``` is located at ```//server/sharename/example.png```:

```asciidoc
image::example.png[]
```
vscode does not show the preview image and a warning is shown in the output window with the following text: **"image to embed not found or not readable: /server/sharename/example.png"**. Note that vscode removes the first **/** from the UNC-path. If an absolute UNC-path is provided the image shows up correctly in the preview.

**Comment by simtec66** [comment]
The following helps:

`:data-uri: {docdir}`

But I don't understand why this is required.

**Comment by tiktuk** [comment]
I'm on Mac and images also don't display in the preview for me, relative or not.

**Comment by Linden-GitHub-Account** [comment]
I've gone to the settings.json for AsciiDoc in VSCode and put:

```
    "asciidoc.preview.attributes": {
        "imagesdir": "../images/"
    
    }
```
That's fixed the problem for me.

**Comment by tiktuk** [comment]
@Linden-GitHub-Account is that what you'd put in the front matter otherwise? Because I can't get that to work..

**Comment by Rasbats** [comment]
@Linden-GitHub-Account : Brilliant. Thanks very much.

**Comment by pietrom16** [comment]
@Linden-GitHub-Account

Even for me your approach does not work. Tried with:

```
:imagesdir: "../images dir/"
:imagesdir: images_dir
:imagesdir: ../images_dir/
```

**Comment by Mogztter** [comment]
This is most likely a bug in Asciidoctor.js with UNC-path.

**Comment by Jeeppler** [comment]
@simtec66 your answer worked:

```
:data-uri: {docdir}
```
