### ISSUE TITLE
Preview images don't show if the folder name of the doucment starts with a number followed by a dot and a blank ("1. xxx")

### ISSUE THREAD

**Issue by WalterZrep** [asciidoctor/asciidoctor-vscode#391]
## Description

If I have my .adoc document stored in a folder that starts with a number followed by a dot and a blank, e.g. **_1. Test_**,  preview images are not showing.

## System Information

Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

AsciiDoc V2.8.7

## To Reproduce

A file is attached

## Screenshots & Files

![image](https://user-images.githubusercontent.com/80189975/110231279-fddc1880-7f16-11eb-984a-23808f1584df.png)

[2. Test.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/6096672/2.Test.zip)

**Comment by Mogztter** [comment]
I can reproduce this issue and I think it's a VS Code Webview issue.
I can also reproduce this issue using the [HTML preview extension](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) with the following HTML page:

```html
<html>
  <body>
    <img src="sunset.jpg" alt="sunset">
  </body>
</html>
```

@WalterZrep Please report this issue at https://github.com/microsoft/vscode
