### ISSUE TITLE
manual invocation or workspace-level setting for asciidoctor-vscode for other file exts

### ISSUE THREAD

**Issue by rosasco-wk** [asciidoctor/asciidoctor-vscode#394]
I'm working on a codebase that uses ".txt" file extensions for asciidoc files.  This is normally done for files that will be included by other files.  The root files in the project are .adoc and include the .txt files within them.

It would be a big win if I could manually invoke asciidoctor-vscode on any file of my choosing, .txt in this case.  Alternatively, a workspace-level setting in which I could specify the file extension upon which asciidoctor always runs/manages would work great.

Today, I'm renaming the .txt files and then moving them back to their original names before committing.

This is a great tool. Thanks and keep up the good work!

**Comment by rongcuid** [comment]
You can use a  setting in your workspace `settings.json`:
```
    "files.associations": {
        "*.txt": "asciidoc"
    }
```
Create or append.

**Comment by rosasco-wk** [comment]
Thanks.
