### ISSUE TITLE
Console error:​ Refused to load the image .. because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by tiktuk** [asciidoctor/asciidoctor-vscode#396]
This is an example issue. Use just the headings and fill out all necessary information. Screenshots & Files and Additional Context are optional.

## Description

Images are not shown in the preview (they work fine when the file is exported instead).

## System Information

```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

Extension: v2.8.8

## To Reproduce

Show the preview pane for a file that references images.

## Screenshots & Files

![Screenshot 2021-03-22 at 19 31 13](https://user-images.githubusercontent.com/153722/112040176-2d109d80-8b45-11eb-93fb-2b2f73039093.png)

## Additional Context

I get this message in the Console:

    ​ [Embedded Page] Refused to load the image 'vscode-resource:example.jpg' because it violates the following Content Security Policy directive: "img-src vscode-webview-resource: http: https: data:".

**Comment by ThompsonLA** [comment]
Same Problem here. On Windows 10, i am the owner of the jpg File.

**Comment by Mogztter** [comment]
@ThompsonLA Could you please share a sample document and also information about your file/directory structure? Are your using WSL 2?

**Comment by ThompsonLA** [comment]
Ok, now I have take a closer look at the Problem and I think I know the Problem now. When I have a path with a blank character, then it doesn't work.

**Comment by maventis** [comment]
> Ok, now I have take a closer look at the Problem and I think I know the Problem now. When I have a path with a blank character, then it doesn't work.

Yes I can reproduce this issue as well. If my path to the document/image has any spaces in it, it will fail to render.

For example:

**Working:**
`C:\mydocumentation\mydoc.adoc`
`C:\mydocumentation\myimg.png`

**Fail:**
`C:\my documentation\mydoc.adoc`
`C:\my documentation\myimg.png`

**Comment by Mogztter** [comment]
I don't think this is related to the original issue.
@maventis @ThompsonLA What you are describing is most likely a VS Code bug, see: https://github.com/asciidoctor/asciidoctor-vscode/issues/352


@tiktuk could you please provide more information please?

**Comment by yungthai** [comment]
Also fails to render images for .adoc filenames with whitespaces e.g.

`c:/path/noSpaces/Document With whiteSpaces.adoc`

AsciiDoc v2.8.9.
```
VSCode
Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by tiktuk** [comment]
> @tiktuk could you please provide more information please?

Sorry, have been away from this project but just checked and in the current version the problem is no longer there :) .

Thanks for the work on this extension
