### ISSUE TITLE
Upgrade to Asciidoctor.js 2.2.4

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-vscode#408]
## Describe the solution you'd like

The extension is currently using Asciidoctor.js 2.1.0 (released 26 Jan 2020).
We should upgrade to [Asciidoctor.js 2.2.4](https://github.com/asciidoctor/asciidoctor.js/releases/tag/v2.2.4) (release 30 April 2021) to benefit from the latest features and bug fixes.

This upgrade will fix:

- #384 

## Additional context

This release doesn't include break changes but we should still be careful when doing the upgrade.

**Comment by joaompinto** [comment]
We don't have a proper testing process, maybe we  just upgrade and handle any new issues ?

**Comment by Mogztter** [comment]
We could do that but we could also take this opportunity to add a few automated tests 😄

**Comment by danyill** [comment]
Yes please to more tests!

I badly want to have some tests to allow "safer contributions".

It's blocking me from contributing more because this extension now has a
reasonable number of users and I'm afraid of breakages.

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-vscode/pull/418
