### ISSUE TITLE
Provide setting options/parameters to stop the preview scroll with the actual text

### ISSUE THREAD

**Issue by kappa-wingman** [asciidoctor/asciidoctor-vscode#411]
When the adoc file has a long code for a long table, the position of the live preview  is not in the correct location with the current position of the text.

I have [this problem with RestructuredText in VSCode](https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/295). That plugin [provides options](https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/121#issuecomment-455388973) to disable it so they won't scroll together.

So  I would like to know if this plugin could provide this feature too.

**Comment by abelsromero** [comment]
Both options are available in the setting section.

![image](https://user-images.githubusercontent.com/5781153/121590382-8c8d9380-ca38-11eb-821c-4e9186c88ee0.png)

**Comment by kappa-wingman** [comment]
It is the option I wanted. Thanks for the help.
