### ISSUE TITLE
Support for custom templates in use_asciidoctor_js 

### ISSUE THREAD

**Issue by HESHN** [asciidoctor/asciidoctor-vscode#413]
Is there a way to attach custom template directories (.hbs etc)  to work with the preview screen? I'm currently running this using asciidoctor_command  + --template-dir argument but the tradeoff is the auto-scrolling option.

**Comment by danyill** [comment]
I'd like to do this too. At the same time as we look to add custom extensions in #422, we could look into custom templates.
