### ISSUE TITLE
The number of the chapter should be start from 0.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-vscode#415]
## Description

I follow https://github.com/asciidoctor/asciidoctor/issues/1434#issuecomment-869369932 to configure my document. But the start number of chapter is start from `1`, not `0`.

## System Information

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (1 wk ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

asciidoctor-vscode: v2.8.9
```

## To Reproduce

Clone my repo, and open the `assignment.adoc`.

![image](https://user-images.githubusercontent.com/2121467/123727968-1b1d6400-d8c5-11eb-8e11-73b210c1c277.png)

Use `asciidoctor` command to convert the document:

![image](https://user-images.githubusercontent.com/2121467/123728055-44d68b00-d8c5-11eb-8d07-537fb7dc56a3.png)

It's OK.

## Screenshots & Files

https://github.com/huoqiangshou/fireworks/blob/master/assignment.adoc

**Comment by Mogztter** [comment]
I think we need to upgrade to Asciidoctor.js 2.2.4. This feature was inadvertently broke in Asciidoctor 2.0.13 core (Asciidoctor.js 2.2.3).
