### ISSUE TITLE
"Follow link (ctrl + click)" does not direct to correct link & not show correctly

### ISSUE THREAD

**Issue by TINGWEIJING** [asciidoctor/asciidoctor-vscode#417]
## Description
Follow link (ctrl + click) the URL macros does not direct to correct link, the link contains square brackets and attribute of URL macros.

Follow link (ctrl + click) message also does not show correctly when hover over the URL macros if the attribute of URL macros contains space.

## System Information
```
Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
```

Extension information
```
Name: AsciiDoc
Id: asciidoctor.asciidoctor-vscode
Description: Provides rich language support for AsciiDoc.
Version: 2.8.9
Publisher: asciidoctor
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode
```

## To Reproduce
Steps to reproduce the issue:

1. Create any URL macros in asciidoc file.
Example:
```
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc Syntax Quick Reference]
```
2. Hover over URL macros (incorrect display, refer image under Screenshots section)
3. `Ctrl + click` it to direct to the link (incorrect direction)

## Screenshots
![image](https://user-images.githubusercontent.com/55592054/124248372-5afa7a80-db55-11eb-8b66-d4cecdf5dc69.png)

![image](https://user-images.githubusercontent.com/55592054/124248536-867d6500-db55-11eb-9fc6-9de8aa9f1d5e.png)

**Comment by Mogztter** [comment]
Thanks for the detailed error report.

It seems that VS Code assumes that the link is written using Markdown.
As you can see in the popup, it even adds `[Follow link]` and considers that `https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[AsciiDoc Syntax Quick Reference]` is the URL 🤦🏻 

Not sure if we can't override this behavior.

**Comment by Mogztter** [comment]
This is a built-in feature but you can disable it using `"editor.links": false`

![editor-link](https://user-images.githubusercontent.com/333276/124394066-f0387300-dcfd-11eb-8681-728f3c603d82.png)

It seems that we could register a link provider: https://github.com/asciidoctor/asciidoctor-vscode/issues/99
Since this issue is a duplicate, I will close it.
