### ISSUE TITLE
Pikchr diagram doesn't work?

### ISSUE THREAD

**Issue by chtenb** [asciidoctor/asciidoctor-vscode#419]
![image](https://user-images.githubusercontent.com/1030961/125166688-067e7d00-e19d-11eb-8d73-d707806f944c.png)

As you can see in the screenshot, other diagrams seem to work fine. What strikes me is that `[blockdiag]` is colored blue, while `[pikchr]` is not. Does this diagram type still need to be registered in this plugin or something?

**Comment by Mogztter** [comment]
You are correct, `pikchr` support was just released in https://github.com/Mogztter/asciidoctor-kroki/releases/tag/v0.13.0

That's the reason why the block is not recognized.

We need to update the version in the `package.json`:


https://github.com/asciidoctor/asciidoctor-vscode/blob/8d7c8b8fbed0b826705daadbd4592481d2e808d7/package.json#L494
