### ISSUE TITLE
Extension cannot be installed in vs-code web

### ISSUE THREAD

**Issue by AlexCzar** [asciidoctor/asciidoctor-vscode#429]
## Description

The extension is not available for installation in vs-code web (e.g. in GitHub web editor)

## System Information

GitHub web-editor (vs-code web)

## To Reproduce

1. Open any repository on github
2. press `.` (dot)
3. when vscode editor opens go to extensions (Ctrl+Shift+X/Cmd+Shift+X)
4. type 'asciidoctor' you'll see the extension grayed out (not-installable)

## Screenshots & Files
![image](https://user-images.githubusercontent.com/1010298/129588015-053e7b75-10da-4b75-9de5-fc178790d70f.png)

## Additional Context

Could be related to #317

**Comment by Mogztter** [comment]
> Could be related to #317

Not sure but I found this page:

> Why is an extension not installable in the browser
There are a small number of extensions that have built-in assumptions or need to run on the desktop. **Examples are when an extension accesses files from the VS Code installation on the desktop or when an extension depends on an executable that must run in a desktop environment.** When you try to install such an extension in the browser, you will be informed that the extension is not available.
Notice such an extension can still be used when connecting to a Codespace from VS Code running on the desktop.

https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser

We are using the `child_process`, `fs` and `path` modules (from Node) that might be the reason why the extension is not available.

**Comment by Mogztter** [comment]
It's a bit unfortunate that Visual Code Web does not tell us exactly why the extension is disabled... or provide a tool to check if the extension is compatible or not.

**Comment by kaovilai** [comment]
@Mogztter you can now simply press `.` on the github repo to launch VS Code Web albeit without certain features but you can certainly test out for compatible extensions.

For this repository it would launch web editor if you go to https://github.dev/asciidoctor/asciidoctor-vscode
You should then be able to see installable extensions there.

**Comment by Mogztter** [comment]
> you can now simply press . on the github repo to launch VS Code Web albeit without certain features but you can certainly test out for compatible extensions.
> For this repository it would launch web editor if you go to github.dev/asciidoctor/asciidoctor-vscode
You should then be able to see installable extensions there.

I know but it does not say *why* the extension cannot be installed:

![vscodeweb](https://user-images.githubusercontent.com/333276/133208903-606f3d3d-df05-4481-804b-99b6d9160b22.png)

"Learn more" is just a link to: https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser

Since I don't know why I don't know how to "fix" the extension, I can only guess... Maybe @mjbvz could give us a hint? If so, that would be great 🤗

**Comment by Mogztter** [comment]
Good news you can now install the extension, bad news it does not work 😭 

See: https://github.com/asciidoctor/asciidoctor-vscode/issues/499

**Comment by Mogztter** [comment]
Closing, the extension is now available as a pre-version (**alpha**) in https://github.dev and https://vscode.dev
Feel free to give it a try and report any issues.
