### ISSUE TITLE
No code highlight in preview

### ISSUE THREAD

**Issue by limejuly** [asciidoctor/asciidoctor-vscode#437]
## Description

In the preview window, no code highlight is generated. 

## System Information

Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.5.0

## To Reproduce

Steps to reproduce the issue:

1. add some simple codes of any language.
2. open preview window
3. see if code highlight is shown.

## Screenshots & Files
<img width="1226" alt="截屏2021-09-11 上午12 44 09" src="https://user-images.githubusercontent.com/33826046/132889105-5dc6947e-1300-4894-a38c-21fe9215b2b9.png">

**Comment by Mogztter** [comment]
You need to enable source highligthing using `:source-highlighter: highlight.js`.

![vscode-syntax-highligter](https://user-images.githubusercontent.com/333276/132944268-b26b83d7-67fe-4ae4-8ccc-93530f1a8e56.png)

Reference: https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/

**Comment by limejuly** [comment]
@Mogztter  Thanks. That is the most important thing I missed. 

And also, I find another step needed. Even if this line is added, vscode would prevent it from rendering.  In the bottom of preview window, it would say "Some content has been disabled in this document". Seems like highlight.js contents are not https. To get it work, one should click it and set it to Disable.

**Comment by Mogztter** [comment]
Thanks for the follow-up.
We are loading Highlight.js through HTTPS but we do not use the Subresource Integrity feature and I think that's the reason why VS Code consider that this is unsafe: https://developer.mozilla.org/fr/docs/Web/Security/Subresource_Integrity

Hopefully, https://github.com/asciidoctor/asciidoctor-vscode/pull/440 will make a more seamless integration of Highlight.js in VS Code.
