### ISSUE TITLE
Enforce a code style (via a linter) to make the code consistent

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-vscode#446]
We could use [ESLint](https://github.com/eslint/eslint) with https://github.com/typescript-eslint/typescript-eslint or [Standard](https://standardjs.com/) I don't really mind but I think it's important to enforce a code style.

**Comment by danyill** [comment]
I agree this is important. I've put a draft PR to look at this and discuss how we do it further.
