### ISSUE TITLE
Preview does not show current line being edited

### ISSUE THREAD

**Issue by Johan1974** [asciidoctor/asciidoctor-vscode#462]
Hello,

I notice with the preview that the focus does not stay on the part you are editing but jumps back to the beginning every time.
So to see my changes i have to scrool back to the place i have changed.

Is there a way to keep the preview focussed on the part that you are changing? 

Thanks!

Johan

**Comment by danyill** [comment]
Thanks for filing an issue!

If you have the user settings on their defaults or set to true it should be focussed on what you are changing, the source editor and the preview pane should scroll together through the document.

These are the settings which should be set to `true`:

* `asciidoc.use_asciidoctor_js`: `true` -- you must be using asciidoctor.js (not asciidoctor CLI)
* `asciidoc.preview.scrollEditorWithPreview`: `true`  -- scroll editor with changes in preview
* `asciidoc.preview.scrollPreviewWithEditor`: `true` -- scroll preview with changes in editor 

There are a few limitations on this (for instance long tables don't work well).

If this doesn't help, are you able to provide a test document?

**Comment by Johan1974** [comment]
Is this also an option within visual studio code. If so where can i put this?

**Comment by danyill** [comment]
You can see these settings and others by opening the settings (on my machine I use Ctrl+Shift+P and go to Preferences: Open User Settings). Then I search the settings for Asciidoc and the settings associated with this extension (including those relevant to your question) are displayed.

See also: https://code.visualstudio.com/docs/getstarted/settings
