### ISSUE TITLE
Add support for VS Code for the Web

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/asciidoctor-vscode#464]
## Is your feature request related to a problem? Please describe

I can't install the extension on github.dev . Look:
![image](https://user-images.githubusercontent.com/48225759/136847476-9640ffc9-4cee-4abf-9ce1-8310af28f947.png)

## Describe the solution you'd like

I'd love to be able to install the extension so I can use it in a remote execution environment that runs VS Code webserver (e.g. github codespaces, github.dev, gitpod.io)

These things all use the open source vs code server https://github.com/gitpod-io/openvscode-server/ I believe.

## Describe alternatives you've considered

I tried to use the deprecated asciidoctor-vscode, but it doesn't actually appear to work. I can't get a preview for my adoc files.
![image](https://user-images.githubusercontent.com/48225759/136847666-9166faed-c1e8-410d-a56a-1dfd8b3a8fe3.png)

**Comment by Mogztter** [comment]
We are aware of this issue but as mentioned in https://github.com/asciidoctor/asciidoctor-vscode/issues/429, github.dev does not provide any additional information or guidance.
The extension is not available but we don't know what needs to be done to make it compatible/available.

>  I'll close this and maybe open an issue at github

Please do 👍🏻
