### ISSUE TITLE
Unpublish deprecated extensions

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-vscode#471]
I wonder if we should reach out to developers of deprecated extensions to ask them to unpublish:

- https://github.com/JustusAdam/language-asciidoc
- https://github.com/stayfool/vscode-asciidoc

I guess we could also unpublish the extension `joaompinto.asciidoctor-vscode`?

Procedure to unpublish: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#unpublishing-extensions

**Comment by apupier** [comment]
Unpublish of https://github.com/JustusAdam/language-asciidoc  has been done. https://github.com/JustusAdam/language-asciidoc/issues/9#issuecomment-953904070


https://github.com/JustusAdam/language-asciidoc/issues/9#issuecomment-953904070 readme has been updated. I asked to mark it  officially as deprecated and to redirect to this one https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-6215886

**Comment by apupier** [comment]
the `joaompinto.asciidoctor-vscode` is now marked as deprecated and will redirect to our extension:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/dc7c2823-46c0-4980-856a-129b0e47441c)

**Comment by ggrossetie** [comment]
> the joaompinto.asciidoctor-vscode is now marked as deprecated and will redirect to our extension:

Awesome, thanks 💪🏻
