### ISSUE TITLE
[Ubuntu 20.04; VS Codium] The extension either doesn't "see" or doesn't want to use a standalone executable of wkhtmltopdf

### ISSUE THREAD

**Issue by VanBrugg3n** [asciidoctor/asciidoctor-vscode#472]
## Description

The extension either doesn't "see" or doesn't want to use a standalone executable of `wkhtmltopdf`, despite an explicit path to it being set in settings.

If I save my file as `html` and then convert it to `pdf` using `wkhtmltopdf` directly from terminal, everything works fine. BTW it's the fastest workaround, if anyone reading this has the same problem.

## System Information

VSCodium Version: `1.61.2`
Commit: `6cba118ac49a1b88332f312a8f67186f7f3c1643`
Date: `2021-10-20T00:21:59.656Z`
Electron: `13.5.1`
Chrome: `91.0.4472.164`
Node.js: `14.16.0`
V8: `9.1.269.39-electron.0`
OS: `Linux x64 5.4.0-89-generic`
wkhtmltopdf Version: `0.12.6-1` (most up-to-date, available only as a `.deb` file [from the project's website.](https://wkhtmltopdf.org/downloads.html)

## Extension Settings

```json
{
    "asciidoc.use_kroki": true,
    "workbench.colorTheme": "Monokai Dimmed",
    "window.zoomLevel": 2,
    "editor.accessibilitySupport": "off",
    "editor.bracketPairColorization.enabled": true,
    "editor.dragAndDrop": false,
    "workbench.preferredDarkColorTheme": "Monokai Dimmed",
    "workbench.statusBar.visible": false,
    "asciidoc.preview.refreshInterval": 100,
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.useWorkspaceRoot": true,
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "asciidoc.preview.scrollPreviewWithEditor": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "workbench.enableExperiments": false,
    "workbench.settings.enableNaturalLanguageSearch": false,
    "update.showReleaseNotes": false,
    "telemetry.telemetryLevel": "off",
    "extensions.ignoreRecommendations": true,
    "asciidoc.wkhtmltopdf_path": "/usr/local/bin/wkhtmltopdf"
}
```

## To Reproduce

0. Use Ubuntu 20.04 or a distro based on it.
1. [Download the `.deb` file of wkhtmltopdf v0.12.6-1](https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb)
2. Run the `.deb` file.
3. Locate the installed `wkhtmltopdf` executable and move it to `/usr/local/bin/`.
4. In AsciiDoc Extension Settings, set `wkhtmltopdf_path` to `/usr/local/bin/wkhtmltopdf`.
5. Create a new `.adoc` file and set any first level title.
6. Open Command Pallete.
7. Select `AsciiDoc: Export document as PDF`.

## Screenshots & Files

![image](https://user-images.githubusercontent.com/44707064/139088038-6d3039e8-a3c5-4432-bf45-94a712c918f6.png)

**Comment by Zhou-Yicheng** [comment]
same problem
