### ISSUE TITLE
Preview of xref to figure in page no longer renders the auto generated labels

### ISSUE THREAD

**Issue by elsav-emrs** [asciidoctor/asciidoctor-vscode#477]
When you preview asciidoc pages in vscode, the auto generated labels of figures such as the following code are no longer rendered.

```
As shown in xref:fig_test[xrefstyle=short], blabla...

[[fig_test]]
.A title for my image
image::myimage.png[]
```

Preview is giving this

![image](https://user-images.githubusercontent.com/69378793/141966980-d58bb195-03e8-441b-acce-434e5f9cf4af.png)

This is a recent regression. Previously it was correctly rendered as: "As shown in Figure 1, blabla..."

Using Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by tim-elmer** [comment]
This also appears to affect generated HTML output. It also occurs when `reftext` is set explicitly on the block.

**Comment by jsieland** [comment]
Strangely when I first noticed this problem, none of my labels were rendered correctly.... some days later it suddenly disappeared and everything rendered correctly.... and today it happened again - but only for some labels (refs added today and appendix).

Version: 1.63.0 (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by r0ckarong** [comment]
Just stumbled on this in the latest version.

Version: 1.90.0 (system setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Name: AsciiDoc
Id: asciidoctor.asciidoctor-vscode
Description: Provides rich language support for AsciiDoc.
Version: 3.3.1
Publisher: asciidoctor
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode

**Comment by ggrossetie** [comment]
Probably related to https://github.com/asciidoctor/asciidoctor-vscode/pull/853

**Comment by r0ckarong** [comment]
Actually, I just realized I am seeing a different problem. I need to open another Issue.

**Comment by elsav-emrs** [comment]
The problem I had experienced a while ago is now fixed but as @r0ckarong described is now not supporting all cross-reference styles (https://docs.asciidoctor.org/asciidoc/latest/macros/xref-text-and-style/#cross-reference-styles). I am closing this issue as fixed. New issue is described in #889
