### ISSUE TITLE
Become a verified publisher in VSCode

### ISSUE THREAD

**Issue by Dominic-Preap** [asciidoctor/asciidoctor-vscode#486]
## Is your feature request related to a problem? Please describe

Just want to [verifying ownership](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher) from the publisher of VS Code.

![example](https://code.visualstudio.com/assets/api/working-with-extensions/publishing-extension/verified-publishers.png)

## Describe the solution you'd like

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Mogztter** [comment]
> Your request to verify the domain is submitted to the marketplace team for processing.

**Comment by Mogztter** [comment]
We are now verified! 🎉 

![image](https://user-images.githubusercontent.com/333276/152312021-71b74a4a-f317-43ac-9aa7-93490bfb9adf.png)
