### ISSUE TITLE
Missing bullets with mixed lists (check list entries and normal unordered entries)

### ISSUE THREAD

**Issue by maddes-b** [asciidoctor/asciidoctor-vscode#493]
## Description

If a mixed list with check and non check entries, then the preview is incorrect

## System Information

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
asciidoctor.asciidoctor-vscode v2.8.10

## To Reproduce

Create an asciidoc file, here test.adoc, with the following content:
```
= Test list

* [ ] check me
* [ ] check me 2
* nothing to check here
```

## Screenshots & Files

![image](https://user-images.githubusercontent.com/565223/151677405-3b43b5e9-10b3-4ca6-a4e3-7f6bf5d2d998.png)

**Comment by Mogztter** [comment]
What do you mean by incorrect? If you want checked and non-checked list then you need to use the following syntax:

```
* [x] Write the press release
* [ ] Update the website
* [ ] Contact the media
````

**Comment by maddes-b** [comment]
You are right that was ambiguously written.
So I checked the [docs][1] again and saw that the examples also show this "wrong" output.

I actually wanted a mix of normal and check list entries, where the normal list entries are displayed like usual with a bullet, square, etc.
In my use case I list the general definitions under each task, then listing the sub tasks. Sometimes following minor general information not related to any specific task.

The docs do no specify this as intended behavior (except by showing this in the example), nor giving a reason for this behavior.It may have a reason which I'm unable to see.
Although with "normal" behavior you could still achieve this by specifying [none], [no-bullet] or even [unstyled], which would allow for more flexible usage.
Also I could not find an option to toggle this behavior.
Can anybody give any insights or whom I should contact?

```
= Test list

* [x] checked list entry
** "working" normal list entry on 2nd level
* [ ] unchecked list entry
** "not working" normal list entry on 2nd level
** [ ] another unchecked list entry for a sub task
* another "not working" normal list entry
```
![image](https://user-images.githubusercontent.com/565223/151696615-5bfb670d-f219-4c4b-9e1a-787a54066619.png)

[1]: https://docs.asciidoctor.org/asciidoc/latest/lists/checklist/

P.S. Will later rename the issue, so that it better fits the "issue".

**Comment by Mogztter** [comment]
Please ask usage questions in the project chat at [asciidoctor.zulipchat.com](https://asciidoctor.zulipchat.com/). If we determine there that there is a bug in the processor, then we can proceed with an issue.
