### ISSUE TITLE
Table of contents not rendered in preview

### ISSUE THREAD

**Issue by dietbrand** [asciidoctor/asciidoctor-vscode#523]
## Description

When specifying :toc: auto and one ore more headings with ====, the table of contents is not rendered.

## System Information

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

## To Reproduce

Steps to reproduce the issue:

Start a new file
Save it as .adoc
Fill in the following content:
```

= Example asciidoc

:toc: auto
...

==== Title 1
==== Title 2

```
Use the preview function to render. No toc renders.  I have tried disabling all the other extensions and reloading.

**Comment by Mogztter** [comment]
@dietbrand which version of the extension are you using? Could you also take a screenshot of what you are seeing?
I cannot reproduce this bug using the latest version of the extension:

![image](https://user-images.githubusercontent.com/333276/155009087-85629324-998b-4527-8f6e-68b1276a57e0.png)

**Comment by dietbrand** [comment]
Dear Guillaume,

Thanks for your reply. I'm using the latest version available. Below is a screenshot.

![image](https://user-images.githubusercontent.com/5815621/155012788-dfce5ae1-f73e-4292-9d34-83804e894fc8.png)

**Comment by Mogztter** [comment]
Your syntax is incorrect, `:toc:` is a document attribute and must be defined as an attribute entry in the document header:

> The toc attribute is activated with an attribute entry in the document header.

https://docs.asciidoctor.org/asciidoc/latest/toc/

You should remove the empty line below the document title:

```
= Example asciidoc
:toc: auto

==== Title 1
==== Title 2
```

Not sure exactly why you are using thematic break in the preamble `'''` (https://docs.asciidoctor.org/asciidoc/latest/blocks/breaks/#thematic-breaks)

**Comment by dietbrand** [comment]
Dear Guillaume,

That's it! Removing the newline worked. Thanks for you help and your patience. Have a great day!
