### ISSUE TITLE
Can't easily type a colon at the end of a line

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [asciidoctor/asciidoctor-vscode#527]
## Description

When typing a colon, a completion list is displayed. When I want a colon att he end of a line, I usually press `:` then `return`, which types the first item of the completion list instead.

## System Information

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

## To Reproduce

Steps to reproduce the issue:

1. Type some text, for instance `Test`
2. Type a colon `:`
3. Type `return`

Expected output:
```
Test:

```
Actual output:
```
Test:app-name: any
```

Typing a colon in the  middle of a line is ok, because pressing space closes the completion list.

**Comment by Mogztter** [comment]
Hey!

The main issue is that `:` is a trigger character: https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features
`:app-name:` is declared as a [snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets) in:

https://github.com/asciidoctor/asciidoctor-vscode/blob/e15256254407d508aca84c3d6553d81d002f0ddc/snippets/snippets.json#L441-L445

This is probably a bad idea and we should instead declare a [CompletionItemProvider](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.CompletionItemProvider.html) where we could return all built-in attributes only if `:` was typed at the start of a line.
 
As a workaround, you can edit your `settings.json` and add:

```
"editor.suggestOnTriggerCharacters": false
```

Suggestion won't be triggered by `:` anymore (or any other characters). You will have to use `<Ctrl> + <Space>` to trigger suggestions.

Another workaround is to configure:

```
"editor.acceptSuggestionOnEnter": "off",
```

`<Enter>` won't accept the suggestion anymore, you will have to use `<Tab>` to accept a suggestion.
