### ISSUE TITLE
User setting asciidoc.asciidoctorpdf_command is ignored

### ISSUE THREAD

**Issue by meznom** [asciidoctor/asciidoctor-vscode#532]
## Description

The user setting `asciidoc.asciidoctorpdf_command` is ignored. 

## System Information

Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

## To Reproduce

Use the command palette to "Preferences: Open Settings (JSON)". Add or change an existing line to, e.g. 

```
"asciidoc.asciidoctorpdf_command": "does-not-exist"
```

With an AsciiDoc document open, use the command palette to "AsciiDoc: Export document as PDF".  I would expect to get an error, because "does-not-exist" cannot be executed -- but the export works just fine.

Similarly, if you set e.g.

```
"asciidoc.asciidoctorpdf_command": "asciidoctor-pdf --attribute pdf-stylesdir=C:\\Users\\Burkhard\\src\\documents\\tools\\asciidoctor\\themes"
```

this has no effect whatsoever.

## Additional Context

This is closely related to issue #472. 

It seems that this problem was introduced with PR #448, specifically a [change in exportAsPDF.ts](https://github.com/asciidoctor/asciidoctor-vscode/blob/cd477c734561e0b7c966fe62c9c193322dff9f7c/src/commands/exportAsPDF.ts#L46).

Unsuprisingly, if I use `asciidoc.asciidoctorPDFCommand` instead of `asciidoc.asciidoctorpdf_command` in `settings.json`, things work as expected.

**Comment by Mogztter** [comment]
Hey @meznom

Thanks for your report and good catch!
Feel free to submit a pull request, I will gladly merge it.
