### ISSUE TITLE
Show source action/command should not open a new pane if the source is already opened

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-vscode#549]
## Description

![noopen](https://user-images.githubusercontent.com/333276/158038163-68b042a2-d000-45e8-8926-fbef50332097.gif)

Instead, it should do what the Markdown extension is doing:

![focus-back](https://user-images.githubusercontent.com/333276/158038208-78eed559-c98e-4f8d-8417-d3c3a35eb7d4.gif)

Which is give the focus back to the editor.

**Comment by marieflorescontact** [comment]
👋
I can submit a pull request for this issue!
