### ISSUE TITLE
Question: Export to DocX possible

### ISSUE THREAD

**Issue by Johan1974** [asciidoctor/asciidoctor-vscode#551]
Hello,

Is there a way to export asciidoc to DocX (Word) ? 

Thanks!

Johan

**Comment by Mogztter** [comment]
You can take a look at: https://pandoc.org/
One way to do it, is to convert your AsciiDoc document to DocBook and then use pandoc to convert from DocBook to Docx.

https://rmoff.net/2020/04/16/converting-from-asciidoc-to-google-docs-and-ms-word/

**Comment by Johan1974** [comment]
Hello tried this one but it does not produce the same output as presented
in PDF or HTM with the asciidoc vscode app.

Are there any parameters i need to set to keep the same document layout.

Met vriendelijke groet / With Kind regards,

Johan Lijffijt
