### ISSUE TITLE
Add code folding on conditional preprocessor directives

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-vscode#552]
I would also like to fold [conditional preprocessor directives](https://docs.asciidoctor.org/asciidoc/latest/directives/conditionals/).

This would make a multi language document much more readable.

```
ifeval::["{lang}" == "de"]
Das ist mein Text.
Das ist mein Text.
Das ist mein Text.
Das ist mein Text.
endif::[]
ifeval::["{lang}" == "en"]
This is my text.
This is my text.
This is my text.
This is my text.
endif::[]
```

Maybe even a visual support to see where a directive starts and ends.
Like [CoenraadS.bracket-pair-colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer).

_Originally posted by @CWempe in https://github.com/asciidoctor/asciidoctor-vscode/issues/70#issuecomment-862753277_

Documentation: https://docs.asciidoctor.org/asciidoc/latest/directives/conditionals/

**Comment by marieflorescontact** [comment]
hello, I can submit a pull request for this issue
