### ISSUE TITLE
Add code folding on open blocks

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-vscode#553]
It would be nice to add code folding for panels too. This way if you have something like:

```
[example]
--
Large example
...
--
```

You could fold it to: 
```
[example]
-- ···
```
(dots are added by VSCode on folding)

Thanks for your work!

_Originally posted by @andresbm05 in https://github.com/asciidoctor/asciidoctor-vscode/issues/70#issuecomment-472747318_

Documentation: https://docs.asciidoctor.org/asciidoc/latest/blocks/open-blocks/

**Comment by marieflorescontact** [comment]
:wave: I can submit a pull request for this issue!
