### ISSUE TITLE
Image pasting filename issues

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#576]
At some stage I think we have changed the way in which pasting images from the clipboard into this extension works:

If no name is provided, the image is named based on a date/time stamp, in the form:

```asciidoc
image:2022-06-21T18-26%3A48-770Z.png[]
```

On Windows, the `%` character is allowed in filenames but is reserved and at least in the preview is not showing correctly on Windows. This may also be associated with the preview provider. `%3A` is the URL encoding of the `:` symbol.

Some possibly relevant information here:

https://superuser.com/questions/1096208/in-windows-explorer-why-can-we-create-a-folder-or-file-with-the-percent-sym

The easiest solution may be simply to replace the % with an underscore or change the timestamp representation.

**Comment by danyill** [comment]
Thanks!

**Comment by edl7878** [comment]
Awesome！

Wait for the new version.

For now, each image pastes, I would have to delete the "%",  and rename the image.
