### ISSUE TITLE
Support for font awesome icons broken in web

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#585]
On the current master, setting 

```
:icons: font
```

does not appear to work in the VS Code web preview:

The developer tools contains an error associated with this:

```
Failed to load resource: the server responded with a status of 404 () https://file+.vscode-resource.vscode-cdn.net/images/icons/tip.png
```

## To Reproduce

Steps to reproduce the issue:

1. Press `.` on this repository
2. Open `CONTRIBUTING.adoc`
3. Set `:icons: font` in the document header
4. Observe the icon is present for the admonition.
    ![image](https://user-images.githubusercontent.com/674783/175806857-c8989e50-89f8-4b7d-ae6f-fa8426d02f12.png)

5. Repeat test on current master (as per `CONTRIBUTING.adoc` instructions).
6. Observe the icon is not present.

I'm not sure if this has been caused by a recent code change or is because the VS Code Web preview is not representative of what would occur in production.

**Comment by Mogztter** [comment]
> https://file+.vscode-resource.vscode-cdn.net/images/icons/tip.png

According to the error message, it tries to use images not FontAwesome. I will investigate.

**Comment by Mogztter** [comment]
I think it's working but the CSP blocks resources in development:

![image](https://user-images.githubusercontent.com/333276/175820454-0a8bfbdb-0a40-4cbf-ad65-471d2fb7bea7.png)

In development, resources will be served using `http://localhost:3000/static/devextensions` whereas in production they will use `https://*.vscode-cdn.net`

```
Refused to load the stylesheet 'http://localhost:3000/static/devextensions/media/font-awesome/css/font-awesome.css' because it violates the following Content Security Policy directive: "style-src 'self' https://*.vscode-cdn.net 'unsafe-inline' https: data:". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

We might be able to detect that we are running in development to automatically authorize `http://localhost:3000/static/devextensions`.

**Comment by danyill** [comment]
OK, thanks for looking into it.
