### ISSUE TITLE
Message Preview error in developer webview console

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#599]
## Description

In the 3.0.0 prelease release I notice a console log error: `Message Preview {0} didn't get externalized correctly.

## System Information

    Version: 1.68.1 (user setup)
    Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
    Date: 2022-06-14T12:48:58.283Z
    Electron: 17.4.7
    Chromium: 98.0.4758.141
    Node.js: 16.13.0
    V8: 9.8.177.13-electron.0
    OS: Windows_NT x64 10.0.19044

## To Reproduce

Steps to reproduce the issue:

1. Create any document, e.g.

   ```asciidoc
   = Test
   
   d
   ````

2. Load the preview and modify the document.

3. Look at the developer tools web console. With a preview open the error message count increases for each preview refresh.

**Comment by Mogztter** [comment]
It has been fixed in #594 (hopefully)
