### ISSUE TITLE
Web extension not installable

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#600]
## Description

Installing either 2.9.8 or installing the 3.0.0 pre-release version doesn't seem to work for the "web version".

## System Information

I'm using Chrome in a managed environment on Windows 10:

   Automatic updates are enabled. Manual updates are disabled by your administrator.
   Version 103.0.5060.114 (Official Build) (64-bit)

I'll try to check this on both Chrome and Firefox in a Linux environment also.

## To Reproduce

Steps to reproduce the issue:

1. Press `.` on a repository like this one.
2. Click on Extensions, search for Asciidoc
3. Try to install this extension.
4. Notice error message

## Screenshots & Files

I tried to install using either of the options shown:

![image](https://user-images.githubusercontent.com/674783/177919960-d48011d1-1962-4fc9-8f86-d882114b905d.png)

Note in the lower right corner an error message:

![image](https://user-images.githubusercontent.com/674783/177919395-43c4a1d0-e2e2-4425-9354-44f20d31ca6e.png)

**Comment by Mogztter** [comment]
Probably related: https://github.com/microsoft/vscode-nls/commit/e3f36f5026867758173405adb4800ebc02eef631
However, I'm not sure if the `options?.locale` should be defined or not in a Web environment.

**Comment by Mogztter** [comment]
In the meantime, we should probably set locale to `en-US` in:

https://github.com/asciidoctor/asciidoctor-vscode/blob/a69e4c90c74b9cd854bd3c811f71257ab29f6bef/src/i18n.ts#L4
