### ISSUE TITLE
Full-window preview completely refreshes when switching tabs, losing scroll position

### ISSUE THREAD

**Issue by rben01** [asciidoctor/asciidoctor-vscode#603]
## Description

After running the `AsciiDoc: Preview` command, you get a full-window preview in the same editor group as the current adoc file. If you switch tabs between the adoc and the preview, the preview refreshes and loses its scroll position. Ideally it would remain open in the background and maintain its scroll position.

## System Information

VSCode: Version: 1.69.0
macOS: 12.5
AsciiDoc extension: v3.0.0 (but this also occurs on the release version)

## To Reproduce

Non-default settings:

```json
"asciidoc.preview.scrollEditorWithPreview": false,
"asciidoc.preview.scrollPreviewWithEditor": false,
"asciidoc.preview.doubleClickToSwitchToEditor": false,
"asciidoc.preview.useEditorStyle": false,
"asciidoc.preview.refreshInterval": 0,
```

Steps to reproduce the issue:

1. Create a new AsciiDoc file and fill it up with text
1. Run the `AsciiDoc: Preview` command to open a preview in the same editor group
1. Scroll to the bottom of the preview window
1. Switch back to adoc file
1. Switch back to preview window

Bug: the preview window refreshes and in doing so loses the scroll position.

## Screenshots & Files

https://user-images.githubusercontent.com/766670/178031621-e0e2c70c-989d-4b31-81ec-755131abb2ff.mp4

**Comment by rben01** [comment]
Actually, this affects the side preview as well if you switch between it and another editor. Any time you hide the Asciidoctor preview window, when you bring it back again it will completely refresh.

**Comment by Mogztter** [comment]
You should get the same behavior using the built-in Markdown extension. The preview window is disposed (to free-up resources), that's why it gets refreshed. Having said that, we do have a mechanism in place to store and restore a state. So, technically, we could save the scroll position and restore it.

Or maybe we should initialize the preview with the scroll position.
