### ISSUE TITLE
resolve include file suggestions relative to document

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-vscode#623]
## Description

autocomplete suggestions for include:: are currently resolved against the workspace root:

https://github.com/asciidoctor/asciidoctor-vscode/blob/b65f1c171ce828e71f784cfdf8c5f2bc6e429f66/src/providers/asciidoc.provider.ts#L53-L58

this works as long as all asciidoc files live in the root of the workspace. as soon as we place them in a subfolder, it is broken

## Additional Context

I created a PR https://github.com/asciidoctor/asciidoctor-vscode/pull/618 that suggests resolving the files relative to the source document.

https://github.com/asciidoctor/asciidoctor-vscode/pull/618/files#diff-fb3632b9c41b259ca81bd1f9be15c3b88bd68efe5d88727117468c79e50fd720R53-R56

**Comment by Mogztter** [comment]
fixed in #618
