### ISSUE TITLE
Create a language server for AsciiDoc

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-vscode#625]
Take inspiration from https://code.visualstudio.com/updates/v1_70#_markdown-language-server

**Comment by FernandoBasso** [comment]
Here's also link to a post by the author of the markdown language server where they mention the reasoning behind it:

- https://code.visualstudio.com/blogs/2022/08/16/markdown-language-server

**Comment by ggrossetie** [comment]
Superseded: https://github.com/asciidoctor/asciidoctor-vscode/issues/686
