### ISSUE TITLE
Add link to Zulip for Asciidoctor to issue templates

### ISSUE THREAD

**Issue by sturtison** [asciidoctor/asciidoctor-vscode#631]
## Is your feature request related to a problem? Please describe

When asking questions about getting something to work, it is not always obvious depending on the arrival path if the open source project has an information discussion channel or not, and would like to know before asking the issue on GitHub.

This may help get more support questions answered faster and let the repo maintainer deal with more focused application related issues.

When the issue templates were first set up, zulipchat was not being used.

## Describe the solution you'd like

That the GitHub issue templates direct issue raisers to the more informal community chat to discuss their issue first according to some criteria. For example, to https://asciidoctor.zulipchat.com/

## Suggested text and options

Add the following text to the existing [templates](https://github.com/asciidoctor/asciidoctor-vscode/tree/master/.github/ISSUE_TEMPLATE):

Please consider joining the community chat and support forum at https://asciidoctor.zulipchat.com/ and asking support related questions there as we don't use the GitHub issue tracker as a support forum.

Configure the [template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) to remove "Create blank issue" as an option.

**Comment by Mogztter** [comment]
That's a good idea.
I've updated the issue templates and added the project chat:

![image](https://user-images.githubusercontent.com/333276/188439638-b50d20fb-875d-4526-95b3-77f3ae905b89.png)
