### ISSUE TITLE
Editor and Preview are not linked when using native asciidoctor

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-vscode#632]
## Description
When using native asciidoctor the preview does not link with the editor (as it does when using asciidoctor.js)

## To Reproduce
i used the following settings:

```
"asciidoc.use_kroki": false,
"asciidoc.use_asciidoctor_js": false,
"asciidoc.asciidoctor_command": "asciidoctor -r asciidoctor-diagram -r rouge ",
"asciidoc.preview.attributes":{
        "source-highlighter":"rouge",
        // "source-linenums-option":"true",
        "rouge-style": "github"

},
"asciidoc.preview.scrollPreviewWithEditor": true,
"asciidoc.preview.scrollEditorWithPreview": true,

```

**Comment by Mogztter** [comment]
That's expected and part of the reason why the Asciidoctor CLI was dropped in version 3.x: https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v3.0.0
