### ISSUE TITLE
Workspace extensions not working on Windows

### ISSUE THREAD

**Issue by jens-auer** [asciidoctor/asciidoctor-vscode#650]
I am trying to setup extension support by putting an extension in ./asciidoctor/lib on a Windows system. As a first test, I followed the example in the documentation:
1. Switch to Prerelease version
2. Enable extensions with
`"asciidoc.extensions.registerWorkspaceExtensions": true`
4. create an empty folder a
5. In a, `npm i asciidoctor-emoji`
6. Create a file a/asciidoctor/lib/emoji.js with 
`module.exports = require('asciidoctor-emoji')`
8. create a emoji.adoc with content
```
= Emoji
:nofoooter:

Asciidoc emoji:heart[] VS Code

````
9. reload project and open preview

This opens a preview where the macro is not processed, and I get an error.
![image](https://user-images.githubusercontent.com/9391718/198253867-ee6b0acb-8a6a-4999-b05e-01eb2f5355ba.png)

```
/c:/Users/JAuer/SWP-Updt/a/.asciidoctor/lib/emoji.js: Error: Cannot find module '/c:/Users/JAuer/SWP-Updt/a/.asciidoctor/lib/emoji.js'
Require stack:
- c:\Users\JAuer\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.0.1\dist\src\asciidocParser.js
- c:\Users\JAuer\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.0.1\dist\src\image-paste.js
- c:\Users\JAuer\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.0.1\dist\src\commands\pasteImage.js
- c:\Users\JAuer\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.0.1\dist\src\commands\index.js
- c:\Users\JAuer\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.0.1\dist\src\extension.js
- c:\Users\JAuer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\JAuer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\JAuer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
```

The emoji.js is at the expected position in the file system:
```
C:\Users\JAuer\SWP-Updt\a>tree /F
Folder PATH listing
Volume serial number is 188A-9A08
C:.
│   emoji.adoc
│   package-lock.json
│   package.json
│
├───.asciidoctor
│   └───lib
│           emoji.js
│
└
```

**Comment by Mogztter** [comment]
It was fixed in https://github.com/asciidoctor/asciidoctor-vscode/commit/3025b897c165dabc5c102132ba38e4329873d82b which will be part of the next release.

Original issue: https://github.com/asciidoctor/asciidoctor-vscode/issues/629

**Comment by jens-auer** [comment]
Is it part of the prerelease already? I tried that and had the same problem.

**Comment by Mogztter** [comment]
No, this fix is not yet released
