### ISSUE TITLE
no more highlighjs rendered with latest 3.0.2

### ISSUE THREAD

**Issue by jseguillon** [asciidoctor/asciidoctor-vscode#664]
Noticed I have no more highlight working after 3.0.2 upgrade. Reverted to 3.0.1 and got highlight working again. 

![3.0.1](https://user-images.githubusercontent.com/1395266/202029947-eee46fe7-268f-425c-bae2-ef76899ea0f1.png)
![3.0.2](https://user-images.githubusercontent.com/1395266/202030104-a3ed5be8-a7f7-4593-a861-ba60dc846a48.png)

```
:source-highlighter: highlight.js

= test

== example

[,json]
-------
{
    "changed": true,
}
-------
```

![about](https://user-images.githubusercontent.com/1395266/202030336-53b6e8d2-7656-456c-a327-f1d993c667bb.png)

**Comment by Mogztter** [comment]
I can reproduce this issue 😬

**Comment by jseguillon** [comment]
Great you could easily reproduce and thanks for the fix ! 

Would diverse an "emergency" pre-release fix I'm afraid. Could you consider a 3.0.3 or 3.0.2.1  @Mogztter  ?

**Comment by Mogztter** [comment]
Yes I will publish a hotfix as soon as possible but first I want to fix https://github.com/asciidoctor/asciidoctor-vscode/issues/665

**Comment by jseguillon** [comment]
Thank you so much !! I tested 3.0.3 : works like a charm!
