### ISSUE TITLE
.asciidoctorconfig passed to preprocessor instead of actual document contents

### ISSUE THREAD

**Issue by jacdavi** [asciidoctor/asciidoctor-vscode#679]
## Details:

* I've written a custom extension that functions as a preprocessor to replace some text
* I have an `.asciidoctorconfig` file in my directory.
* When printing out the lines received by the preprocessor, it appears to get the contents of the config file
* Deleting the config file causes the correct lines to be passed to the preprocessor

See the example below. The preprocessor writes the lines it receives to `~/test.txt`. You'll also see the preprocessor tries to set the lines to `["TEST"]` which results in `TEST` being prepended to the output document (since I assume the config gets prepended and is now replaced)

[asciidoc-min-example.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/10273586/asciidoc-min-example.zip)

Preprocessor.js:

```js
const fs = require('fs');

function incontextPreprocessor() {
    const self = this

    self.process(function (doc, reader) {
        var lines = reader.getLines()
        fs.writeFileSync('test.txt', JSON.stringify(lines, null, 2));
        reader.lines = ["TEST"]
        return reader
    })
}

module.exports.register = function register(registry) {
    if (typeof registry.register === 'function') {
        registry.register(function () {
            this.preprocessor(incontextPreprocessor)
        })
    } else if (typeof registry.block === 'function') {
        registry.preprocessor(incontextPreprocessor)
    }
    return registry
}
```

`*.adoc` and `.asciidoctorconfig` files don't really matter, can be anything.

## VS Code Version:
```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 4.18.0-193.el8.x86_64
Sandboxed: No
```

**Comment by Mogztter** [comment]
I think you should use `prefer()` to make sure that your extension runs first:

```js
function incontextPreprocessor() {
    const self = this

    self.prefer() // insert the processor as the first processor

    self.process(function (doc, reader) {
        var lines = reader.getLines()
        fs.writeFileSync('test.txt', JSON.stringify(lines, null, 2))
        reader.lines = ["TEST"]
        return reader
    })
}
```

We are indeed using a Preprocessor to include the `.asciidoctorconfig` content:

https://github.com/asciidoctor/asciidoctor-vscode/blob/be5055d2f5f314c865f0b6cd597d2714e0802f4c/src/asciidocParser.ts#L38

**Comment by jacdavi** [comment]
Thanks, that does seem to fix it!

It does seem odd to me that without the `self.prefer()` the preprocessor only got passed the contents of the `asciidoctorconfig` file. I would have thought it would get the entire `.adoc` file with `.asciidoctorconfig` already prepended.

**Comment by Mogztter** [comment]
We might need to return the `reader`... 🤔
Is that correct @mojavelinux ?

**Comment by mojavelinux** [comment]
No, the issue is that `getLines()` is not how you read lines from the reader. All that does is give you a copy of the remaining lines that are currently in context, which is the .asciidoctorconfig include. If you want to actually read the lines as they are processed, then you'd need to use `readLines()`. These too methods are very different.

**Comment by jacdavi** [comment]
Thanks @mojavelinux ! That works and makes sense. Should've noticed that the ruby and java extensions I've written use `read` as opposed to `get`.

**Comment by Mogztter** [comment]
> No, the issue is that getLines() is not how you read lines from the reader. All that does is give you a copy of the remaining lines that are currently in context, which is the .asciidoctorconfig include.

Thanks for clarifying. I thought `getLines` would return a copy of all the remaining lines (so `.asciidoctorconfig` include + the whole document).

**Comment by mojavelinux** [comment]
> all the remaining lines

All the remaining lines of the current entry in the stack, without doing any processing. `readLines()` returns all remaining lines on all stacks...and processes them too.
