### ISSUE TITLE
Things which is not working in v3.0.3 pre-release

### ISSUE THREAD

**Issue by AshkanV** [asciidoctor/asciidoctor-vscode#681]
Hello
Thank you for this great extension
I am trying to get prepared for the upcoming version 3 and adopt my workflow. As I am using this extension for all of my documentations.

These are the features which are not working on version 3.0.3:

1. The parameters in `asciidoctorAttributes` is not used for the final HTML export and only used in preview. But if I include theme in the Asciidoc document itself, it will be OK in the final HTML export. I think if someone needs an attribute for previewing, he/she will also needs it for the final export.
2. The Kroki diagrams is not embeded in the HTML output and only a link to the image is generated which always requires the server. I use this combination:
```
    :data-uri:
    :allow-uri-read:
    :kroki-default-format: svg
    :kroki-default-options: interactive
    :kroki-fetch-diagram!: 
```
if I remove the `!` char from `kroki-fetch-diagram` or use `inline` instead of `interactive` there will be no diagram at all.

Thank you all

**Comment by Mogztter** [comment]
Thanks for testing the pre-release version.
Could you please create one issue per item? It's easier to track progress and keep the discussion on track. Thanks!

**Comment by AshkanV** [comment]
Sure, I have created 2 separate issues (#682, #683) for this matter.

**Comment by Mogztter** [comment]
Thanks!
