### ISSUE TITLE
asciidoctorAttributes not used for HTML export in v3.0.3

### ISSUE THREAD

**Issue by AshkanV** [asciidoctor/asciidoctor-vscode#682]
The attributes set in `asciidoctorAttributes` are not used for the HTML export (`Save HTML document` from command palette).

VSCode: 1.74 (tar.gz version)
AsciiDoctor VSCode: 3.0.3
OS: Linux openSUSE 15.4

(This bug report is created to make a separate issue for each item in #681)

**Comment by Mogztter** [comment]
My idea was to separate attributes used in the preview and used in the export.
The setting `asciidoctorAttributes` is defined in the "Preview" section.

We could introduce a checkbox in the "common" section to use the same attributes in the export. And/or introduce an export section where we could configure attributes.

**Comment by ggrossetie** [comment]
We might also recommend using `.asciidoctorconfig`.

@ahus1 Have you considered a "profile" to use a different set of attributes when exporting to PDF or when exporting to HTML or when using the preview?

**Comment by ahus1** [comment]
@ggrossetie - I haven't considered different profiles in my projects; so far all projects have been using the same attributes. 

When people want to differentiate between different environments, they could use `env` or `backend` attribute and `ifdef`/`ifndef`. WDYT? I'd assume the setting would mostly be the same, only some minor differences in HTML vs. PDF.

**Comment by ggrossetie** [comment]
> When people want to differentiate between different environments, they could use env or backend attribute and ifdef/ifndef. WDYT? I'd assume the setting would mostly be the same, only some minor differences in HTML vs. PDF.

That's a good point 👍🏻 


> We could introduce a checkbox in the "common" section to use the same attributes in the export. And/or introduce an export section where we could configure attributes.

Might be better to have:
1. global attributes
2. HTML preview attributes
3. PDF export attributes
4. HTML export attributes

**Comment by ggrossetie** [comment]
I've decided to not introduce additional configuration options. Instead, Asciidoctor attributes should be defined in an `.asciidoctorconfig` file.
This file will be used in the preview and when export to HTML and PDF.

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/333276/d858d526-cd43-41b2-89da-8ea4898182f8)
