### ISSUE TITLE
VSC: Failed to load AsciiDoc document

### ISSUE THREAD

**Issue by sberequek** [asciidoctor/asciidoctor-vscode#684]
When composing the document I keep getting the error visible in the screenshot:

<img width="1693" alt="screen_1" src="https://user-images.githubusercontent.com/31727791/210758898-23a2fdc1-fe54-4149-aa14-8c2caf03c719.png">

The preview is empty :(

Here is my environment:
- MacOS: 13.1
- AsciiDoc Extension: 2.9.8
- VSC:
      - Version: 1.74.2
      - Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
      - Date: 2022-12-20T10:26:09.430Z
      - Electron: 19.1.8
      - Chromium: 102.0.5005.167
      - Node.js: 16.14.2
      - V8: 10.2.154.15-electron.0
      - OS: Darwin x64 22.2.0
      - Sandboxed: No

Thanks!

**Comment by Mogztter** [comment]
I think this is the same issue: https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/VSCODE.20.22Preview.20to.20the.20side.22.20not.20working

**Comment by sberequek** [comment]
Great, that fixed it, thanks a lot @Mogztter
