### ISSUE TITLE
Collapsible Sections

### ISSUE THREAD

**Issue by hybras** [asciidoctor/asciidoctor-vscode#687]
VS Code has collapsible sections and code block for markdown. This is analogous to the ability to collapse blocks in most programmings languages (like conditionals, loops, function definitions, classes, etc). I've attached a screenshot. The collapse buttons are available in the gutter.

This is very convenient when viewing large files or those with many sections and for help focusing attention on a single section.

<img width="172" alt="Screenshot 2023-01-10 at 7 00 02 PM" src="https://user-images.githubusercontent.com/24651269/211687599-8b2b0201-74dc-49b8-9e09-82cb7a6b5aac.png">

I assume vs code has an api for denoting that a subset of a file, or a subrange of lines, refers to a block and can be collapsed.

**Comment by Mogztter** [comment]
This was implemented and released in version 3.0.0 (pre-release): https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v3.0.0

Please give it a try!

**Comment by hybras** [comment]
Oh that's beautiful, looking forward to when v3 is released.
