### ISSUE TITLE
3.0.3 preview - asciidoctor-pdf export not picking up theme

### ISSUE THREAD

**Issue by SjoerdV** [asciidoctor/asciidoctor-vscode#703]
After upgrading from 2.9.8 to 3.0.3

Exporting to pdf using asciidoctor-pdf is not picking up the theme anymore. Includes, images and icons do work correctly.
* note: theme settings are loaded through an external include file from the main document

my config: https://github.com/asciidoctor/asciidoctor-vscode/issues/700#issuecomment-1426797834

VSCode: 1.75.1
AsciiDoctor VSCode: 3.0.3
Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.18
OS: Linux LMDE 5

Some guidance is needed.

**Comment by ggrossetie** [comment]
I cannot reproduce this issue using:

![image](https://user-images.githubusercontent.com/333276/218323261-7294a7d6-e335-455c-8ee3-be3213291574.png)

**Comment by ggrossetie** [comment]
Please note that `pdf-themesdir` is relative to the working directory (i.e., workspace folder) not relative to the document:

> If the path is relative, the value is resolved starting from the current working directory.

https://docs.asciidoctor.org/pdf-converter/latest/theme/apply-theme/

**Comment by SjoerdV** [comment]
OK, thanks for pointing me in the right direction

So this constitutes a breaking change with the transition from 2.9.8 to 3.0.3

original pdftheme settings were (which was working fine in 2.9.8) with a `{parent-path}` fed from the main document
```
:pdf-themesdir: {parent-path}resources/themes
:pdf-theme: my
:pdf-fontsdir: {parent-path}resources/fonts,GEM_FONTS_DIR
```
now with 3.0.3 it has to be
```
:pdf-themesdir: resources/themes
:pdf-theme: my
:pdf-fontsdir: resources/fonts
```

As a sidenote, I also had which works fine in both 2.9.8 and 3.0.3
```
:imagesdir: {parent-path}resources/media
```
Just to check I removed the `{parent-path}` part and this also worked in 3.0.3 (did not 2.9.8)
```
:imagesdir: resources/media
```

I think we can close this one

**Comment by ggrossetie** [comment]
I will leave this issue open as a reminder to update the CHANGELOG/Documentation.
