### ISSUE TITLE
3.0.3 preview - TOC is inserted into the title header in preview style

### ISSUE THREAD

**Issue by SjoerdV** [asciidoctor/asciidoctor-vscode#704]
After upgrading from 2.9.8 to 3.0.3

After fixing loading styles for the preview: https://github.com/asciidoctor/asciidoctor-vscode/issues/702, a (for me 'duplicate')  TOC  is now inserted into the title header.

my 2.9.8 config: https://github.com/asciidoctor/asciidoctor-vscode/issues/700#issuecomment-1426797834 (TOC settings are in an external include file)
my 3.0.3 config: https://github.com/asciidoctor/asciidoctor-vscode/issues/702#issuecomment-1427186096

VSCode: 1.75.1
AsciiDoctor VSCode: 3.0.3
Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.18
OS: Linux LMDE 5

* How to fix the TOC not being inserted in the header in the preview. I already have the TOC already inserted in another place in the main document with `toc::[]` directive.
* This extra TOC is not present when exporting to pdf with asciidoctor-pdf

**Comment by ggrossetie** [comment]
@SjoerdV can you please share a screenshot?

> How to fix the TOC not being inserted in the header in the preview. I already have the TOC already inserted in another place in the main document with toc::[] directive.

Did you set `:toc: macro`?

**Comment by SjoerdV** [comment]
> Did you set `:toc: macro`?

Yes, it's in the external 'include' settings file. I have added the TOC settings to my shared config above.

Just to make sure: 3.0.3 isn't calling `asciidoctor -a toc` by any chance?
https://docs.asciidoctor.org/asciidoc/latest/toc/#activate-the-toc-from-the-cli

**Comment by SjoerdV** [comment]
OK, this is really weird, the extra TOC (the one in the title header) is only present in the vscode preview window but when I choose 'Save HTML Document' or 'Export Document as PDF' there is only the TOC I defined.

Just a note, when saving as HTML, my custom stylesheet is not included, so I have to add this manually to the file (I found no setting to do that automatically in 3.0.3) is that correct?

**Comment by ggrossetie** [comment]
> Just a note, when saving as HTML, my custom stylesheet is not included, so I have to add this manually to the file (I found no setting to do that automatically in 3.0.3) is that correct?

Yes and no.
The preview uses its own stylesheet (you configure it using `asciidoc.preview.style` setting). The export is using the built-in AsciiDoc attributes (styledir, stylesheet...).

Currently, you cannot configure export attributes, see https://github.com/asciidoctor/asciidoctor-vscode/issues/682

With the benefit of hindsight, we should probably mention that in the CHANGELOG and provide explanation on how to use the exact same stylesheet on the HTML preview and export.

**Comment by SjoerdV** [comment]
I've updated my config https://github.com/asciidoctor/asciidoctor-vscode/issues/700#issuecomment-1426797834 so that `styledir` and `stylesheet` are included again in the `default_settings.adoc` file. This will make sure the HTML export does its thing.

Were you able to get some intel on the ToC issue?

I did found a workaround that works for me (inspired by [this code block ](https://github.com/asciidoctor/asciidoctor/blob/8b67f4ec2deba9b2beff832e42460b44829e5d6f/lib/asciidoctor/converter/html5.rb#L191-L224))

Adding this to my css prevents the unwanted ToC from showing up in the preview, while allowing my self placed toc to be visible
```
#header #toc { display: none; }
```
tested this with both PDF and HTML export options and all good.

**Comment by ggrossetie** [comment]
I can reproduce this bug 👍🏻
