### ISSUE TITLE
Register extension fails with TypeError: extjs.register is not a function

### ISSUE THREAD

**Issue by jens-auer** [asciidoctor/asciidoctor-vscode#708]
I am trying to use custom extensions automatically with the register extensions feature. This fails with an error:

`Production\Documents\test\.asciidoctor\lib\lorem.js: TypeError: extjs.register is not a function`

I tested this with a simple project using the lorem extensions.
[test.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/10981257/test.zip)

It has one adoc file with
`lorem::sentences[size=2]`

and the macro in .asciidoctor/lib.
```
// NOTE: Below we are using a minimalist implementation to generate lorem ipsum text.
// If you need a complete implementation, you can use the following Node package:
// var lorem = require('lorem-ipsum')

var dictionary = {
    words: [
      'lorem',
      'ipsum',
      'dolor',
      'sit',
      'amet'
    ]
  }
  
  function getRandomArbitrary (min, max) {
    return Math.random() * (max - min) + min
  }
  
  function lorem (opts) {
    var count = opts.count
    var units = opts.units
    var words = dictionary.words
    if (units === 'sentences') {
      var sentences = []
      var sentence = []
      for (i = 0; i < count; i++) {
        var sentenceLength = getRandomArbitrary(5, 15)
        for (j = 0; j < sentenceLength; j++) {
          // use predictive position for testing purpose
          var position = j % words.length
          // var position = Math.floor(Math.random() * words.length)
          var word = dictionary.words[position]
          if (j === 0) {
            // capitalize the first letter
            word = word.charAt(0).toUpperCase() + word.slice(1)
          }
          sentence.push(word)
        }
        sentence[sentence.length - 1] += '.'
        sentences.push(sentence.join(' '))
      }
      return sentences.join(' ')
    }
  }
  
  module.exports = function (registry) {
    registry.blockMacro(function () {
      var self = this
      self.named('lorem')
      self.process(function (parent, target, attrs) {
        var size = parseInt(attrs.size)
        var result = lorem({ count: size, units: target })
        return self.createBlock(parent, 'paragraph', result)
      })
    })
  }
```

**Comment by jens-auer** [comment]
Forget it, stupid copy & paste problem sitting in front of the screen.

**Comment by bryan-nice** [comment]
what do you mean copy & paste, this seems to be a bug with the VS Code asciidoctor extension. I am getting the exact same error as yours.

**Comment by bryan-nice** [comment]
Ok, I found the issue. Y'all really need to take time and do a lot better with your documentation. The issue is your document is incorrect on the examples. Instead of `module.exports` it needs to be `module.exports.register` to have asciidoctor.js VSCode extension recognizing a custom extension correctly.

Seriously, asciidoctor is a nice idea, but too bad you can't trust the documentation to help you use if effectively. I hope either this community matures to fix it, or someone else should lead it that will ensure better quality expectations are set. Forums and asking questions is not documentation.

**Comment by ggrossetie** [comment]
Be the change that you want to see in the world.

This is an open source project maintained by volunteers. Feel free to open a pull request and improve the documentation.

**Comment by ggrossetie** [comment]
@bryan-nice For reference, the documentation is correct.

The `asciidoctor-emoji` extension exports a `register` function: https://github.com/ggrossetie/asciidoctor-emoji/blob/7a3c8caf5b20b833580f816ed95f8b2d583c0549/src/asciidoctor-emoji.js#L38

So, `module.exports = require('asciidoctor-emoji')` is correct and working as intended.
