### ISSUE TITLE
Export pdf does not pass workspace directory when "Workspace Root As Base Directory" is selected in settings

### ISSUE THREAD

**Issue by jens-auer** [asciidoctor/asciidoctor-vscode#716]
I want to export an adoc file that is included in my root document as pdf via Asciidoc: Export document as PDF, but it does not resolve includes correctly. I think it does not pass the correct basedir with -B. I selected "Workspace Root As Base Directory" in the plugin settings

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/9391718/b4f9e4d1-d829-4874-807a-5a78d1559402)

My workspace root is /home/jens/SWP-Updt/sysad/030_design, but the command uses a nested path with the adoc file I wanted to export.

but the command that seems to be executed when exporting a pdf is 
`Unable to generate a PDF using asciidoctor-pdf: Error: command failed: asciidoctor-pdf -q -B "/home/jens/SWP-Updt/sysad/030_design/safety" -o "/home/jens/SWP-Updt/sysad/030_design/safety/tsc.pdf" -n, -a, imagesdir=./media `

so it uses the path to the exported adoc file instead of the workspace root.

**Comment by ggrossetie** [comment]
Could you please add your system information and the extension version?

> We'll also need your system information (get it under "Help" -> "About" in VS Code). Share the installed extension version (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> or <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> on macOS).

**Comment by jens-auer** [comment]
```
Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

I'm using the prerelease version of the plugin
![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/9391718/d2b6438b-b811-439c-872c-b7b9a35ae101)

**Comment by ggrossetie** [comment]
Thanks!
So you are already using the latest (pre-version).

> My workspace root is /home/jens/SWP-Updt/sysad/030_design
> OS: Windows_NT x64 10.0.19045

Are you using WSL2?

**Comment by jens-auer** [comment]
Yes, its WSL2.

**Comment by ggrossetie** [comment]
Got it, thanks!
I can reproduce this bug 🐞
