### ISSUE TITLE
Don't warn about "list item index: expected x, got y" when `[start=y]` is set

### ISSUE THREAD

**Issue by bnoctis** [asciidoctor/asciidoctor-vscode#718]
## What you are trying to do

Write an ordered list that maintains numbering through several section headings, like this:

```asciidoc
==== Section 2.1

1. One
2. Two
3. Three

==== Section 2.2

[start=4]
4. Four
5. Five
6. Six
```

## What happened

<img width="414" alt="image" src="https://github.com/asciidoctor/asciidoctor-vscode/assets/4474501/305a4dcb-f38a-4f36-977c-5bf8bb3ec67c">

## What you expected to happen

Respect the `start` header and silence this warning.

I'm able to find this warning text in the extension's `node_modules/@asciidoctor/core`, but not in asciidoctor.js source code.

## System information

VSCodium

```
Version: 1.78.2
Release: 23132
Commit: e06ea6147733c975d26c3d3552462681e05cb147
Date: 2023-05-12T00:17:05.317Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```
AsciiDoc extension v2.9.8

**Comment by ggrossetie** [comment]
I get the same warning when using Asciidoctor (Ruby) 2.0.20:

```console
$ cat test.adoc 
= Title

== Section 2.1

1. One
2. Two
3. Three

== Section 2.2

[start=4]
4. Four
5. Five
6. Six
```
```console
$ asciidoctor -v
Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
```console
$ asciidoctor test.adoc 
asciidoctor: WARNING: test.adoc: line 12: list item index: expected 1, got 4
asciidoctor: WARNING: test.adoc: line 13: list item index: expected 2, got 5
asciidoctor: WARNING: test.adoc: line 14: list item index: expected 3, got 6
```

You can omit the numbering in AsciiDoc (and thus avoid warnings):

```
==== Section 2.1

. One
. Two
. Three

==== Section 2.2

[start=4]
. Four
. Five
. Six
```

@mojavelinux should we address this "issue"?

**Comment by mojavelinux** [comment]
There's already an open issue for this. But fixing it is very complicated. I've tried on several occasions, but haven't been able to do it with the way the code is written.

**Comment by ggrossetie** [comment]
Upstream issue: https://github.com/asciidoctor/asciidoctor/issues/3252
