### ISSUE TITLE
Attribute coming from include files are missing in completion with 3.0.x

### ISSUE THREAD

**Issue by apupier** [asciidoctor/asciidoctor-vscode#727]
using a file like my.adoc:
```
== test

include::ref1.adoc[]

```
and a file ref1.adoc:
```
:aref1: test
```

calling completion in first file does not always provide the attributes of the included file where other attributes are defined.

one case working:
![Screenshot from 2023-06-12 15-21-54](https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/294c0fdd-7624-4183-90e4-6e692099101e)

one case not working:
![Screenshot from 2023-06-19 17-25-53](https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/a50998be-ee83-487b-a931-3c8840815009)

**Comment by apupier** [comment]
it works fine with 2.9.8

**Comment by apupier** [comment]
I tried to add several additional parameters from the [ProcessorOptions](https://github.com/asciidoctor/asciidoctor.js/blob/cba1da0a23f79b14be3a37b99a91f0e1b4cef0f3/packages/core/types/index.d.ts#L622):
https://github.com/apupier/asciidoctor-vscode/blob/261224c2f3f9f27bcb0fc7c03d0c860d7bb2c653/src/asciidocParser.ts#L120

```
    const document = processor.load(textDocument.getText(), {
      attributes: {
        'allow-uri-read': '',
        'env-vscode': '',
        env: 'vscode',
      },
      extension_registry: registry,
      sourcemap: true,
      safe: 'unsafe',
      'allow-uri-read': '',
      parse: true,
      catalog_assets: true,
      ...(baseDir && { base_dir: baseDir }),
    })
 ```

without success

**Comment by ggrossetie** [comment]
We only retrieve document attributes using: https://github.com/apupier/asciidoctor-vscode/blob/eece7d6dbcb7fcf3596cf3efa8168535d298990a/src/features/attributeReferenceProvider.ts#L10-L11

Attributes defined in the body are processed during the parse phase. Previously, the implementation was using a regular expression to get any attributes (i.e, any line that starts with `:`).

If you remove the empty lines it will work because all attributes will be defined as document attributes.

**Comment by ggrossetie** [comment]
The logic is here:

https://github.com/asciidoctor/asciidoctor-vscode/blob/45302b52a57c8e3ffdd37cdca3a4f7145df7be23/src/features/attributeReferenceProvider.ts#L7-L8

**Comment by apupier** [comment]
even without empty lines, with 3.0.8-dev, I do not have the completion for the attributes defined in a file which is "included":

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/8060f02a-e8fb-4f5b-8f5e-07ecd18481a2)

**Comment by ggrossetie** [comment]
Might be because you don't have a document title? 🤔 
Not sure, I will need to debug in VS code, I was testing using Asciidoctor.js directly.

**Comment by apupier** [comment]
something like?

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/891fd2fe-7d5d-4309-9f08-68d3a5719a3a)

**Comment by ggrossetie** [comment]
We need to add `safe: safe` (or `safe: unsafe`) otherwise the inclure directive is converted to a link.

**Comment by apupier** [comment]
isn't already added?

https://github.com/apupier/asciidoctor-vscode/blob/261224c2f3f9f27bcb0fc7c03d0c860d7bb2c653/src/asciidocParser.ts#L127

or you mean somewhere else?

**Comment by ggrossetie** [comment]
In the `attributeReferenceProvider.ts`:

https://github.com/asciidoctor/asciidoctor-vscode/blob/45302b52a57c8e3ffdd37cdca3a4f7145df7be23/src/features/attributeReferenceProvider.ts#L7-L8

**Comment by apupier** [comment]
The load that you are pointing https://github.com/asciidoctor/asciidoctor-vscode/blob/45302b52a57c8e3ffdd37cdca3a4f7145df7be23/src/features/attributeReferenceProvider.ts#L7-L8 is calling the code I pointed https://github.com/apupier/asciidoctor-vscode/blob/261224c2f3f9f27bcb0fc7c03d0c860d7bb2c653/src/asciidocParser.ts#L127

https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/3ba06e8c-f7a3-4e97-8b70-e1c09367b0c1

I do not understand how to provide the parameter in a different way than it is currently

**Comment by ggrossetie** [comment]
Oh sorry, I read `Asciidoctor.load(textDocument) ` instead of `AsciidocParser.load(textDocument)` 😬 

That's strange it should work... I'm probably missing something but I can't see it 🤔

**Comment by apupier** [comment]
Can it be related to this code which seems to say that it doesn't process "meaningfully" the includes?

https://github.com/asciidoctor/asciidoctor-vscode/blob/261224c2f3f9f27bcb0fc7c03d0c860d7bb2c653/src/asciidoctorFindIncludeProcessor.ts#L21-L27

**Comment by ggrossetie** [comment]
I forgot about this extension! Yes, you are correct this is definitely why it isn't working 👍

**Comment by ggrossetie** [comment]
We will probably need to create distinct functions depending on what we need.

**Comment by apupier** [comment]
I will start by creating the tests.

I would expect that the Asciidoctor core can be able to provide all attributes directly when passing the flags correctly. Is there an existing processor for includes in Asciidoctor core that we can reuse? or we will need to implement our own Include Processor? But surely there is some logic doing it somewhere even if not in a processor?

**Comment by apupier** [comment]
> Yes there's an existing include preprocessor (built-in) and you don't need to specify anything.

I wasn't able to find it or a way to activate it.

I tried:
* to not register the includeprocessor ```    asciidoctorFindIncludeProcessor.register(registry)```
* to remove the ```extension_registry: registry,``` in the options
* different variations of attributes and options:
** 'allow-uri-read': true,
** 'allow-uri-read': '',
** safe: 'unsafe',

**Comment by ggrossetie** [comment]
If I remove the `asciidoctorFindIncludeProcessor` then it's working as excepted:


**main.adoc**
```
= Main
:a-attr0: value0
:a-attr1: value1
include::attrs.adoc[]

content
```


**attrs.adoc**
```adoc
:a-attr3: value3
```

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/333276/70f79b9b-10c8-4c4d-b101-10f2084821ee)


As you can see, we have `a-attr0`,  `a-attr1` and  `a-attr3`.
