### ISSUE TITLE
Plantuml

### ISSUE THREAD

**Issue by KindaAlhammadehGraniten** [asciidoctor/asciidoctor-vscode#746]
Hi!
Yesterday after updating the AsciiDoc extension in Visual Studio all my plantuml diagrams didn't appear correctly as before.

This is my code:

````
[plantuml]
----
state Init

State CartonHandling{
    state "Idle" as CHI
    state "TransportIn" as TRI
    state "TransportOut" as TRO
    state "TamperEvidentApplication" as APL
    state "LabelChecking" as LCH

    [*] --> CHI 
    CHI --> TRI : Carton in place
    TRI --> APL : Carton ready for labelling
    APL --> LCH : Label applied
    LCH --> TRO : Vision results acquired
    TRO --> CHI : Carton in TMX
}

[*] --> Init
Init --> CartonHandling
----
````
It appeared so before:

<img width="553" alt="MicrosoftTeams-image (2)" src="https://github.com/asciidoctor/asciidoctor-vscode/assets/132544021/ca54310f-3794-4362-a348-6b50c2409826">

And now it is so:

<img width="226" alt="Screenshot 2023-07-12 094622" src="https://github.com/asciidoctor/asciidoctor-vscode/assets/132544021/c989bc9a-92f8-4a4f-a079-809c0cd39083">

Please how to solve this problem.

**Comment by ggrossetie** [comment]
Is `asciidoc.extensions.enableKroki` enabled in your settings?

**Comment by KindaAlhammadehGraniten** [comment]
It wasn't enabled, even before updating, but now after enabling it, the plantuml diagrams appear correctly.
Thanks a lot.

**Comment by ggrossetie** [comment]
I don't recall maybe it was enabled by default but since we are sending data to https://kroki.io some users requested to disable it by default.

**Comment by ggrossetie** [comment]
I've added a note in the Breaking changes section: https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v3.1.0
