### ISSUE TITLE
Preview does not respect :toclevels: in top level doc

### ISSUE THREAD

**Issue by glynb** [asciidoctor/asciidoctor-vscode#762]
Preview doesn't apply  :TOCLEVELS: as specified in top level document. Included (child) docs appear to override the value of :toclevels: in the parent document. This is new behaviour  in version 3.1.2 (this was also incorrect in 3.1.0, correct behaviour in 2.9.8)

Please see the difference in the _Table of Contents_ in the preview window in screenshots below

Expected behaviour ( in 2.9.8)...

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/31587300/d8bf8b58-d0e9-41cb-a3c2-233215b4dd8f)

Incorrect behaviour ( in 3.1.2)...

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/31587300/c6c97b89-a0f0-42e0-af48-a52f69a1425c)

example adoc content:

---
**_parent.adoc_**

:toc:
:toclevels: 1
:sectnums: 

:xrefstyle: full 

= Title - V3.1.2

== Level 1 - first

=== Level 2

:leveloffset: +2

include::child.adoc[]

:leveloffset: -2

==== Level 3

===== Level 4

== Level 1 - second

---
**_child.adoc_**

:toc:
:toclevels: 3
:sectnums: 

= Child

I'm the child doc

== child level 1

=== child level 2

==== child level 3

**_System info:_**

Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by ggrossetie** [comment]
To be honest, I don't have any clue... we delegate the work to the built-in HTML5 converter:

https://github.com/asciidoctor/asciidoctor-vscode/blob/ea37e351f185cd86f1c3b93f0afed5b9ec074b6f/src/asciidoctorWebViewConverter.ts#L311

My only guess is that somehow the `node` is not the parent document and we retrieve `:toclevels: 3` instead of `:toclevels: 1` but I don't understand how.

@mojavelinux If you have time I would love your insight/guess

**Comment by mojavelinux** [comment]
The explanation is pretty simple. The `toclevels` attribute must be set in the header. In the document provide, it is not. Please see https://docs.asciidoctor.org/asciidoc/latest/document/header/#document-header-structure

**Comment by ggrossetie** [comment]
I assumed that something was wrong in the extension because I get the "expected" behavior using the browser extension 🤔

**Comment by glynb** [comment]
Noted comment on header structure. (as per previous comment from @ggrossetie ) , applying the correct structure and simplifying the adocs, does still produce the unexpected output. Also tried asciidoctor and asciidoctor-pdf cli and they both give the expected result (with either header structure) 

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/31587300/62e43402-40e8-4f8f-9e24-508bd46cb285)

**Comment by mojavelinux** [comment]
Was it a matter of when it was called?

**Comment by ggrossetie** [comment]
Yes, I moved it after calling `getDocumentHeader`, see: https://github.com/asciidoctor/asciidoctor-vscode/commit/2ff98610c0974a69419a43ddaf76744c5c0685ee

**Comment by mojavelinux** [comment]
That means my suggested fix was incorrect, but the idea was the same. That ensures the right document attributes are available at the time `getContent()` is run.
