### ISSUE TITLE
Pretty HTML

### ISSUE THREAD

**Issue by cunka** [asciidoctor/asciidoctor-vscode#769]
Asciidoctor generates unformatted HTML.

It would be nice that a user can choose to run a HTML 'pretty' formatter on the generated HTML that is user set in the 'Preferences'.

**Comment by ggrossetie** [comment]
In my opinion, it would be better to keep this post-processing step outside of the VS code extension.

You can use any tool once you've exported to HTML. Alternatively, you can use an Asciidoctor Postprocessor extension: https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/postprocessor/

**Comment by ggrossetie** [comment]
I will close this issue since I believe this is out-of-scope (and will most likely be better handled by another extension)
