### ISSUE TITLE
Preview not working after update & Trouble passing asciidoctor attributes to preview

### ISSUE THREAD

**Issue by Pigmented** [asciidoctor/asciidoctor-vscode#771]
- Before the upgrade of asciidoctor-vscode, the preview of **.adoc** is OK. My **settings.json** is set as follows:
`"asciidoc.asciidoctor_command": "asciidoctor -v --failure-level=WARN -r asciidoctor-diagram"`
- Now I got two questions. 
1. VS Code fails to display the preview of images made by asciidoctor diagram; instead it shows only the source code as follows:
![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/129073565/e8c1e932-704d-4be3-9deb-27989e9ce1b9)
2. Code between **ifdef::backend-html5[]** and **endif::backend-html5[]** can not be displayed; but when using the command **asciidoctor output.adoc**, it works.
- So I've tried to solve these by two ways.
1. Add the asciidoctorAttributes parameter in **settings. json**; it doesn't work and I don't know how to add `- v` and -` r asciidoctor-diagram` to it.
```
    "asciidoc.preview.asciidoctorAttributes": 
   {
        "backend": "html5",
        "doctype": "article",
        "failure-level": "WARN"
    },
```
2. Add the **preview. asciidoctorconfig** to the project's root directory; it failed and I have no idea how to add `- v`, `- failure level=WARN`, and `- r asciidoctor-diagram` to it.
```
:backend: html5
:outlinelevels: 4:1
```

**Comment by ggrossetie** [comment]
Please read the release notes: https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v3.1.0

The Asciidoctor CLI was dropped in 3.x.

The VS code extension is now only using Asciidoctor.js. If you want to render diagrams, I would recommend using Asciidoctor Kroki.

If you want to preview your document using the Asciidoctor CLI (Ruby) then read the breaking changes section where we provide a workaround.

**Comment by Pigmented** [comment]
Thx. But could you explain why the following code doesn't work? See My Question 2 above.
`:backend: html5`
`:outlinelevels: 4:1`

**Comment by Pigmented** [comment]
Thx. But could you explain why the following code doesn't work? See My Question 2 above.
`:backend: html5`
`:outlinelevels: 4:1`

**Comment by ggrossetie** [comment]
The VS code preview is using a custom backend. The `backend` attribute is not modifiable (or more precisely, it will be ignored).

If you want to include something when Asciidoctor produces an HTML output, I think you should use the `basebackend` attribute (not modifiable). The value should be `html`.

In the future, please direct questions to the project chat at https://chat.asciidoctor.org

**Comment by Pigmented** [comment]
Thanks for the quick answer and clear explanation.
