### ISSUE TITLE
"Command" path option is no more in settings

### ISSUE THREAD

**Issue by Dedeou31** [asciidoctor/asciidoctor-vscode#785]
New version of the extension has remove the "Command" option.
My use case used this setting to overwrite the path to launch asciidoctor.
Eg: Command: python /home/<login>/.docops/TC0032/bin/launch_asciidoctor.py gen_html --env-vscode --asciidoctor

How can we do it with the new version ?
If not, is it possible to add this setting to allow user to manage a local launcher ?

Thanks in advance

**Comment by ggrossetie** [comment]
Hello,

The release note is addressing this breaking change:

> NOTE: If you want to keep using asciidoctor CLI, it's possible to setup a similar workflow using both the [HTML Preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) and [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extensions using the following settings.json:

```json
{
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.adoc$",
                "cmd": "asciidoctor ${file}"
            },
        ]
    }
}
```


This feature was removed because the maintenance burden was too high and arguably out-of-scope (i.e., better-handled by other extensions).
