### ISSUE TITLE
Live Preview and Open in Default Browser Not Working

### ISSUE THREAD

**Issue by tejwantk01** [asciidoctor/asciidoctor-vscode#786]
Hi guys. 

I have been coding on my MacBook and tried shifting all the files using Remote Tunnel from my Mac to Windows. But the problem I am getting now is that on my Windows desktop, the VS Code does not load the preview so I can't even see how my HTML, CSS, and JS look on websites. I downloaded two extensions called Live Preview and Show in Browser. When I press show preview, it gives me a blank white screen and when I press show in default browser, I get an error message saying "Windows cannot find" and then the file name (I think this is because all the files are only located on the Mac but I do not know how to completely transfer them over to my Windows. Also, when I open with Live Server, it opens on my Mac for some reason. 

I'll screenshot the two errors. If anyone knows a fix, please help.

![Screenshot 2023-09-17 172127](https://github.com/asciidoctor/asciidoctor-vscode/assets/103787266/2d540efd-fae1-46e7-a3c2-edb4b1164e27)
![Screenshot 2023-09-17 172320](https://github.com/asciidoctor/asciidoctor-vscode/assets/103787266/6056741d-aa93-46fa-87a1-e6b1f9054be6)

**Comment by ggrossetie** [comment]
Hello, I don't really see how this is related to the Asciidoctor VS code extension? Could you please clarify? Thanks!

**Comment by tejwantk01** [comment]
I think this is the wrong section to post it. You can take it down.
