### ISSUE TITLE
Preview rendering of barcode diagrams is not working

### ISSUE THREAD

**Issue by SjoerdV** [asciidoctor/asciidoctor-vscode#792]
Please provide details about:

* What you're trying to do
Preview rendering of barcode diagrams
* What happened
Preview is not rendering barcodes
* What you expected to happen
Preview should render barcodes, while pdf/html export does show barcodes in exported file through ruby gem

example: https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/barcode/
```
Barcodes can be written codabar:A31117013206375A[png, height=10] inline or as blocks.

[qrcode, format="png", xdim=4]
....
Hello World!
....
```

We'll also need your system information (get it under "Help" -> "About" in VS Code). Share the installed extension version 
Product: VS Codium
Version: 1.82.2
Release: 23257
OS: Linux x64
AsciiDoc: v3.1.5

**Comment by ggrossetie** [comment]
Asciidoctor Diagram is not available in a JavaScript environment and Asciidoctor Kroki does not support barcode.
In other words, this is an upstream "issue" (more specifically a feature request) and not something we can fix in the VS Code Extension.
