### ISSUE TITLE
Can not swith to other source code syntax highlighter to show line number

### ISSUE THREAD

**Issue by Jasper-Li** [asciidoctor/asciidoctor-vscode#803]
I want to show line number in source code.
As asciidoctor official doc says:

When using Asciidoctor, the only syntax highlighter that does not support line numbering is highlight.js.

Which is from: https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/#enable-line-numbering

I must switch to another syntax hightlighter like rouge, coderay.

Before I used an asciidoctor CLI in my local machine.

After "Asciidoctor CLI Dropped" from asciidoctor-vscode version 3.0, I failed to show line nubmer for a source block.

In a summary,

1. How to show line number in source bloock?
2. Methods to switch syntax highlighter

Thanks

**Comment by ggrossetie** [comment]
The VS Code Extension is written in JavaScript and uses Asciidoctor.js.
Highlight.js is the only built-in syntax highlighter supported by Asciidoctor.js.

If you want to use another syntax highlighter, you will need to use the `asciidoctor` CLI. As mentioned in the release notes, you can use both the [HTML Preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) and [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extensions with the following settings.json:

```json
{
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.adoc$",
                "cmd": "asciidoctor ${file}"
            },
        ]
    }
}
```

You can also setup a workflow outside of VS Code that relies on the `asciidoctor` CLI.

Another solution would be to integrate Prism as a syntax highlighter with the line number plugin: https://prismjs.com/plugins/line-numbers

Yet another solution would be to include https://github.com/wcoder/highlightjs-line-numbers.js using docinfo files (I don't recall if the VS Code Extension supports docinfo).

**Comment by Jasper-Li** [comment]
Thanks very much. I think the [HTML Preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) and [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) method is not smooth on using.

Prism or [highlightjs-line-numbers.js](https://github.com/wcoder/highlightjs-line-numbers.js) is a better solution.
Does developer team have a plan on source block line number showing? It's a common need on technical writing.

**Comment by ggrossetie** [comment]
Not sure but you could contribute to https://github.com/thom4parisot/asciidoctor-prism-extension/issues/2 if you want a syntax highlighter with line numbers
