### ISSUE TITLE
Style in `asciidoc.preview.style` can't be loaded

### ISSUE THREAD

**Issue by Mutantpenguin** [asciidoctor/asciidoctor-vscode#815]
When opening the preview, the *.css theme set via `asciidoc.preview.style` is not applied and a warning message is shown.

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/9027507/167d83e5-46a1-4b4a-a3b0-c6d4d865a9d0)

Link to repository which shows the problem:
https://github.com/Mutantpenguin/Universalis

System information:
```
Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

The problems exists with versions 3.1.6 and 3.1.7, with 3.1.5 (and earlier versions) it works great.

There is nothing to be found about this in the extension logs.

**Comment by ggrossetie** [comment]
Could you please try `./RegeIn/style/html-theme.css`

**Comment by cunka** [comment]
Just to confirm its not isolated - I have had the same issue with `asciidoc.preview.style` as Mutantpenguin and get the same error message - albeit, I am using my own custom stylesheet and not the one Mutantpenguin is using.

It was working, and working well.

**Comment by ggrossetie** [comment]
I can't see what changed between 3.1.5 and 3.1.7 🤔 
@cunka could you please share your error message? maybe I can find a pattern... are you on Windows? do you use `\\`? did you try to replace `\\` by `/` (since it's a URI and not a file path)

**Comment by Mutantpenguin** [comment]
> Could you please try `./RegeIn/style/html-theme.css`

I did so and it doesn't work and gives the same error message.

Even when I place the file directly in my workspace root so I don't need to use `\`, `\\` or `/` I get the same error message.

**Comment by ggrossetie** [comment]
I was able to reproduce it. It's not a path issue it's a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

```
index.html:1 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Nova+Round' because it violates the following Content Security Policy directive: "style-src 'self' 'self' https://*.vscode-cdn.net 'unsafe-inline' data:". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```
```
index.html:1 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Noto+Sans:300,600italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700' because it violates the following Content Security Policy directive: "style-src 'self' 'self' https://*.vscode-cdn.net 'unsafe-inline' data:". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```
```
index.html:1 Refused to load the stylesheet 'https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor@2.0/data/stylesheets/asciidoctor-default.css' because it violates the following Content Security Policy directive: "style-src 'self' 'self' https://*.vscode-cdn.net 'unsafe-inline' data:". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

You can workaround this issue by disabling the CSP.

**Comment by ggrossetie** [comment]
We probably need to add `https:` in `style-src` and `script-src`:

https://github.com/asciidoctor/asciidoctor-vscode/blob/2a145bfb674b6250d21018e9cc8bf223e38170ea/src/asciidoctorWebViewConverter.ts#L67-L75

**Comment by cunka** [comment]
Yes - I'm a WINDOWS 10 user.
Had the paths set up as `\` - as per this other bug i mentioned. [https://github.com/asciidoctor/asciidoctor-vscode/issues/777#issuecomment-1676297112](url)

It was working and I could use the webview to edit/modify the stylesheet all in VSCode and then stopped working.
Outside of the VSCode updates, I'm wondering if something was enforced by Microsoft in a recent OS update.

I'm glad you have found a solution.
