### ISSUE TITLE
Plantuml preview with local kroki of the diagram with target doesn't work 

### ISSUE THREAD

**Issue by agrexgh** [asciidoctor/asciidoctor-vscode#818]
Please provide details about:

* What you're trying to do
I'd like to preview plantuml diagram with this extension with local kroki
* What happened
  * With local kroki
  The preview shows not plantuml diagram with target but plantuml scripts(It doesn't work as I expected).
  The preview show plantuml diagram with target (It works as I expected).
  The settings.json includes below.
  ```
  "asciidoc.preview.asciidoctorAttributes": {
      "kroki-server-url": "http://localhost:8000",
      "allow-uri-read": true,
      "kroki-fetch-diagram": true
  }
  ```
  * With kroki.io
  The preview show plantuml diagram.
  The settings.json does ***NOT*** include any setting in below.
  ```
  "asciidoc.preview.asciidoctorAttributes": {
      "kroki-server-url": "http://localhost:8000",
      "allow-uri-read": true,
      "kroki-fetch-diagram": true
  }
  ```

* What you expected to happen
The preview shows plantuml diagram with target

Please share relevant sample content. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

How to reproduce
1.`docker run --rm -it -p 8000:8000 yuzutech/kroki`
2.Set below to settings.json  
  ```
  "asciidoc.preview.asciidoctorAttributes": {
      "kroki-server-url": "http://localhost:8000",
      "allow-uri-read": true,
      "kroki-fetch-diagram": true
  }
  ```

3. Open the adoc file. The content is below.  
  ```
  = test
  
  [plantuml]
  .without target
  ----
  @startuml sample
  bob -> alice : hello
  @enduml
  ----
  
  [plantuml,foo/bar]
  .with target
  ----
  @startuml sample
  marie -> john : good evening
  @enduml
  ----
  ```

We'll also need your system information (get it under "Help" -> "About" in VS Code). Share the installed extension version (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> or <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> on macOS).
`v3.1.7`

Provide steps to reproduce the issue and, if applicable, add screenshots to make it easier to understand. There is also extension logs where errors show up. Go to the Command Palette and select the option 'Developer: Open Extension Logs Folder'.
The screenshot shows that vs code doesn't show the Figure "with target" 's preview but the Figure "without target".
![previewOfDiagramWithTargetDoesnotWorkscreenshot](https://github.com/asciidoctor/asciidoctor-vscode/assets/47779973/c3863266-98dc-4e0b-aac9-2bdff9f01d82)

Look among the logs there for errors.

**Comment by ggrossetie** [comment]
`:kroki-fetch-diagram:` is not supported when running Asciidoctor Kroki in VS Code. The reason is that `unxhr` does not work in VS Code: https://github.com/ggrossetie/unxhr/issues/98

With the following configuration:

```
"asciidoc.preview.asciidoctorAttributes": {
    "allow-uri-read": true,
    "kroki-fetch-diagram": true
}
```

Asciidoctor Kroki won't work with either kroki.io or local instance.

I've updated the documentation: https://github.com/asciidoctor/asciidoctor-vscode/pull/820

**Comment by agrexgh** [comment]
@ggrossetie Thank you for replying.

I'd like to use local kroki to preview plantuml diagrams on asciidoc preview.
I understood ‘kroki-fetch-diagram‘ is necessary to do that, but unfortunately it's not supported.
Do you have any alternative solutions to preview plantuml diagrams with local kroki than ‘kroki-fetch-diagram‘?

**Comment by ggrossetie** [comment]
> I'd like to use local kroki to preview plantuml diagrams on asciidoc preview.
I understood ‘kroki-fetch-diagram‘ is necessary to do that, but unfortunately it's not supported.

You don't need `kroki-fetch-diagram` to use a local Kroki instance. This option is useful for publishing an HTML document without having a dependency on a Kroki instance. If it's just for local preview, there's no need for `kroki-fetch-diagram`. Otherwise, I recommend exporting to HTML outside of VS Code using the `asciidoctor` command line (where the `kroki-fetch-diagram` will work).

Did you understand that the option was necessary while reading the documentation? Maybe we need to clarify that.

**Comment by agrexgh** [comment]
@ggrossetie 
I understand that ‘kroki-fetch-diagram‘ was necessary based on the actual behavior of the extension, not from the documents.

I'll write "actual behavior".
With ‘kroki-fetch-diagram‘ diagrams were shown in the preview and without it diagrams weren't shown.
The version of this extension is v3.1.7.

**Comment by ggrossetie** [comment]
Do you still reproduce this issue with the latest version (3.1.8)?

Could you please try to reproduce in a clean environment:
- no other extension 
- reset your user and workspace settings
- install latest version of the AsciiDoc extension
- enable Kroki
- create a simple Asciidoc file with a diagram

Thanks!

**Comment by agrexgh** [comment]
@ggrossetie 
I tested with below

* no other extension
* reset user settings and add below(This includes enabling kroki.)
```json
{
  "asciidoc.extensions.enableKroki": true,
  "asciidoc.preview.asciidoctorAttributes": {
    "kroki-server-url": "http://localhost:8000"
  }
}
```
* I think the adoc content which I quoted in this issue origin is enough simple.

With `v3.1.8`: It works! The diagrams in preview was shown.
With `v3.1.7`: It doesn't work.

It seems this issue was fixed in `v3.1.8`,
I'd like to know what issue fixed this issue.
Do you know this?

**Comment by ggrossetie** [comment]
I made a fix to allow the Kroki server defined in the preview attributes (by adding it to the CSP rules)

Please note that it should also work in 3.1.7 if you disable the preview security.

**Comment by agrexgh** [comment]
> Please note that it should also work in 3.1.7 if you disable the preview security.

Excuse me, could you tell me how to disable the.preview security and enable it?

**Comment by ggrossetie** [comment]
When the preview is opened, open the command palette (https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-palette) and search for "Manage Preview Security Settings".

**Comment by agrexgh** [comment]
Thank you, I'll try it after a few days!

**Comment by agrexgh** [comment]
> When the preview is opened, open the command palette (https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-palette) and search for "Manage Preview Security Settings".

I tried this.
When preview security setting was "Allow insecure local content", the preview of plantuml was shown in also v3.9.7!
Thank you for telling it to me!

My problems were all solved:)

**Comment by canfoderiskii** [comment]
I cannot preview plantuml diagram via local kroki server now.

* OS: Debian 12
* AsciiDoc extension: 3.4.2 (installed directly inside vscode extension market)
* VSCode: 1.100.2
* Kroki: 0.28.0, Docker Image

* VSCode AsciiDoc configuration:

```javascript
"asciidoc.extensions.enableKroki": true,
"asciidoc.preview.asciidoctorAttributes": {
    "kroki-server-url": "http://localhost:8000"
}
```

What should I do next? I don't find any configuration error, or server configuration error
