### ISSUE TITLE
Follow-up, stylesheet not loading without an error

### ISSUE THREAD

**Issue by SjoerdV** [asciidoctor/asciidoctor-vscode#831]
Reference: https://github.com/asciidoctor/asciidoctor-vscode/issues/747#issuecomment-1841117164

Please provide details about:

* What you're trying to do: Loading specific css files configured in a nested folders for use in the vscode live preview
* What happened: Error is displayed in vscode (Could not load 'asciidoc.styles': resources/css/1-asciidoc.css), but stylesheet is loading
* What you expected to happen: no error displayed

REPRO:
* Minimal reproducible example folder structure is attached: [NotesFrame.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/13604165/NotesFrame.zip)

VSCODIUM DETAILS
Version: 1.84.2
Release: 23319
Commit: 1fc52b725b3f76b97eadfd988cea42a739ae923f
Date: 2023-11-15T21:57:44.436Z
Electron: 25.9.2
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.1.0-13-amd64

asciidoctor-vscode: v3.1.10

Provide steps to reproduce the issue:
- Open each of the adoc files (0.adoc, 1.adoc, 2.adoc, 3.adoc) in the vscode workspace

**Comment by SjoerdV** [comment]
It seems the issue has resolved itself, but I already created the frame for having multiple css files in a workspace (configured per folder) for use with Live Preview. So this might help someone setting this up.

**Comment by ggrossetie** [comment]
> It seems the issue has resolved itself 

🤔
