### ISSUE TITLE
Consistent code completion for includes

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-vscode#838]
Thank you for your tooling, it is great.

It would be nice, if code completion for includes would also work consistently.

Example:
````
include::../exercise_settings.adoc[]

include::../Flutter/[CURSOR HERE - PRESS CTRL + Space]

````

Result:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/139910/1dc2adc7-df8f-48b5-8092-418c5800377b)

Press ESC and trigger CTRL+Space again, you get a different result:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/139910/ab1ea686-292b-43b0-9f0f-422ff046e78c)

Press ESC again and trigger CTRL+Space again, you get again the first result.

**Comment by ggrossetie** [comment]
It's actually a bug, we were using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test which is **stateful**.

**Comment by vogella** [comment]
Thanks @ggrossetie for the fix. Is their a way to get the latest build version or do I have to wait for the next release? Currently my version says it was updated on 2024-01-19, 10:40:49

**Comment by ggrossetie** [comment]
I will release a new version in the next few days

**Comment by vogella** [comment]
Cool, thanks
