### ISSUE TITLE
Preview stops working if reference to bibliography entry exists in 3.2.1

### ISSUE THREAD

**Issue by TuxTom** [asciidoctor/asciidoctor-vscode#857]
* What you're trying to do
Preview my document that contains references to a bibliography entry
* What happened
As soon as the document contains a reference to a bibliography entry, the preview is not updated anymore, and an error message is shown: "TypeError: refNode.getTitle is not a function"
* What you expected to happen
The preview being updated

Minimal test document to reproduce:

> = Test
> 
> See &lt;&lt;ref>>
> 
> [bibliography]
> == Bibliography
> 
> * [[[ref]]] Reference

System Information:
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Extension version: v3.2.1

**Comment by ggrossetie** [comment]
@ViToni It seems that we need to make sure that `getTitle` is available on `refNode`. Could you please take a look?

**Comment by ViToni** [comment]
@ggrossetie I'll look into it.
@TuxTom Thanks for the reproducer.

**Comment by ViToni** [comment]
Seems the probem is even worse as all refs to anchors fail, so no bibliography needed to make it fial. This is a minimal example failing for me:
```
= Test

See <<inline_anchor>>

[[inline_anchor]]Some text
```
PR #859 should fix the underlying issue.

**Comment by ViToni** [comment]
@TuxTom May you give the branch from the PR a try.
@ggrossetie Could you review the PR.

**Comment by TuxTom** [comment]
@ViToni Tried the branch, this indeed fixes the issue for me.

Thanks for the swift response!
