### ISSUE TITLE
`package.json` and `package-lock.json` are not in sync after `prepare branch for development [no ci]`

### ISSUE THREAD

**Issue by ViToni** [asciidoctor/asciidoctor-vscode#862]
Please provide details about:

* What you're trying to do: `npm install`
* What happened: `package-lock.json` gets modified because it has a different project version than `package.json`
* What you expected to happen: Whenever the project version gets bumped the project versions should match between `package.json` and `package-lock.json`. Otherwise the first PR after the version bump must contain the "unrelated fix" for `package-lock.json`.

There are commits only changing `package.json`:

- 417917a
- 2235846
- 26c8034

**Comment by ggrossetie** [comment]
I guess we should run `npm i --package-lock-only` after:

https://github.com/asciidoctor/asciidoctor-vscode/blob/6f20e7b898a160d9dc5e1c24bbc4295542e8d686/release.sh#L31

Having said that, the npm documentation says:

> Run this in a package directory to bump the version and write the new data back to package.json, package-lock.json, and, if present, npm-shrinkwrap.json.

So it might be a bug in npm? I'm not sure if not updating the version in the `package-lock.json` is expected or not... 🤔

**Comment by ggrossetie** [comment]
Maybe we should use `npm version` with `--no-git-tag-version`
