### ISSUE TITLE
xrefstyle is not honored when displaying xrefs

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-vscode#889]
I was trying to help with [this discussion](https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/Referring.20to.20a.20table.20as.20Table.201.20iso.20the.20title.20of.20the.20table) and tested the behavior in my VSCode.

This example was provided by Dan to show how to do it but in my VSCode it wouldn't work right.

```
= Document Title
:xrefstyle: short

See <<my-table>> for more reference.

.Title of my table
[#my-table]
|===
|data
|===
```

What I would expect to see is "Table 1" as the link text. I get the text from the auto-id instead.

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/4920542/65539e4a-a87b-452e-b757-930757517261)

The browser extension shows it correctly:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/4920542/49cfd236-4d05-482c-a22f-f51f54603793)

**Comment by r0ckarong** [comment]
Explicitly setting the xref as macro with the style "short" doesn't work either:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/4920542/a1a38756-6eed-48ad-9b9e-e6862ddd4f98)

```
= Document Title
:xrefstyle: short

See <<my-table>> for more reference.

See xref:my-table[xrefstyle=short] for more reference.

.Title of my table
[#my-table]
|===
|data
|===
```

**Comment by ggrossetie** [comment]
Also related to https://github.com/asciidoctor/asciidoctor-vscode/pull/853 where we are using a custom converter for xref to support link (href) in the preview.

Basically, we don't support all the xref features and we need to implement them in the `asciidoctorWebViewConverter`. Feel free to open a pull request to implement the missing features. You can take a look at: https://github.com/asciidoctor/asciidoctor/blob/e070613f0932b18cfb64370a8f0b6a0831eee4cd/lib/asciidoctor/converter/html5.rb#L1131-L1154

**Comment by ggrossetie** [comment]
Thanks for the minimal reproduction case that was really helpful 🤗 
I was able to add a test to make sure that my changes actually fixed this issue: https://github.com/asciidoctor/asciidoctor-vscode/pull/911
