### ISSUE TITLE
[Feature Request] Point asciidoc.preview.asciidoctorAttributes to file which holds attributes

### ISSUE THREAD

**Issue by bai-yi-bai** [asciidoctor/asciidoctor-vscode#892]
Please provide details about:

* Currently, asciidoc.preview.asciidoctorAttributes takes an array of attributes. I would like to know if it is possible to detect if there is a string/filename and load the attributes from the file.
* I currently use Antora and instruct my users to clone a git repository which contains our template and copy a number of files for their new projects, this includes the settings.json file. We currently have all our branding defined as attributes in a different  distributed repository. We use an include:: statement at the top of every .adoc file. This means that none of our attributes resolve in the preview or local render. 
* I was interested in using the https://github.com/redpanda-data/docs-extensions-and-macros/blob/main/extensions/add-global-attributes.js extension, but because we have too many attributes we run into the Windows CLI limit of 8,191 characters asciidoctor-pdf doesn't work. I am writing an extension which only imports attributes used in a rendered document. 
* My idea is generate an antoraattributes.json file each time Antora is run. This would give the user the ability to use the local preview in Visual Studio Code. 
* I intend to add this generated antoraattributes.json file to the .gitignore, because I don't want users to rely upon it as a permanent source of truth, since there is no facility to keep it in sync with our "shared" repository. Plus, we have a lot of nested attributes-in-attributes, which json isn't compatible with.
* Alternatively, we could add our 'shared' repository as a git sub repo, and point the asciidoc.preview.asciidoctorAttributes to the .yaml/json file in it.

**Comment by ggrossetie** [comment]
This extension supports the Asciidoctor config file feature as described in: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html

I guess that should solve your issue?

> We use an include:: statement at the top of every .adoc file. This means that none of our attributes resolve in the preview or local render.

I don't think attributes should be defined in a distributed component. Might be better to define them in the playbook?

> I intend to add this generated antoraattributes.json file to the .gitignore, because I don't want users to rely upon it as a permanent source of truth, since there is no facility to keep it in sync with our "shared" repository. Plus, we have a lot of nested attributes-in-attributes, which json isn't compatible with.

The `settings.json` already contains the Asciidoctor attributes:

```json
{
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "redhat.telemetry.enabled": true,
    "asciidoc.preview.refreshInterval": 0,
    "asciidoc.preview.scrollEditorWithPreview": false,
    "asciidoc.preview.templates": [],
    "asciidoc.antora.enableAntoraSupport": true,
    "asciidoc.preview.asciidoctorAttributes": {
        "foo": "bar"
    },
}
```

If you can retrieve all your attributes, it would be better to either generate an `.asciidoctorconfig` file or generate the `settings.json`.
Please note that the `.asciidoctorconfig` can contain attribute references.

**Comment by bai-yi-bai** [comment]
This is excellent! Thank you so much. I've got a thread on the zulipchat about my attribute strategy, but this solves the problem of preview in VSC.
