### ISSUE TITLE
ENOENT: ENOENT: no such file or directory, open '/home/data/stylesheets/coderay-asciidoctor.css'

### ISSUE THREAD

**Issue by thoraxe** [asciidoctor/asciidoctor-vscode#91]
Just trying to install this extension and when attempting to use preview mode I get the error:

`ENOENT: ENOENT: no such file or directory, open '/home/data/stylesheets/coderay-asciidoctor.css'`

I am assuming this is some kind of setting error. But the interesting thing is that `coderay-asciidoctor.css` doesn't appear anywhere in the code of this repo...

**Comment by thoraxe** [comment]
So this appears to be related to a setting in my actual asciidoc file:

`:source-highlighter: coderay`

I guess the question is regarding the configuration of the source hilighter and how you tell `asciidoctor-vscode` where to find the relevant CSS file?

**Comment by danyill** [comment]
The integrated preview with `asciidoctor.js` doesn't support coderay.

If you're externally using Ruby you must install coderay before you use it as a syntax highlighter. Refer to the [Asciidoctor user manual](https://asciidoctor.org/docs/user-manual/#coderay)

See also [here](https://asciidoctor.org/docs/user-manual/#available-source-highlighters) for the source highlighters available for different processors.

I'll close this issue as it's unrelated to this extension. Feel free to re-open if this doesn't address your concerns.
