### ISSUE TITLE
Preview displayed to the side shows Error in 3.4 Release

### ISSUE THREAD

**Issue by Kruzntat** [asciidoctor/asciidoctor-vscode#913]
Please provide details about: I updated my AsciiDoc from 3.3.1 to 3.4, but the side panel was unable to provide a preview of my document in the correct formatting. Instead, it only displayed "Error, unable to preview". I had to revert back to version 3.3.1 to fix the issue.

* What you're trying to do: Preview Asciidoc in the side panel
* What happened: "Error" displayed in the review panel with no display
* What you expected to happen:  A preview of mt asciidoc

Windows 10, Precision 5570
VScode - Version 1.94.2 | Node.js 20.16.0 | OS: Windows_NT x64 10.0.19045

Provide steps to reproduce the issue and, if applicable, add screenshots to make it easier to understand. There is also extension logs where errors show up. Go to the Command Palette and select the option 'Developer: Open Extension Logs Folder'.

1. Click on VScode plugins
2. Select Asciidoc
3. Click update
4. Restart Application

Installed specific version 3.3.1 for the fix. No logs are available at this time
'Developer: Open Extension Logs Folder'. - Result in an Error

**Comment by ggrossetie** [comment]
Could you please share a screencast with the developer tools opened? You should see an error in the Console tab (in the developer tools).

Without a stacktrace (i.e., an error message) it's hard to know what went wrong.

Thanks!

**Comment by SaschaWillems** [comment]
Same here. Previews no longer work, I only get aforementioned error message. Here is a screencap of the developer console:

![image](https://github.com/user-attachments/assets/0d32d670-d17e-4fc5-8369-ebd45dfffe62)

**Comment by ggrossetie** [comment]
Thanks @SaschaWillems

So it seems related to #910. Could you please show the content of the folder `(...)\asciidoctor.asciidoctor-vscode-3.4.0\node_modules\@vscode\ripgrep\bin` ?

**Comment by ggrossetie** [comment]
I think the issue is that the extension is packaged on Linux (x86_64) and, as a result, only the `rg` binary for this platform is available. Since VS code seems to be using ripgrep, it might be possible to use the built-in/bundled binary.

**Comment by ggrossetie** [comment]
I think I found a solution, version 3.4.1 will be available shortly.
@SaschaWillems @Kruzntat could you please give it a try?

**Comment by SaschaWillems** [comment]
Can confirm. Works again with 3.4.1.

Thank you very much for fixing this so fast. Very much appreciated 👍🏻

**Comment by ggrossetie** [comment]
Yay!
Thank you for providing the error message that was really helpful 👍🏻
