### ISSUE TITLE
Error: spawn rg.exe ENOENT with 3.4.1 and VS code < 1.94

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-vscode#915]
On my machine the path to the `rg` binary was:
 ```
C:\path\to\Microsoft VS Code\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin
```

Not really sure how we can reliably determine if the VS code application is using asar or not. It seems that asar is currently disabled since VS code moved to ESM: https://github.com/microsoft/vscode/blob/7cb8970c0fbcef3ae74f29242f49f57cc5e03929/build/linux/dependencies-generator.ts#L50

We might need to test if the binary file exists in one of these locations.

For reference, here's what VS code is using to call the `rg` binary: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/search/node/ripgrepTextSearchEngine.ts

**Comment by ryan-carpenter** [comment]
Is this a Windows-specific issue? After updating to 3.4.1 I could not preview any documents on my Linux system. The preview only showed "An error occurred while loading view: asciidoc.preview". I rolled back to version 3.3.1 and the preview worked again. I'll open another issue if needed. Note: this was in VS Codium 

```
Version: 1.94.2
Release: 24286
Commit: 62f778783c52510c94e687de293bc2ad230f9a67
Date: 2024-10-12T20:14:54.465Z
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.11.2-1-default
```

**Comment by ggrossetie** [comment]
@ryan-carpenter This issue was not related to Windows but to an outdated version of VS code where ASAR packaging where enabled. VS code 1.94.2 should not have ASAR enabled but I think that VS code will re-enable it sooner or later.

Could you please open the developer tools and copy/paste the error message? It might be another issue.
