### ISSUE TITLE
AsciiDoc Preview in VS Code - Displays Markdown Syntax Instead of AsciiDoc Formatting

### ISSUE THREAD

**Issue by levietduc0712** [asciidoctor/asciidoctor-vscode#918]
Hi all,

When opening `.adoc` file in VS Code, I encountered a problem where the preview incorrectly displays the file as Markdown syntax instead of rendering it with the correct AsciiDoc format. 

![image](https://github.com/user-attachments/assets/c7a41df9-c5a2-499f-8abf-655954b09457)

Here is the details of my system.

* AsciiDoc version: v3.4.1
* VSCode Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

I have attempted disabling other Markdown-related extensions, but the issue persists. It would be helpful if the AsciiDoc extension could override any conflicting syntax interpretations to ensure accurate rendering.

Thank you for looking into this! Let me know if any additional information is needed.

**Comment by ggrossetie** [comment]
It seems like the file extension .adoc is associated with the Markdown extension (built-in). It's probably a configuration/setting issue. Is the AsciiDoc extension correctly installed? You might want to reset your settings: https://stackoverflow.com/questions/36108515/how-to-reset-settings-in-visual-studio-code

**Comment by levietduc0712** [comment]
Hi Guillaume,

Thanks so much for your response! You were absolutely right; it was indeed a configuration issue with the file associations. After checking my `settings.json` file, I found the following lines:
```
"files.associations": {
    "*.py": "python",
    "*.adoc": "markdown"
}
```
Changing `"*.adoc": "markdown"` to `"*.adoc": "asciidoc"` solved the problem perfectly!

Thanks again for pointing me in the right direction – your advice saved me a lot of time!

**Comment by ggrossetie** [comment]
I'm glad your problem is solved!
Feel free to join https://asciidoctor.zulipchat.com/ if you have questions or if you want to chat about Asciidoctor and the VS code extension.
