### ISSUE TITLE
ToC links was not take me to the section when clicked on

### ISSUE THREAD

**Issue by moliyadi** [asciidoctor/asciidoctor-vscode#92]
```
= Document Title
:toc:
:numbered:

== Header

some text

=== Header

some text

== Header
```

Open side preview, click on toc link, not go to the section.

VSCode: 1.23.1
AsciiDoc: 0.12.0

**Comment by danyill** [comment]
This is working fine in the current version of the extension so I'll close this issue.

Feel free to reopen if you are able to test and come to any different conclusion.
