### ISSUE TITLE
Show heading tree in outline view

### ISSUE THREAD

**Issue by bitfield** [asciidoctor/asciidoctor-vscode#95]
Now that outline support in Code is out of preview, it would be great if the Outline view on an Asciidoc file showed the headings in a (foldable) tree, like the Markdown extension:

![screen shot 2018-07-06 at 12 44 19](https://user-images.githubusercontent.com/142262/42377213-4f924332-811a-11e8-9503-417c67f83899.png)

I would be most grateful for this, as I am using Asciidoc to write a book, currently at 12 chapters and 100,000 words, and the outline view is ideal for navigating inside chapters.

**Comment by naltatis** [comment]
I'm not sure which version introduced it and I can't find it in the CHANGELOG. But VSCode now shows proper outlines for .adoc documents 💚💛

![outline](https://user-images.githubusercontent.com/152287/69481714-db9eb400-0e13-11ea-80a6-04f823cc743c.png)

**Comment by joaompinto** [comment]
It was probably fixed in 2.7.7, related to https://github.com/asciidoctor/asciidoctor-vscode/pull/234 .
Thanks for the feedback :)
