### ISSUE TITLE
asciidoctor preview does not work with SSH FS

### ISSUE THREAD

**Issue by alexfederlin** [asciidoctor/asciidoctor-vscode#96]
I am using kelvin.vscode-sshfs to access and edit files on a remote filesystem on a linux machine with my local VS Code on my Windows machine.

The Asciidoctor preview apparently cannot deal with this. None of the includes in my adoc files are resolved. It works when I check out and edit the files locally, but when doing the preview on the remote files, all I get is

Unresolved directive in <stdin> - include::...

Also images are not included.

**Comment by joaompinto** [comment]
Could you please test with the new preview release ?

https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99 .

Any feedback is welcome.

**Comment by danyill** [comment]
Closed due to lack of response. Feel free to open if you manage to test this and can provide feedback.
