### ISSUE TITLE
Live preview does not work with VS Live Share

### ISSUE THREAD

**Issue by khengling** [asciidoctor/asciidoctor-vscode#97]
Live preview does not work in participant site (those that join a sharing session) in VS Live Share. It only works in the host site (those that start a sharing session).

An error message appears in the participant site when live preview is requested:

> Command 'adoc.preview' not found

Appreciate if the problem can be fixed (:

**Comment by joaompinto** [comment]
Could you please test with the new preview release ?

https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.99 .


Any feedback is welcome.
